// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSComboBoxCell;

class NSComboBoxCell
{
    public static function initTextCell(string string_) -> int
    {
        return nscomboboxcell_init_text_cell(string_);
    }

    public static function hasVerticalScroller(int handle) -> bool
    {
        int r;

        let r = nscomboboxcell_has_vertical_scroller(handle);

        return r == 1;
    }

    public static function setHasVerticalScroller(int handle, bool hasVerticalScroller) -> void
    {
        nscomboboxcell_set_has_vertical_scroller(handle, hasVerticalScroller);
    }

    public static function intercellSpacing(int handle) -> array
    {
        var result;

        let result = nscomboboxcell_intercell_spacing(handle);

        return result;
    }

    public static function setIntercellSpacing(int handle, double width, double height) -> void
    {
        nscomboboxcell_set_intercell_spacing(handle, width, height);
    }

    public static function itemHeight(int handle) -> double
    {
        return nscomboboxcell_item_height(handle);
    }

    public static function setItemHeight(int handle, double itemHeight) -> void
    {
        nscomboboxcell_set_item_height(handle, itemHeight);
    }

    public static function numberOfVisibleItems(int handle) -> int
    {
        return nscomboboxcell_number_of_visible_items(handle);
    }

    public static function setNumberOfVisibleItems(int handle, int numberOfVisibleItems) -> void
    {
        nscomboboxcell_set_number_of_visible_items(handle, numberOfVisibleItems);
    }

    public static function isButtonBordered(int handle) -> bool
    {
        int r;

        let r = nscomboboxcell_is_button_bordered(handle);

        return r == 1;
    }

    public static function setButtonBordered(int handle, bool buttonBordered) -> void
    {
        nscomboboxcell_set_button_bordered(handle, buttonBordered);
    }

    public static function reloadData(int handle) -> void
    {
        nscomboboxcell_reload_data(handle);
    }

    public static function noteNumberOfItemsChanged(int handle) -> void
    {
        nscomboboxcell_note_number_of_items_changed(handle);
    }

    public static function usesDataSource(int handle) -> bool
    {
        int r;

        let r = nscomboboxcell_uses_data_source(handle);

        return r == 1;
    }

    public static function setUsesDataSource(int handle, bool usesDataSource) -> void
    {
        nscomboboxcell_set_uses_data_source(handle, usesDataSource);
    }

    public static function scrollItemAtIndexToTop(int handle, int index) -> void
    {
        nscomboboxcell_scroll_item_at_index_to_top(handle, index);
    }

    public static function scrollItemAtIndexToVisible(int handle, int index) -> void
    {
        nscomboboxcell_scroll_item_at_index_to_visible(handle, index);
    }

    public static function selectItemAtIndex(int handle, int index) -> void
    {
        nscomboboxcell_select_item_at_index(handle, index);
    }

    public static function deselectItemAtIndex(int handle, int index) -> void
    {
        nscomboboxcell_deselect_item_at_index(handle, index);
    }

    public static function indexOfSelectedItem(int handle) -> int
    {
        return nscomboboxcell_index_of_selected_item(handle);
    }

    public static function numberOfItems(int handle) -> int
    {
        return nscomboboxcell_number_of_items(handle);
    }

    public static function completes(int handle) -> bool
    {
        int r;

        let r = nscomboboxcell_completes(handle);

        return r == 1;
    }

    public static function setCompletes(int handle, bool completes) -> void
    {
        nscomboboxcell_set_completes(handle, completes);
    }

    public static function completedString(int handle, string string_) -> var
    {
        var result;

        let result = nscomboboxcell_completed_string(handle, string_);

        return result;
    }

    public static function dataSource(int handle) -> int
    {
        return nscomboboxcell_data_source(handle);
    }

    public static function setDataSource(int handle, int dataSource) -> void
    {
        nscomboboxcell_set_data_source(handle, dataSource);
    }

    public static function addItemWithObjectValue(int handle, int object_) -> void
    {
        nscomboboxcell_add_item_with_object_value(handle, object_);
    }

    public static function addItemsWithObjectValues(int handle, array objects) -> void
    {
        nscomboboxcell_add_items_with_object_values(handle, objects);
    }

    public static function insertItemWithObjectValueAtIndex(int handle, int object_, int index) -> void
    {
        nscomboboxcell_insert_item_with_object_value_at_index(handle, object_, index);
    }

    public static function removeItemWithObjectValue(int handle, int object_) -> void
    {
        nscomboboxcell_remove_item_with_object_value(handle, object_);
    }

    public static function removeItemAtIndex(int handle, int index) -> void
    {
        nscomboboxcell_remove_item_at_index(handle, index);
    }

    public static function removeAllItems(int handle) -> void
    {
        nscomboboxcell_remove_all_items(handle);
    }

    public static function selectItemWithObjectValue(int handle, int object_) -> void
    {
        nscomboboxcell_select_item_with_object_value(handle, object_);
    }

    public static function itemObjectValueAtIndex(int handle, int index) -> int
    {
        return nscomboboxcell_item_object_value_at_index(handle, index);
    }

    public static function objectValueOfSelectedItem(int handle) -> int
    {
        return nscomboboxcell_object_value_of_selected_item(handle);
    }

    public static function indexOfItemWithObjectValue(int handle, int object_) -> int
    {
        return nscomboboxcell_index_of_item_with_object_value(handle, object_);
    }

    public static function objectValues(int handle) -> array
    {
        var result;

        let result = nscomboboxcell_object_values(handle);

        return result;
    }
}
