// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSAlert;

class NSAlert
{
    public static function init() -> int
    {
        return nsalert_init();
    }

    public static function alertWithError(int error) -> int
    {
        return nsalert_alert_with_error(error);
    }

    public static function messageText(int handle) -> string
    {
        var result;

        let result = nsalert_message_text(handle);

        return result;
    }

    public static function setMessageText(int handle, string messageText) -> void
    {
        nsalert_set_message_text(handle, messageText);
    }

    public static function informativeText(int handle) -> string
    {
        var result;

        let result = nsalert_informative_text(handle);

        return result;
    }

    public static function setInformativeText(int handle, string informativeText) -> void
    {
        nsalert_set_informative_text(handle, informativeText);
    }

    public static function icon(int handle) -> int
    {
        return nsalert_icon(handle);
    }

    public static function setIcon(int handle, int icon) -> void
    {
        nsalert_set_icon(handle, icon);
    }

    public static function addButtonWithTitle(int handle, string title) -> int
    {
        return nsalert_add_button_with_title(handle, title);
    }

    public static function buttons(int handle) -> array
    {
        var result;

        let result = nsalert_buttons(handle);

        return result;
    }

    public static function alertStyle(int handle) -> int
    {
        return nsalert_alert_style(handle);
    }

    public static function setAlertStyle(int handle, int alertStyle) -> void
    {
        nsalert_set_alert_style(handle, alertStyle);
    }

    public static function showsHelp(int handle) -> bool
    {
        int r;

        let r = nsalert_shows_help(handle);

        return r == 1;
    }

    public static function setShowsHelp(int handle, bool showsHelp) -> void
    {
        nsalert_set_shows_help(handle, showsHelp);
    }

    public static function helpAnchor(int handle) -> var
    {
        var result;

        let result = nsalert_help_anchor(handle);

        return result;
    }

    public static function setHelpAnchor(int handle, var helpAnchor) -> void
    {
        nsalert_set_help_anchor(handle, helpAnchor);
    }

    public static function delegate(int handle) -> int
    {
        return nsalert_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nsalert_set_delegate(handle, delegate);
    }

    public static function accessoryView(int handle) -> int
    {
        return nsalert_accessory_view(handle);
    }

    public static function setAccessoryView(int handle, int accessoryView) -> void
    {
        nsalert_set_accessory_view(handle, accessoryView);
    }

    public static function layout(int handle) -> void
    {
        nsalert_layout(handle);
    }

    public static function runModal(int handle) -> int
    {
        return nsalert_run_modal(handle);
    }

    public static function showsSuppressionButton(int handle) -> bool
    {
        int r;

        let r = nsalert_shows_suppression_button(handle);

        return r == 1;
    }

    public static function setShowsSuppressionButton(int handle, bool showsSuppressionButton) -> void
    {
        nsalert_set_shows_suppression_button(handle, showsSuppressionButton);
    }

    public static function suppressionButton(int handle) -> int
    {
        return nsalert_suppression_button(handle);
    }

    public static function window(int handle) -> int
    {
        return nsalert_window(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (void)beginSheetModalForWindow:(NSWindow *)sheetWindow completionHandler:(void (^ _Nullable)(NSModalResponse returnCode))handler — block
    // @reserved + (NSAlert *)alertWithMessageText:(nullable NSString *)message defaultButton:(nullable NSString *)defaultButton alternateButton:(nullable NSString *)alternateButton otherButton:(nullable NSString *)otherButton informativeTextWithFormat:(NSString *)format, ... API_DEPRECATED
    // @reserved - (void)beginSheetModalForWindow:(NSWindow *)window modalDelegate:(nullable id)delegate didEndSelector:(nullable SEL)didEndSelector contextInfo:(nullable void *)contextInfo API_DEPRECATED

}
