
extern zend_class_entry *appkit_ns_nstextinsertionindicator_nstextinsertionindicator_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator);

PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, create);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, wrap);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, destroy);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, nsTextInsertionIndicator);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setDisplayMode);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, getDisplayMode);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setColor);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, getColor);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setAutomaticModeOptions);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, getAutomaticModeOptions);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setEffectsViewInserterParent);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, clearEffectsViewInserter);
PHP_METHOD(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, hasEffectsViewInserter);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_create, 0, 4, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTextInsertionIndicatorPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_nstextinsertionindicator, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_setdisplaymode, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, mode, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_getdisplaymode, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_setcolor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, color, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_getcolor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_setautomaticmodeoptions, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_getautomaticmodeoptions, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_seteffectsviewinserterparent, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, parentView, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_cleareffectsviewinserter, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_haseffectsviewinserter, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, indicator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstextinsertionindicator_nstextinsertionindicator_method_entry) {
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, create, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, wrap, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, destroy, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, nsTextInsertionIndicator, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_nstextinsertionindicator, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setDisplayMode, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_setdisplaymode, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, getDisplayMode, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_getdisplaymode, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setColor, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_setcolor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, getColor, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_getcolor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setAutomaticModeOptions, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_setautomaticmodeoptions, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, getAutomaticModeOptions, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_getautomaticmodeoptions, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, setEffectsViewInserterParent, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_seteffectsviewinserterparent, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, clearEffectsViewInserter, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_cleareffectsviewinserter, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator, hasEffectsViewInserter, arginfo_appkit_ns_nstextinsertionindicator_nstextinsertionindicator_haseffectsviewinserter, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
