// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSTabViewItem;

class NSTabViewItem
{
    public static function tabViewItemWithViewController(int viewController) -> int
    {
        return nstabviewitem_tab_view_item_with_view_controller(viewController);
    }

    public static function initWithIdentifier(int identifier) -> int
    {
        return nstabviewitem_init_with_identifier(identifier);
    }

    public static function identifier(int handle) -> int
    {
        return nstabviewitem_identifier(handle);
    }

    public static function setIdentifier(int handle, int identifier) -> void
    {
        nstabviewitem_set_identifier(handle, identifier);
    }

    public static function color(int handle) -> int
    {
        return nstabviewitem_color(handle);
    }

    public static function setColor(int handle, int color) -> void
    {
        nstabviewitem_set_color(handle, color);
    }

    public static function label(int handle) -> string
    {
        var result;

        let result = nstabviewitem_label(handle);

        return result;
    }

    public static function setLabel(int handle, string label) -> void
    {
        nstabviewitem_set_label(handle, label);
    }

    public static function image(int handle) -> int
    {
        return nstabviewitem_image(handle);
    }

    public static function setImage(int handle, int image) -> void
    {
        nstabviewitem_set_image(handle, image);
    }

    public static function view(int handle) -> int
    {
        return nstabviewitem_view(handle);
    }

    public static function setView(int handle, int view) -> void
    {
        nstabviewitem_set_view(handle, view);
    }

    public static function viewController(int handle) -> int
    {
        return nstabviewitem_view_controller(handle);
    }

    public static function setViewController(int handle, int viewController) -> void
    {
        nstabviewitem_set_view_controller(handle, viewController);
    }

    public static function tabState(int handle) -> int
    {
        return nstabviewitem_tab_state(handle);
    }

    public static function tabView(int handle) -> int
    {
        return nstabviewitem_tab_view(handle);
    }

    public static function initialFirstResponder(int handle) -> int
    {
        return nstabviewitem_initial_first_responder(handle);
    }

    public static function setInitialFirstResponder(int handle, int initialFirstResponder) -> void
    {
        nstabviewitem_set_initial_first_responder(handle, initialFirstResponder);
    }

    public static function toolTip(int handle) -> var
    {
        var result;

        let result = nstabviewitem_tool_tip(handle);

        return result;
    }

    public static function setToolTip(int handle, var toolTip) -> void
    {
        nstabviewitem_set_tool_tip(handle, toolTip);
    }

    public static function drawLabelInRect(int handle, bool shouldTruncateLabel, double x, double y, double width, double height) -> void
    {
        nstabviewitem_draw_label_in_rect(handle, shouldTruncateLabel, x, y, width, height);
    }

    public static function sizeOfLabel(int handle, bool computeMin) -> array
    {
        var result;

        let result = nstabviewitem_size_of_label(handle, computeMin);

        return result;
    }
}
