// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSAttributedString;

class NSAttributedString
{
    public static function initWithString(string str) -> int
    {
        return nsattributedstring_init_with_string(str);
    }

    public static function initWithStringAttributes(string str, var attributes) -> int
    {
        return nsattributedstring_init_with_string_attributes(str, attributes);
    }

    public static function string_(int handle) -> var
    {
        var result;

        let result = nsattributedstring_string(handle);

        return result;
    }

    public static function length(int handle) -> int
    {
        return nsattributedstring_length(handle);
    }
}
