// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSCollectionViewLayoutInvalidationContext;

class NSCollectionViewLayoutInvalidationContext
{
    public static function init() -> int
    {
        return nscollectionviewlayoutinvalidationcontext_init();
    }

    public static function invalidateEverything(int handle) -> bool
    {
        int r;

        let r = nscollectionviewlayoutinvalidationcontext_invalidate_everything(handle);

        return r == 1;
    }

    public static function invalidateDataSourceCounts(int handle) -> bool
    {
        int r;

        let r = nscollectionviewlayoutinvalidationcontext_invalidate_data_source_counts(handle);

        return r == 1;
    }

    public static function invalidateItemsAtIndexPaths(int handle, array indexPaths) -> void
    {
        nscollectionviewlayoutinvalidationcontext_invalidate_items_at_index_paths(handle, indexPaths);
    }

    public static function invalidateSupplementaryElementsOfKindAtIndexPaths(int handle, string elementKind, array indexPaths) -> void
    {
        nscollectionviewlayoutinvalidationcontext_invalidate_supplementary_elements_of_kind_at_index_paths(handle, elementKind, indexPaths);
    }

    public static function invalidateDecorationElementsOfKindAtIndexPaths(int handle, string elementKind, array indexPaths) -> void
    {
        nscollectionviewlayoutinvalidationcontext_invalidate_decoration_elements_of_kind_at_index_paths(handle, elementKind, indexPaths);
    }

    public static function invalidatedItemIndexPaths(int handle) -> array
    {
        var result;

        let result = nscollectionviewlayoutinvalidationcontext_invalidated_item_index_paths(handle);

        return result;
    }

    public static function invalidatedSupplementaryIndexPaths(int handle) -> int
    {
        return nscollectionviewlayoutinvalidationcontext_invalidated_supplementary_index_paths(handle);
    }

    public static function invalidatedDecorationIndexPaths(int handle) -> int
    {
        return nscollectionviewlayoutinvalidationcontext_invalidated_decoration_index_paths(handle);
    }

    public static function contentOffsetAdjustment(int handle) -> array
    {
        var result;

        let result = nscollectionviewlayoutinvalidationcontext_content_offset_adjustment(handle);

        return result;
    }

    public static function setContentOffsetAdjustment(int handle, double x, double y) -> void
    {
        nscollectionviewlayoutinvalidationcontext_set_content_offset_adjustment(handle, x, y);
    }

    public static function contentSizeAdjustment(int handle) -> array
    {
        var result;

        let result = nscollectionviewlayoutinvalidationcontext_content_size_adjustment(handle);

        return result;
    }

    public static function setContentSizeAdjustment(int handle, double width, double height) -> void
    {
        nscollectionviewlayoutinvalidationcontext_set_content_size_adjustment(handle, width, height);
    }
}
