// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSOpenGLContext;

class NSOpenGLContext
{
    public static function initWithFormatShareContext(int format, int share) -> int
    {
        return nsopenglcontext_init_with_format_share_context(format, share);
    }

    public static function initWithCGLContextObj(int context) -> int
    {
        return nsopenglcontext_init_with_cgl_context_obj(context);
    }

    public static function pixelFormat(int handle) -> int
    {
        return nsopenglcontext_pixel_format(handle);
    }

    public static function view(int handle) -> int
    {
        return nsopenglcontext_view(handle);
    }

    public static function setView(int handle, int view) -> void
    {
        nsopenglcontext_set_view(handle, view);
    }

    public static function setFullScreen(int handle) -> void
    {
        nsopenglcontext_set_full_screen(handle);
    }

    public static function setOffScreenWidthHeightRowbytes(int handle, int baseaddr, int width, int height, int rowbytes) -> void
    {
        nsopenglcontext_set_off_screen_width_height_rowbytes(handle, baseaddr, width, height, rowbytes);
    }

    public static function clearDrawable(int handle) -> void
    {
        nsopenglcontext_clear_drawable(handle);
    }

    public static function update(int handle) -> void
    {
        nsopenglcontext_update(handle);
    }

    public static function flushBuffer(int handle) -> void
    {
        nsopenglcontext_flush_buffer(handle);
    }

    public static function makeCurrentContext(int handle) -> void
    {
        nsopenglcontext_make_current_context(handle);
    }

    public static function clearCurrentContext() -> void
    {
        nsopenglcontext_clear_current_context();
    }

    public static function currentContext() -> int
    {
        return nsopenglcontext_current_context();
    }

    public static function copyAttributesFromContextWithMask(int handle, int context, int mask) -> void
    {
        nsopenglcontext_copy_attributes_from_context_with_mask(handle, context, mask);
    }

    public static function setValuesForParameter(int handle, array vals, int param) -> void
    {
        nsopenglcontext_set_values_for_parameter(handle, vals, param);
    }

    public static function getValuesForParameter(int handle, int param) -> array
    {
        var result;

        let result = nsopenglcontext_get_values_for_parameter(handle, param);

        return result;
    }

    public static function currentVirtualScreen(int handle) -> int
    {
        return nsopenglcontext_current_virtual_screen(handle);
    }

    public static function setCurrentVirtualScreen(int handle, int currentVirtualScreen) -> void
    {
        nsopenglcontext_set_current_virtual_screen(handle, currentVirtualScreen);
    }

    public static function createTextureFromViewInternalFormat(int handle, int target, int view, int format) -> void
    {
        nsopenglcontext_create_texture_from_view_internal_format(handle, target, view, format);
    }

    public static function CGLContextObj(int handle) -> int
    {
        return nsopenglcontext_cgl_context_obj(handle);
    }

    public static function setPixelBufferCubeMapFaceMipMapLevelCurrentVirtualScreen(int handle, int pixelBuffer, int face, int level, int screen) -> void
    {
        nsopenglcontext_set_pixel_buffer_cube_map_face_mip_map_level_current_virtual_screen(handle, pixelBuffer, face, level, screen);
    }

    public static function pixelBuffer(int handle) -> int
    {
        return nsopenglcontext_pixel_buffer(handle);
    }

    public static function pixelBufferCubeMapFace(int handle) -> int
    {
        return nsopenglcontext_pixel_buffer_cube_map_face(handle);
    }

    public static function pixelBufferMipMapLevel(int handle) -> int
    {
        return nsopenglcontext_pixel_buffer_mip_map_level(handle);
    }

    public static function setTextureImageToPixelBufferColorBuffer(int handle, int pixelBuffer, int source) -> void
    {
        nsopenglcontext_set_texture_image_to_pixel_buffer_color_buffer(handle, pixelBuffer, source);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (void)setView:(nullable NSView *)view NS_SWIFT_UI_ACTOR API_DEPRECATED("Use NSOpenGLView to provide OpenGL content in a Cocoa app.", macos(10.0,10.14)); — second declaration of the `view` property's setter; bound once as that setter

}
