// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSColor;

class NSColor
{
    public static function init() -> int
    {
        return nscolor_init();
    }

    public static function colorWithSRGBRedGreenBlueAlpha(double red, double green, double blue, double alpha) -> int
    {
        return nscolor_color_with_srgb_red_green_blue_alpha(red, green, blue, alpha);
    }

    public static function colorWithGenericGamma22WhiteAlpha(double white, double alpha) -> int
    {
        return nscolor_color_with_generic_gamma22_white_alpha(white, alpha);
    }

    public static function colorWithDisplayP3RedGreenBlueAlpha(double red, double green, double blue, double alpha) -> int
    {
        return nscolor_color_with_display_p3_red_green_blue_alpha(red, green, blue, alpha);
    }

    public static function colorWithWhiteAlpha(double white, double alpha) -> int
    {
        return nscolor_color_with_white_alpha(white, alpha);
    }

    public static function colorWithRedGreenBlueAlpha(double red, double green, double blue, double alpha) -> int
    {
        return nscolor_color_with_red_green_blue_alpha(red, green, blue, alpha);
    }

    public static function colorWithHueSaturationBrightnessAlpha(double hue, double saturation, double brightness, double alpha) -> int
    {
        return nscolor_color_with_hue_saturation_brightness_alpha(hue, saturation, brightness, alpha);
    }

    public static function colorWithColorSpaceHueSaturationBrightnessAlpha(int space, double hue, double saturation, double brightness, double alpha) -> int
    {
        return nscolor_color_with_color_space_hue_saturation_brightness_alpha(space, hue, saturation, brightness, alpha);
    }

    public static function colorWithCatalogNameColorName(string listName, string colorName) -> int
    {
        return nscolor_color_with_catalog_name_color_name(listName, colorName);
    }

    public static function colorNamedBundle(string name, int bundle) -> int
    {
        return nscolor_color_named_bundle(name, bundle);
    }

    public static function colorNamed(string name) -> int
    {
        return nscolor_color_named(name);
    }

    public static function colorWithDeviceWhiteAlpha(double white, double alpha) -> int
    {
        return nscolor_color_with_device_white_alpha(white, alpha);
    }

    public static function colorWithDeviceRedGreenBlueAlpha(double red, double green, double blue, double alpha) -> int
    {
        return nscolor_color_with_device_red_green_blue_alpha(red, green, blue, alpha);
    }

    public static function colorWithDeviceHueSaturationBrightnessAlpha(double hue, double saturation, double brightness, double alpha) -> int
    {
        return nscolor_color_with_device_hue_saturation_brightness_alpha(hue, saturation, brightness, alpha);
    }

    public static function colorWithDeviceCyanMagentaYellowBlackAlpha(double cyan, double magenta, double yellow, double black, double alpha) -> int
    {
        return nscolor_color_with_device_cyan_magenta_yellow_black_alpha(cyan, magenta, yellow, black, alpha);
    }

    public static function colorWithCalibratedWhiteAlpha(double white, double alpha) -> int
    {
        return nscolor_color_with_calibrated_white_alpha(white, alpha);
    }

    public static function colorWithCalibratedRedGreenBlueAlpha(double red, double green, double blue, double alpha) -> int
    {
        return nscolor_color_with_calibrated_red_green_blue_alpha(red, green, blue, alpha);
    }

    public static function colorWithCalibratedHueSaturationBrightnessAlpha(double hue, double saturation, double brightness, double alpha) -> int
    {
        return nscolor_color_with_calibrated_hue_saturation_brightness_alpha(hue, saturation, brightness, alpha);
    }

    public static function colorWithPatternImage(int image) -> int
    {
        return nscolor_color_with_pattern_image(image);
    }

    public static function type(int handle) -> int
    {
        return nscolor_type(handle);
    }

    public static function colorUsingType(int handle, int type) -> int
    {
        return nscolor_color_using_type(handle, type);
    }

    public static function colorUsingColorSpace(int handle, int space) -> int
    {
        return nscolor_color_using_color_space(handle, space);
    }

    public static function blackColor() -> int
    {
        return nscolor_black_color();
    }

    public static function darkGrayColor() -> int
    {
        return nscolor_dark_gray_color();
    }

    public static function lightGrayColor() -> int
    {
        return nscolor_light_gray_color();
    }

    public static function whiteColor() -> int
    {
        return nscolor_white_color();
    }

    public static function grayColor() -> int
    {
        return nscolor_gray_color();
    }

    public static function redColor() -> int
    {
        return nscolor_red_color();
    }

    public static function greenColor() -> int
    {
        return nscolor_green_color();
    }

    public static function blueColor() -> int
    {
        return nscolor_blue_color();
    }

    public static function cyanColor() -> int
    {
        return nscolor_cyan_color();
    }

    public static function yellowColor() -> int
    {
        return nscolor_yellow_color();
    }

    public static function magentaColor() -> int
    {
        return nscolor_magenta_color();
    }

    public static function orangeColor() -> int
    {
        return nscolor_orange_color();
    }

    public static function purpleColor() -> int
    {
        return nscolor_purple_color();
    }

    public static function brownColor() -> int
    {
        return nscolor_brown_color();
    }

    public static function clearColor() -> int
    {
        return nscolor_clear_color();
    }

    public static function labelColor() -> int
    {
        return nscolor_label_color();
    }

    public static function secondaryLabelColor() -> int
    {
        return nscolor_secondary_label_color();
    }

    public static function tertiaryLabelColor() -> int
    {
        return nscolor_tertiary_label_color();
    }

    public static function quaternaryLabelColor() -> int
    {
        return nscolor_quaternary_label_color();
    }

    public static function quinaryLabelColor() -> int
    {
        return nscolor_quinary_label_color();
    }

    public static function linkColor() -> int
    {
        return nscolor_link_color();
    }

    public static function placeholderTextColor() -> int
    {
        return nscolor_placeholder_text_color();
    }

    public static function windowFrameTextColor() -> int
    {
        return nscolor_window_frame_text_color();
    }

    public static function selectedMenuItemTextColor() -> int
    {
        return nscolor_selected_menu_item_text_color();
    }

    public static function alternateSelectedControlTextColor() -> int
    {
        return nscolor_alternate_selected_control_text_color();
    }

    public static function headerTextColor() -> int
    {
        return nscolor_header_text_color();
    }

    public static function separatorColor() -> int
    {
        return nscolor_separator_color();
    }

    public static function gridColor() -> int
    {
        return nscolor_grid_color();
    }

    public static function windowBackgroundColor() -> int
    {
        return nscolor_window_background_color();
    }

    public static function underPageBackgroundColor() -> int
    {
        return nscolor_under_page_background_color();
    }

    public static function controlBackgroundColor() -> int
    {
        return nscolor_control_background_color();
    }

    public static function selectedContentBackgroundColor() -> int
    {
        return nscolor_selected_content_background_color();
    }

    public static function unemphasizedSelectedContentBackgroundColor() -> int
    {
        return nscolor_unemphasized_selected_content_background_color();
    }

    public static function alternatingContentBackgroundColors() -> array
    {
        var result;

        let result = nscolor_alternating_content_background_colors();

        return result;
    }

    public static function findHighlightColor() -> int
    {
        return nscolor_find_highlight_color();
    }

    public static function textColor() -> int
    {
        return nscolor_text_color();
    }

    public static function textBackgroundColor() -> int
    {
        return nscolor_text_background_color();
    }

    public static function textInsertionPointColor() -> int
    {
        return nscolor_text_insertion_point_color();
    }

    public static function selectedTextColor() -> int
    {
        return nscolor_selected_text_color();
    }

    public static function selectedTextBackgroundColor() -> int
    {
        return nscolor_selected_text_background_color();
    }

    public static function unemphasizedSelectedTextBackgroundColor() -> int
    {
        return nscolor_unemphasized_selected_text_background_color();
    }

    public static function unemphasizedSelectedTextColor() -> int
    {
        return nscolor_unemphasized_selected_text_color();
    }

    public static function controlColor() -> int
    {
        return nscolor_control_color();
    }

    public static function controlTextColor() -> int
    {
        return nscolor_control_text_color();
    }

    public static function selectedControlColor() -> int
    {
        return nscolor_selected_control_color();
    }

    public static function selectedControlTextColor() -> int
    {
        return nscolor_selected_control_text_color();
    }

    public static function disabledControlTextColor() -> int
    {
        return nscolor_disabled_control_text_color();
    }

    public static function keyboardFocusIndicatorColor() -> int
    {
        return nscolor_keyboard_focus_indicator_color();
    }

    public static function scrubberTexturedBackgroundColor() -> int
    {
        return nscolor_scrubber_textured_background_color();
    }

    public static function systemRedColor() -> int
    {
        return nscolor_system_red_color();
    }

    public static function systemGreenColor() -> int
    {
        return nscolor_system_green_color();
    }

    public static function systemBlueColor() -> int
    {
        return nscolor_system_blue_color();
    }

    public static function systemOrangeColor() -> int
    {
        return nscolor_system_orange_color();
    }

    public static function systemYellowColor() -> int
    {
        return nscolor_system_yellow_color();
    }

    public static function systemBrownColor() -> int
    {
        return nscolor_system_brown_color();
    }

    public static function systemPinkColor() -> int
    {
        return nscolor_system_pink_color();
    }

    public static function systemPurpleColor() -> int
    {
        return nscolor_system_purple_color();
    }

    public static function systemGrayColor() -> int
    {
        return nscolor_system_gray_color();
    }

    public static function systemTealColor() -> int
    {
        return nscolor_system_teal_color();
    }

    public static function systemIndigoColor() -> int
    {
        return nscolor_system_indigo_color();
    }

    public static function systemMintColor() -> int
    {
        return nscolor_system_mint_color();
    }

    public static function systemCyanColor() -> int
    {
        return nscolor_system_cyan_color();
    }

    public static function systemFillColor() -> int
    {
        return nscolor_system_fill_color();
    }

    public static function secondarySystemFillColor() -> int
    {
        return nscolor_secondary_system_fill_color();
    }

    public static function tertiarySystemFillColor() -> int
    {
        return nscolor_tertiary_system_fill_color();
    }

    public static function quaternarySystemFillColor() -> int
    {
        return nscolor_quaternary_system_fill_color();
    }

    public static function quinarySystemFillColor() -> int
    {
        return nscolor_quinary_system_fill_color();
    }

    public static function controlAccentColor() -> int
    {
        return nscolor_control_accent_color();
    }

    public static function currentControlTint() -> int
    {
        return nscolor_current_control_tint();
    }

    public static function highlightColor() -> int
    {
        return nscolor_highlight_color();
    }

    public static function shadowColor() -> int
    {
        return nscolor_shadow_color();
    }

    public static function highlightWithLevel(int handle, double val) -> int
    {
        return nscolor_highlight_with_level(handle, val);
    }

    public static function shadowWithLevel(int handle, double val) -> int
    {
        return nscolor_shadow_with_level(handle, val);
    }

    public static function colorWithSystemEffect(int handle, int systemEffect) -> int
    {
        return nscolor_color_with_system_effect(handle, systemEffect);
    }

    public static function set(int handle) -> void
    {
        nscolor_set(handle);
    }

    public static function setFill(int handle) -> void
    {
        nscolor_set_fill(handle);
    }

    public static function setStroke(int handle) -> void
    {
        nscolor_set_stroke(handle);
    }

    public static function blendedColorWithFractionOfColor(int handle, double fraction, int color) -> int
    {
        return nscolor_blended_color_with_fraction_of_color(handle, fraction, color);
    }

    public static function colorWithAlphaComponent(int handle, double alpha) -> int
    {
        return nscolor_color_with_alpha_component(handle, alpha);
    }

    public static function catalogNameComponent(int handle) -> string
    {
        var result;

        let result = nscolor_catalog_name_component(handle);

        return result;
    }

    public static function colorNameComponent(int handle) -> string
    {
        var result;

        let result = nscolor_color_name_component(handle);

        return result;
    }

    public static function localizedCatalogNameComponent(int handle) -> string
    {
        var result;

        let result = nscolor_localized_catalog_name_component(handle);

        return result;
    }

    public static function localizedColorNameComponent(int handle) -> string
    {
        var result;

        let result = nscolor_localized_color_name_component(handle);

        return result;
    }

    public static function redComponent(int handle) -> double
    {
        return nscolor_red_component(handle);
    }

    public static function greenComponent(int handle) -> double
    {
        return nscolor_green_component(handle);
    }

    public static function blueComponent(int handle) -> double
    {
        return nscolor_blue_component(handle);
    }

    public static function getRedGreenBlueAlpha(int handle) -> array
    {
        var result;

        let result = nscolor_get_red_green_blue_alpha(handle);

        return result;
    }

    public static function hueComponent(int handle) -> double
    {
        return nscolor_hue_component(handle);
    }

    public static function saturationComponent(int handle) -> double
    {
        return nscolor_saturation_component(handle);
    }

    public static function brightnessComponent(int handle) -> double
    {
        return nscolor_brightness_component(handle);
    }

    public static function getHueSaturationBrightnessAlpha(int handle) -> array
    {
        var result;

        let result = nscolor_get_hue_saturation_brightness_alpha(handle);

        return result;
    }

    public static function whiteComponent(int handle) -> double
    {
        return nscolor_white_component(handle);
    }

    public static function getWhiteAlpha(int handle) -> array
    {
        var result;

        let result = nscolor_get_white_alpha(handle);

        return result;
    }

    public static function cyanComponent(int handle) -> double
    {
        return nscolor_cyan_component(handle);
    }

    public static function magentaComponent(int handle) -> double
    {
        return nscolor_magenta_component(handle);
    }

    public static function yellowComponent(int handle) -> double
    {
        return nscolor_yellow_component(handle);
    }

    public static function blackComponent(int handle) -> double
    {
        return nscolor_black_component(handle);
    }

    public static function getCyanMagentaYellowBlackAlpha(int handle) -> array
    {
        var result;

        let result = nscolor_get_cyan_magenta_yellow_black_alpha(handle);

        return result;
    }

    public static function colorSpace(int handle) -> int
    {
        return nscolor_color_space(handle);
    }

    public static function numberOfComponents(int handle) -> int
    {
        return nscolor_number_of_components(handle);
    }

    public static function patternImage(int handle) -> int
    {
        return nscolor_pattern_image(handle);
    }

    public static function alphaComponent(int handle) -> double
    {
        return nscolor_alpha_component(handle);
    }

    public static function colorFromPasteboard(int pasteBoard) -> int
    {
        return nscolor_color_from_pasteboard(pasteBoard);
    }

    public static function writeToPasteboard(int handle, int pasteBoard) -> void
    {
        nscolor_write_to_pasteboard(handle, pasteBoard);
    }

    public static function drawSwatchInRect(int handle, double x, double y, double width, double height) -> void
    {
        nscolor_draw_swatch_in_rect(handle, x, y, width, height);
    }

    public static function colorWithCGColor(int cgColor) -> int
    {
        return nscolor_color_with_cg_color(cgColor);
    }

    public static function colorWithCIColor(int color) -> int
    {
        return nscolor_color_with_ci_color(color);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (nullable instancetype)initWithCoder:(NSCoder *)coder — NSCoder
    // @reserved + (NSColor *)colorWithColorSpace:(NSColorSpace *)space components:(const CGFloat *)components count:(NSInteger)numberOfComponents — C component buffer
    // @reserved + (NSColor *)colorWithName:(nullable NSColorName)colorName dynamicProvider:(NSColor * (^)(NSAppearance *))dynamicProvider — block
    // @reserved + (NSColor *)colorForControlTint:(NSControlTint)controlTint — API_DEPRECATED
    // @reserved - (void)getComponents:(CGFloat *)components — C component buffer
    // @reserved @property (readonly) CGColorRef CGColor NS_RETURNS_INNER_POINTER — CGColorRef inner pointer
    // @reserved @property (class) BOOL ignoresAlpha — getter API_DEPRECATED
    // @reserved @property (class) BOOL ignoresAlpha — setter API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *controlHighlightColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *controlLightHighlightColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *controlShadowColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *controlDarkShadowColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *scrollBarColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *knobColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *selectedKnobColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *windowFrameColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *selectedMenuItemColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *headerColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *secondarySelectedControlColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *alternateSelectedControlColor — API_DEPRECATED
    // @reserved @property (class, strong, readonly) NSColor *controlAlternatingRowBackgroundColors — API_DEPRECATED
    // @reserved @property (readonly, copy) NSColorSpaceName colorSpaceName — API_DEPRECATED
    // @reserved - (nullable NSColor *)colorUsingColorSpaceName:(nullable NSColorSpaceName)name device:(nullable NSDictionary *)deviceDescription — API_DEPRECATED
    // @reserved - (nullable NSColor *)colorUsingColorSpaceName:(NSColorSpaceName)name — API_DEPRECATED

}
