
extern zend_class_entry *appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult);

PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, createWithTargetElement);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, createWithToken);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, wrap);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, destroy);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, nsAccessibilityCustomRotorItem);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, customLabel);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, setCustomLabel);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, setTargetRange);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, targetRange);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_createwithtargetelement, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, element, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_createwithtoken, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, token, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, label, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_customlabel, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_setcustomlabel, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, label, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_settargetrange, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_targetrange, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_method_entry) {
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, createWithTargetElement, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_createwithtargetelement, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, createWithToken, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_createwithtoken, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, wrap, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, destroy, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, nsAccessibilityCustomRotorItem, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, customLabel, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_customlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, setCustomLabel, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_setcustomlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, setTargetRange, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_settargetrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItemResult_NSAccessibilityCustomRotorItemResult, targetRange, arginfo_appkit_ns_nsaccessibilitycustomrotoritemresult_nsaccessibilitycustomrotoritemresult_targetrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
