
extern zend_class_entry *appkit_ns_nspickertouchbaritem_nspickertouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem);

PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, pickerWithLabels);
PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, nsPickerTouchBarItem);
PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, setSelectedIndex);
PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, getSelectedIndex);
PHP_METHOD(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, pollAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_pickerwithlabels, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_ARRAY_INFO(0, labels, 0)
	ZEND_ARG_TYPE_INFO(0, selectionMode, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_nspickertouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_setselectedindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_getselectedindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_pollaction, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nspickertouchbaritem_nspickertouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, pickerWithLabels, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_pickerwithlabels, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, wrap, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, destroy, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, nsPickerTouchBarItem, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_nspickertouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, setSelectedIndex, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_setselectedindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, getSelectedIndex, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_getselectedindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPickerTouchBarItem_NSPickerTouchBarItem, pollAction, arginfo_appkit_ns_nspickertouchbaritem_nspickertouchbaritem_pollaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
