// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSTableCellView;

class NSTableCellView
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nstablecellview_init_with_frame(x, y, width, height);
    }

    public static function objectValue(int handle) -> int
    {
        return nstablecellview_object_value(handle);
    }

    public static function setObjectValue(int handle, int objectValue) -> void
    {
        nstablecellview_set_object_value(handle, objectValue);
    }

    public static function textField(int handle) -> int
    {
        return nstablecellview_text_field(handle);
    }

    public static function setTextField(int handle, int textField) -> void
    {
        nstablecellview_set_text_field(handle, textField);
    }

    public static function imageView(int handle) -> int
    {
        return nstablecellview_image_view(handle);
    }

    public static function setImageView(int handle, int imageView) -> void
    {
        nstablecellview_set_image_view(handle, imageView);
    }

    public static function backgroundStyle(int handle) -> int
    {
        return nstablecellview_background_style(handle);
    }

    public static function setBackgroundStyle(int handle, int backgroundStyle) -> void
    {
        nstablecellview_set_background_style(handle, backgroundStyle);
    }

    public static function rowSizeStyle(int handle) -> int
    {
        return nstablecellview_row_size_style(handle);
    }

    public static function setRowSizeStyle(int handle, int rowSizeStyle) -> void
    {
        nstablecellview_set_row_size_style(handle, rowSizeStyle);
    }

    public static function draggingImageComponents(int handle) -> array
    {
        var result;

        let result = nstablecellview_dragging_image_components(handle);

        return result;
    }
}
