
extern zend_class_entry *appkit_ns_nspersistentdocument_nspersistentdocument_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSPersistentDocument_NSPersistentDocument);

PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, create);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, wrap);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, destroy);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, nsPersistentDocument);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, managedObjectContext);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, managedObjectModel);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, persistentStoreTypeForFileType);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, readFromURL);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, writeToURL);
PHP_METHOD(AppKit_NS_NSPersistentDocument_NSPersistentDocument, revertToContentsOfURL);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsPersistentDocumentPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_nspersistentdocument, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_managedobjectcontext, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_managedobjectmodel, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_persistentstoretypeforfiletype, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, fileType, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_readfromurl, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, url, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, typeName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_writetourl, 0, 4, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, url, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, typeName, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, saveOperation, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, originalURL, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_reverttocontentsofurl, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, url, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, typeName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nspersistentdocument_nspersistentdocument_method_entry) {
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, create, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, wrap, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, destroy, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, nsPersistentDocument, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_nspersistentdocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, managedObjectContext, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_managedobjectcontext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, managedObjectModel, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_managedobjectmodel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, persistentStoreTypeForFileType, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_persistentstoretypeforfiletype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, readFromURL, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_readfromurl, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, writeToURL, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_writetourl, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPersistentDocument_NSPersistentDocument, revertToContentsOfURL, arginfo_appkit_ns_nspersistentdocument_nspersistentdocument_reverttocontentsofurl, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
