
extern zend_class_entry *appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem);

PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, create);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, nsCustomTouchBarItem);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, setView);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, getView);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, setCustomizationLabel);
PHP_METHOD(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, getCustomizationLabel);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_nscustomtouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_setview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_getview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_setcustomizationlabel, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, label, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_getcustomizationlabel, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, create, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, wrap, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, destroy, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, nsCustomTouchBarItem, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_nscustomtouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, setView, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_setview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, getView, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_getview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, setCustomizationLabel, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_setcustomizationlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCustomTouchBarItem_NSCustomTouchBarItem, getCustomizationLabel, arginfo_appkit_ns_nscustomtouchbaritem_nscustomtouchbaritem_getcustomizationlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
