
extern zend_class_entry *appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem);

PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, create);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, nsCandidateListTouchBarItem);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, setCollapsed);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, isCollapsed);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, setCandidates);
PHP_METHOD(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, getCandidates);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_setcollapsed, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_iscollapsed, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_setcandidates, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, candidates, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_getcandidates, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, create, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, wrap, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, destroy, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, nsCandidateListTouchBarItem, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, setCollapsed, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_setcollapsed, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, isCollapsed, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_iscollapsed, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, setCandidates, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_setcandidates, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCandidateListTouchBarItem_NSCandidateListTouchBarItem, getCandidates, arginfo_appkit_ns_nscandidatelisttouchbaritem_nscandidatelisttouchbaritem_getcandidates, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
