
extern zend_class_entry *appkit_ns_nspressureconfiguration_nspressureconfiguration_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration);

PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, create);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, wrap);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, destroy);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, nsPressureConfiguration);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, pressureBehavior);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, set);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, setOnView);
PHP_METHOD(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, viewConfiguration);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pressureBehavior, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsPressureConfigurationPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, configuration, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_nspressureconfiguration, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, configuration, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_pressurebehavior, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, configuration, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_set, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, configuration, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_setonview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, configuration, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_viewconfiguration, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nspressureconfiguration_nspressureconfiguration_method_entry) {
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, create, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, wrap, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, destroy, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, nsPressureConfiguration, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_nspressureconfiguration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, pressureBehavior, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_pressurebehavior, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, set, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_set, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, setOnView, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_setonview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressureConfiguration_NSPressureConfiguration, viewConfiguration, arginfo_appkit_ns_nspressureconfiguration_nspressureconfiguration_viewconfiguration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
