
extern zend_class_entry *appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController);

PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, create);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, createWithView);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, wrap);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, destroy);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, nsTitlebarAccessoryViewController);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setView);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, view);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setLayoutAttribute);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, layoutAttribute);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setFullScreenMinHeight);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, fullScreenMinHeight);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setHidden);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, isHidden);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setAutomaticallyAdjustsSize);
PHP_METHOD(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, automaticallyAdjustsSize);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_createwithview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTitlebarAccessoryViewControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_view, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setlayoutattribute, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attribute, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_layoutattribute, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setfullscreenminheight, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_fullscreenminheight, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_sethidden, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, hidden, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_ishidden, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setautomaticallyadjustssize, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, adjusts, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_automaticallyadjustssize, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_method_entry) {
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, create, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, createWithView, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_createwithview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, wrap, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, destroy, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, nsTitlebarAccessoryViewController, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setView, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, view, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_view, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setLayoutAttribute, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setlayoutattribute, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, layoutAttribute, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_layoutattribute, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setFullScreenMinHeight, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setfullscreenminheight, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, fullScreenMinHeight, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_fullscreenminheight, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setHidden, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_sethidden, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, isHidden, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_ishidden, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, setAutomaticallyAdjustsSize, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_setautomaticallyadjustssize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTitlebarAccessoryViewController_NSTitlebarAccessoryViewController, automaticallyAdjustsSize, arginfo_appkit_ns_nstitlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller_automaticallyadjustssize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
