
extern zend_class_entry *appkit_ns_nslevelindicatorcell_nslevelindicatorcell_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell);

PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, createText);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, wrap);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, destroy);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, nsLevelIndicatorCell);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setTitle);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getTitle);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setState);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getState);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setEnabled);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, isEnabled);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setTag);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getTag);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setLevelIndicatorStyle);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getLevelIndicatorStyle);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setEditable);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, isEditable);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setMinValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getMinValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setMaxValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getMaxValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setWarningValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getWarningValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setCriticalValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getCriticalValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setDoubleValue);
PHP_METHOD(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getDoubleValue);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_createtext, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsLevelIndicatorCellPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_nslevelindicatorcell, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_settitle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_gettitle, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setstate, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, state, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getstate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, enabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_isenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_settag, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, tag, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_gettag, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setlevelindicatorstyle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, style, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getlevelindicatorstyle, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_seteditable, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_iseditable, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setminvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getminvalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setmaxvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getmaxvalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setwarningvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getwarningvalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setcriticalvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getcriticalvalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setdoublevalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getdoublevalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nslevelindicatorcell_nslevelindicatorcell_method_entry) {
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, createText, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_createtext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, wrap, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, destroy, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, nsLevelIndicatorCell, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_nslevelindicatorcell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setTitle, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_settitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getTitle, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_gettitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setState, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getState, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setEnabled, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, isEnabled, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_isenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setTag, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_settag, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getTag, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_gettag, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setLevelIndicatorStyle, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setlevelindicatorstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getLevelIndicatorStyle, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getlevelindicatorstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setEditable, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_seteditable, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, isEditable, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_iseditable, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setMinValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setminvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getMinValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getminvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setMaxValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setmaxvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getMaxValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getmaxvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setWarningValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setwarningvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getWarningValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getwarningvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setCriticalValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setcriticalvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getCriticalValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getcriticalvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, setDoubleValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_setdoublevalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell, getDoubleValue, arginfo_appkit_ns_nslevelindicatorcell_nslevelindicatorcell_getdoublevalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
