
extern zend_class_entry *appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer);

PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, create);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, wrap);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, destroy);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, nsSpeechSynthesizer);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, startSpeakingString);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, startSpeakingStringToURL);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, isSpeaking);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, stopSpeaking);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, stopSpeakingAtBoundary);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, pauseSpeakingAtBoundary);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, continueSpeaking);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, voice);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setVoice);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, rate);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setRate);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, volume);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setVolume);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, usesFeedbackWindow);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setUsesFeedbackWindow);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, phonemesFromText);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, isAnyApplicationSpeaking);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, defaultVoice);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, availableVoicesCount);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, availableVoiceAt);
PHP_METHOD(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, attributeForVoice);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_create, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, voice, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsSpeechSynthesizerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_nsspeechsynthesizer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_startspeakingstring, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_startspeakingstringtourl, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, url, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_isspeaking, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_stopspeaking, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_stopspeakingatboundary, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, boundary, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_pausespeakingatboundary, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, boundary, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_continuespeaking, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_voice, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setvoice, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, voice, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_rate, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setrate, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rate, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_volume, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setvolume, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, volume, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_usesfeedbackwindow, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setusesfeedbackwindow, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_phonemesfromtext, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, synthesizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_isanyapplicationspeaking, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_defaultvoice, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_availablevoicescount, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_availablevoiceat, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_attributeforvoice, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, voice, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, key, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_method_entry) {
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, create, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, wrap, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, destroy, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, nsSpeechSynthesizer, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_nsspeechsynthesizer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, startSpeakingString, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_startspeakingstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, startSpeakingStringToURL, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_startspeakingstringtourl, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, isSpeaking, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_isspeaking, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, stopSpeaking, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_stopspeaking, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, stopSpeakingAtBoundary, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_stopspeakingatboundary, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, pauseSpeakingAtBoundary, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_pausespeakingatboundary, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, continueSpeaking, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_continuespeaking, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, voice, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_voice, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setVoice, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setvoice, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, rate, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_rate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setRate, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setrate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, volume, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_volume, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setVolume, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setvolume, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, usesFeedbackWindow, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_usesfeedbackwindow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, setUsesFeedbackWindow, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_setusesfeedbackwindow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, phonemesFromText, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_phonemesfromtext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, isAnyApplicationSpeaking, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_isanyapplicationspeaking, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, defaultVoice, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_defaultvoice, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, availableVoicesCount, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_availablevoicescount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, availableVoiceAt, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_availablevoiceat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechSynthesizer_NSSpeechSynthesizer, attributeForVoice, arginfo_appkit_ns_nsspeechsynthesizer_nsspeechsynthesizer_attributeforvoice, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
