
extern zend_class_entry *appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer);

PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, create);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, destroy);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, setEnabled);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, isEnabled);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, state);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, addToView);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, removeFromView);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, locationInView);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, magnification);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, setMagnification);
PHP_METHOD(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, nsMagnificationGestureRecognizer);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_setenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, enabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_isenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_state, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_addtoview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_removefromview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_locationinview, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_magnification, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_setmagnification, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_method_entry) {
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, create, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, destroy, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, setEnabled, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_setenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, isEnabled, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_isenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, state, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_state, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, addToView, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_addtoview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, removeFromView, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_removefromview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, locationInView, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_locationinview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, magnification, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_magnification, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, setMagnification, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_setmagnification, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer, nsMagnificationGestureRecognizer, arginfo_appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
