// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSegmentedCell;

class NSSegmentedCell
{
    public static function initTextCell(string string_) -> int
    {
        return nssegmentedcell_init_text_cell(string_);
    }

    public static function initImageCell(int image) -> int
    {
        return nssegmentedcell_init_image_cell(image);
    }

    public static function segmentCount(int handle) -> int
    {
        return nssegmentedcell_segment_count(handle);
    }

    public static function setSegmentCount(int handle, int segmentCount) -> void
    {
        nssegmentedcell_set_segment_count(handle, segmentCount);
    }

    public static function selectedSegment(int handle) -> int
    {
        return nssegmentedcell_selected_segment(handle);
    }

    public static function setSelectedSegment(int handle, int selectedSegment) -> void
    {
        nssegmentedcell_set_selected_segment(handle, selectedSegment);
    }

    public static function selectSegmentWithTag(int handle, int tag) -> bool
    {
        int r;

        let r = nssegmentedcell_select_segment_with_tag(handle, tag);

        return r == 1;
    }

    public static function makeNextSegmentKey(int handle) -> void
    {
        nssegmentedcell_make_next_segment_key(handle);
    }

    public static function makePreviousSegmentKey(int handle) -> void
    {
        nssegmentedcell_make_previous_segment_key(handle);
    }

    public static function trackingMode(int handle) -> int
    {
        return nssegmentedcell_tracking_mode(handle);
    }

    public static function setTrackingMode(int handle, int trackingMode) -> void
    {
        nssegmentedcell_set_tracking_mode(handle, trackingMode);
    }

    public static function setWidthForSegment(int handle, double width, int segment) -> void
    {
        nssegmentedcell_set_width_for_segment(handle, width, segment);
    }

    public static function widthForSegment(int handle, int segment) -> double
    {
        return nssegmentedcell_width_for_segment(handle, segment);
    }

    public static function setImageForSegment(int handle, int image, int segment) -> void
    {
        nssegmentedcell_set_image_for_segment(handle, image, segment);
    }

    public static function imageForSegment(int handle, int segment) -> int
    {
        return nssegmentedcell_image_for_segment(handle, segment);
    }

    public static function setImageScalingForSegment(int handle, int scaling, int segment) -> void
    {
        nssegmentedcell_set_image_scaling_for_segment(handle, scaling, segment);
    }

    public static function imageScalingForSegment(int handle, int segment) -> int
    {
        return nssegmentedcell_image_scaling_for_segment(handle, segment);
    }

    public static function setLabelForSegment(int handle, string label, int segment) -> void
    {
        nssegmentedcell_set_label_for_segment(handle, label, segment);
    }

    public static function labelForSegment(int handle, int segment) -> var
    {
        var result;

        let result = nssegmentedcell_label_for_segment(handle, segment);

        return result;
    }

    public static function setSelectedForSegment(int handle, bool selected, int segment) -> void
    {
        nssegmentedcell_set_selected_for_segment(handle, selected, segment);
    }

    public static function isSelectedForSegment(int handle, int segment) -> bool
    {
        int r;

        let r = nssegmentedcell_is_selected_for_segment(handle, segment);

        return r == 1;
    }

    public static function setEnabledForSegment(int handle, bool enabled, int segment) -> void
    {
        nssegmentedcell_set_enabled_for_segment(handle, enabled, segment);
    }

    public static function isEnabledForSegment(int handle, int segment) -> bool
    {
        int r;

        let r = nssegmentedcell_is_enabled_for_segment(handle, segment);

        return r == 1;
    }

    public static function setMenuForSegment(int handle, int menu, int segment) -> void
    {
        nssegmentedcell_set_menu_for_segment(handle, menu, segment);
    }

    public static function menuForSegment(int handle, int segment) -> int
    {
        return nssegmentedcell_menu_for_segment(handle, segment);
    }

    public static function setToolTipForSegment(int handle, var toolTip, int segment) -> void
    {
        nssegmentedcell_set_tool_tip_for_segment(handle, toolTip, segment);
    }

    public static function toolTipForSegment(int handle, int segment) -> var
    {
        var result;

        let result = nssegmentedcell_tool_tip_for_segment(handle, segment);

        return result;
    }

    public static function setTagForSegment(int handle, int tag, int segment) -> void
    {
        nssegmentedcell_set_tag_for_segment(handle, tag, segment);
    }

    public static function tagForSegment(int handle, int segment) -> int
    {
        return nssegmentedcell_tag_for_segment(handle, segment);
    }

    public static function segmentStyle(int handle) -> int
    {
        return nssegmentedcell_segment_style(handle);
    }

    public static function setSegmentStyle(int handle, int segmentStyle) -> void
    {
        nssegmentedcell_set_segment_style(handle, segmentStyle);
    }

    public static function drawSegmentInFrameWithView(int handle, int segment, double x, double y, double width, double height, int controlView) -> void
    {
        nssegmentedcell_draw_segment_in_frame_with_view(handle, segment, x, y, width, height, controlView);
    }

    public static function interiorBackgroundStyleForSegment(int handle, int segment) -> int
    {
        return nssegmentedcell_interior_background_style_for_segment(handle, segment);
    }
}
