// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSGridCell;

class NSGridCell
{
    public static function init() -> int
    {
        return nsgridcell_init();
    }

    public static function contentView(int handle) -> int
    {
        return nsgridcell_content_view(handle);
    }

    public static function setContentView(int handle, int contentView) -> void
    {
        nsgridcell_set_content_view(handle, contentView);
    }

    public static function emptyContentView() -> int
    {
        return nsgridcell_empty_content_view();
    }

    public static function row(int handle) -> int
    {
        return nsgridcell_row(handle);
    }

    public static function column(int handle) -> int
    {
        return nsgridcell_column(handle);
    }

    public static function xPlacement(int handle) -> int
    {
        return nsgridcell_x_placement(handle);
    }

    public static function setXPlacement(int handle, int xPlacement) -> void
    {
        nsgridcell_set_x_placement(handle, xPlacement);
    }

    public static function yPlacement(int handle) -> int
    {
        return nsgridcell_y_placement(handle);
    }

    public static function setYPlacement(int handle, int yPlacement) -> void
    {
        nsgridcell_set_y_placement(handle, yPlacement);
    }

    public static function rowAlignment(int handle) -> int
    {
        return nsgridcell_row_alignment(handle);
    }

    public static function setRowAlignment(int handle, int rowAlignment) -> void
    {
        nsgridcell_set_row_alignment(handle, rowAlignment);
    }

    public static function customPlacementConstraints(int handle) -> array
    {
        var result;

        let result = nsgridcell_custom_placement_constraints(handle);

        return result;
    }

    public static function setCustomPlacementConstraints(int handle, array constraints) -> void
    {
        nsgridcell_set_custom_placement_constraints(handle, constraints);
    }
}
