
extern zend_class_entry *appkit_ns_nssearchfieldcell_nssearchfieldcell_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell);

PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, createText);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, wrap);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, destroy);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, nsSearchFieldCell);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setTitle);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getTitle);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setStringValue);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getStringValue);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setPlaceholderString);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getPlaceholderString);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setRecentSearches);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getRecentSearches);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setRecentsAutosaveName);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getRecentsAutosaveName);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setSendsWholeSearchString);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, sendsWholeSearchString);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setMaximumRecents);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, maximumRecents);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setSendsSearchStringImmediately);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, sendsSearchStringImmediately);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, searchButtonCell);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, cancelButtonCell);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, resetSearchButtonCell);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, resetCancelButtonCell);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setSearchMenuTemplate);
PHP_METHOD(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, searchMenuTemplate);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_createtext, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsSearchFieldCellPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_nssearchfieldcell, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_settitle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_gettitle, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setstringvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getstringvalue, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setplaceholderstring, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, placeholder, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getplaceholderstring, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setrecentsearches, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, searches, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getrecentsearches, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setrecentsautosavename, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getrecentsautosavename, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setsendswholesearchstring, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_sendswholesearchstring, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setmaximumrecents, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, maximum, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_maximumrecents, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setsendssearchstringimmediately, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_sendssearchstringimmediately, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_searchbuttoncell, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_cancelbuttoncell, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_resetsearchbuttoncell, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_resetcancelbuttoncell, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setsearchmenutemplate, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, menu, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_searchmenutemplate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssearchfieldcell_nssearchfieldcell_method_entry) {
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, createText, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_createtext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, wrap, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, destroy, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, nsSearchFieldCell, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_nssearchfieldcell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setTitle, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_settitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getTitle, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_gettitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setStringValue, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setstringvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getStringValue, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getstringvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setPlaceholderString, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setplaceholderstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getPlaceholderString, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getplaceholderstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setRecentSearches, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setrecentsearches, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getRecentSearches, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getrecentsearches, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setRecentsAutosaveName, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setrecentsautosavename, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, getRecentsAutosaveName, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_getrecentsautosavename, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setSendsWholeSearchString, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setsendswholesearchstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, sendsWholeSearchString, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_sendswholesearchstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setMaximumRecents, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setmaximumrecents, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, maximumRecents, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_maximumrecents, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setSendsSearchStringImmediately, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setsendssearchstringimmediately, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, sendsSearchStringImmediately, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_sendssearchstringimmediately, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, searchButtonCell, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_searchbuttoncell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, cancelButtonCell, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_cancelbuttoncell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, resetSearchButtonCell, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_resetsearchbuttoncell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, resetCancelButtonCell, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_resetcancelbuttoncell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, setSearchMenuTemplate, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_setsearchmenutemplate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell, searchMenuTemplate, arginfo_appkit_ns_nssearchfieldcell_nssearchfieldcell_searchmenutemplate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
