
extern zend_class_entry *appkit_ns_nsstoryboardsegue_nsstoryboardsegue_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue);

PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, create);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, wrap);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, destroy);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, nsStoryboardSegue);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, getIdentifier);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, getSourceController);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, getDestinationController);
PHP_METHOD(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, perform);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_create, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, sourceControllerPtr, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, destinationControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsStoryboardSeguePtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, segue, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_nsstoryboardsegue, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, segue, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_getidentifier, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, segue, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_getsourcecontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, segue, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_getdestinationcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, segue, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_perform, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, segue, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsstoryboardsegue_nsstoryboardsegue_method_entry) {
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, create, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, wrap, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, destroy, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, nsStoryboardSegue, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_nsstoryboardsegue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, getIdentifier, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_getidentifier, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, getSourceController, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_getsourcecontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, getDestinationController, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_getdestinationcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStoryboardSegue_NSStoryboardSegue, perform, arginfo_appkit_ns_nsstoryboardsegue_nsstoryboardsegue_perform, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
