// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSView;

class NSView
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nsview_init_with_frame(x, y, width, height);
    }

    public static function window(int handle) -> int
    {
        return nsview_window(handle);
    }

    public static function superview(int handle) -> int
    {
        return nsview_superview(handle);
    }

    public static function subviews(int handle) -> array
    {
        var result;

        let result = nsview_subviews(handle);

        return result;
    }

    public static function setSubviews(int handle, array subviews) -> void
    {
        nsview_set_subviews(handle, subviews);
    }

    public static function isDescendantOf(int handle, int view) -> bool
    {
        int r;

        let r = nsview_is_descendant_of(handle, view);

        return r == 1;
    }

    public static function ancestorSharedWithView(int handle, int view) -> int
    {
        return nsview_ancestor_shared_with_view(handle, view);
    }

    public static function opaqueAncestor(int handle) -> int
    {
        return nsview_opaque_ancestor(handle);
    }

    public static function isHidden(int handle) -> bool
    {
        int r;

        let r = nsview_is_hidden(handle);

        return r == 1;
    }

    public static function setHidden(int handle, bool hidden) -> void
    {
        nsview_set_hidden(handle, hidden);
    }

    public static function isHiddenOrHasHiddenAncestor(int handle) -> bool
    {
        int r;

        let r = nsview_is_hidden_or_has_hidden_ancestor(handle);

        return r == 1;
    }

    public static function getRectsBeingDrawnCount(int handle) -> array
    {
        var result;

        let result = nsview_get_rects_being_drawn_count(handle);

        return result;
    }

    public static function needsToDrawRect(int handle, double x, double y, double width, double height) -> bool
    {
        int r;

        let r = nsview_needs_to_draw_rect(handle, x, y, width, height);

        return r == 1;
    }

    public static function wantsDefaultClipping(int handle) -> bool
    {
        int r;

        let r = nsview_wants_default_clipping(handle);

        return r == 1;
    }

    public static function viewDidHide(int handle) -> void
    {
        nsview_view_did_hide(handle);
    }

    public static function viewDidUnhide(int handle) -> void
    {
        nsview_view_did_unhide(handle);
    }

    public static function addSubview(int handle, int view) -> void
    {
        nsview_add_subview(handle, view);
    }

    public static function addSubviewPositionedRelativeTo(int handle, int view, int place, int otherView) -> void
    {
        nsview_add_subview_positioned_relative_to(handle, view, place, otherView);
    }

    public static function viewWillMoveToWindow(int handle, int newWindow) -> void
    {
        nsview_view_will_move_to_window(handle, newWindow);
    }

    public static function viewDidMoveToWindow(int handle) -> void
    {
        nsview_view_did_move_to_window(handle);
    }

    public static function viewWillMoveToSuperview(int handle, int newSuperview) -> void
    {
        nsview_view_will_move_to_superview(handle, newSuperview);
    }

    public static function viewDidMoveToSuperview(int handle) -> void
    {
        nsview_view_did_move_to_superview(handle);
    }

    public static function didAddSubview(int handle, int subview) -> void
    {
        nsview_did_add_subview(handle, subview);
    }

    public static function willRemoveSubview(int handle, int subview) -> void
    {
        nsview_will_remove_subview(handle, subview);
    }

    public static function removeFromSuperview(int handle) -> void
    {
        nsview_remove_from_superview(handle);
    }

    public static function replaceSubviewWith(int handle, int oldView, int newView) -> void
    {
        nsview_replace_subview_with(handle, oldView, newView);
    }

    public static function removeFromSuperviewWithoutNeedingDisplay(int handle) -> void
    {
        nsview_remove_from_superview_without_needing_display(handle);
    }

    public static function viewDidChangeBackingProperties(int handle) -> void
    {
        nsview_view_did_change_backing_properties(handle);
    }

    public static function postsFrameChangedNotifications(int handle) -> bool
    {
        int r;

        let r = nsview_posts_frame_changed_notifications(handle);

        return r == 1;
    }

    public static function setPostsFrameChangedNotifications(int handle, bool postsFrameChangedNotifications) -> void
    {
        nsview_set_posts_frame_changed_notifications(handle, postsFrameChangedNotifications);
    }

    public static function resizeSubviewsWithOldSize(int handle, double width, double height) -> void
    {
        nsview_resize_subviews_with_old_size(handle, width, height);
    }

    public static function resizeWithOldSuperviewSize(int handle, double width, double height) -> void
    {
        nsview_resize_with_old_superview_size(handle, width, height);
    }

    public static function autoresizesSubviews(int handle) -> bool
    {
        int r;

        let r = nsview_autoresizes_subviews(handle);

        return r == 1;
    }

    public static function setAutoresizesSubviews(int handle, bool autoresizesSubviews) -> void
    {
        nsview_set_autoresizes_subviews(handle, autoresizesSubviews);
    }

    public static function autoresizingMask(int handle) -> int
    {
        return nsview_autoresizing_mask(handle);
    }

    public static function setAutoresizingMask(int handle, int autoresizingMask) -> void
    {
        nsview_set_autoresizing_mask(handle, autoresizingMask);
    }

    public static function setFrameOrigin(int handle, double x, double y) -> void
    {
        nsview_set_frame_origin(handle, x, y);
    }

    public static function setFrameSize(int handle, double width, double height) -> void
    {
        nsview_set_frame_size(handle, width, height);
    }

    public static function frame(int handle) -> array
    {
        var result;

        let result = nsview_frame(handle);

        return result;
    }

    public static function setFrame(int handle, double x, double y, double width, double height) -> void
    {
        nsview_set_frame(handle, x, y, width, height);
    }

    public static function frameRotation(int handle) -> double
    {
        return nsview_frame_rotation(handle);
    }

    public static function setFrameRotation(int handle, double frameRotation) -> void
    {
        nsview_set_frame_rotation(handle, frameRotation);
    }

    public static function frameCenterRotation(int handle) -> double
    {
        return nsview_frame_center_rotation(handle);
    }

    public static function setFrameCenterRotation(int handle, double frameCenterRotation) -> void
    {
        nsview_set_frame_center_rotation(handle, frameCenterRotation);
    }

    public static function setBoundsOrigin(int handle, double x, double y) -> void
    {
        nsview_set_bounds_origin(handle, x, y);
    }

    public static function setBoundsSize(int handle, double width, double height) -> void
    {
        nsview_set_bounds_size(handle, width, height);
    }

    public static function boundsRotation(int handle) -> double
    {
        return nsview_bounds_rotation(handle);
    }

    public static function setBoundsRotation(int handle, double boundsRotation) -> void
    {
        nsview_set_bounds_rotation(handle, boundsRotation);
    }

    public static function translateOriginToPoint(int handle, double x, double y) -> void
    {
        nsview_translate_origin_to_point(handle, x, y);
    }

    public static function scaleUnitSquareToSize(int handle, double width, double height) -> void
    {
        nsview_scale_unit_square_to_size(handle, width, height);
    }

    public static function rotateByAngle(int handle, double angle) -> void
    {
        nsview_rotate_by_angle(handle, angle);
    }

    public static function bounds(int handle) -> array
    {
        var result;

        let result = nsview_bounds(handle);

        return result;
    }

    public static function setBounds(int handle, double x, double y, double width, double height) -> void
    {
        nsview_set_bounds(handle, x, y, width, height);
    }

    public static function isFlipped(int handle) -> bool
    {
        int r;

        let r = nsview_is_flipped(handle);

        return r == 1;
    }

    public static function isRotatedFromBase(int handle) -> bool
    {
        int r;

        let r = nsview_is_rotated_from_base(handle);

        return r == 1;
    }

    public static function isRotatedOrScaledFromBase(int handle) -> bool
    {
        int r;

        let r = nsview_is_rotated_or_scaled_from_base(handle);

        return r == 1;
    }

    public static function isOpaque(int handle) -> bool
    {
        int r;

        let r = nsview_is_opaque(handle);

        return r == 1;
    }

    public static function convertPointFromView(int handle, double x, double y, int view) -> array
    {
        var result;

        let result = nsview_convert_point_from_view(handle, x, y, view);

        return result;
    }

    public static function convertPointToView(int handle, double x, double y, int view) -> array
    {
        var result;

        let result = nsview_convert_point_to_view(handle, x, y, view);

        return result;
    }

    public static function convertSizeFromView(int handle, double width, double height, int view) -> array
    {
        var result;

        let result = nsview_convert_size_from_view(handle, width, height, view);

        return result;
    }

    public static function convertSizeToView(int handle, double width, double height, int view) -> array
    {
        var result;

        let result = nsview_convert_size_to_view(handle, width, height, view);

        return result;
    }

    public static function convertRectFromView(int handle, double x, double y, double width, double height, int view) -> array
    {
        var result;

        let result = nsview_convert_rect_from_view(handle, x, y, width, height, view);

        return result;
    }

    public static function convertRectToView(int handle, double x, double y, double width, double height, int view) -> array
    {
        var result;

        let result = nsview_convert_rect_to_view(handle, x, y, width, height, view);

        return result;
    }

    public static function backingAlignedRectOptions(int handle, double x, double y, double width, double height, int options) -> array
    {
        var result;

        let result = nsview_backing_aligned_rect_options(handle, x, y, width, height, options);

        return result;
    }

    public static function centerScanRect(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_center_scan_rect(handle, x, y, width, height);

        return result;
    }

    public static function convertPointToBacking(int handle, double x, double y) -> array
    {
        var result;

        let result = nsview_convert_point_to_backing(handle, x, y);

        return result;
    }

    public static function convertPointFromBacking(int handle, double x, double y) -> array
    {
        var result;

        let result = nsview_convert_point_from_backing(handle, x, y);

        return result;
    }

    public static function convertSizeToBacking(int handle, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_size_to_backing(handle, width, height);

        return result;
    }

    public static function convertSizeFromBacking(int handle, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_size_from_backing(handle, width, height);

        return result;
    }

    public static function convertRectToBacking(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_rect_to_backing(handle, x, y, width, height);

        return result;
    }

    public static function convertRectFromBacking(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_rect_from_backing(handle, x, y, width, height);

        return result;
    }

    public static function convertPointToLayer(int handle, double x, double y) -> array
    {
        var result;

        let result = nsview_convert_point_to_layer(handle, x, y);

        return result;
    }

    public static function convertPointFromLayer(int handle, double x, double y) -> array
    {
        var result;

        let result = nsview_convert_point_from_layer(handle, x, y);

        return result;
    }

    public static function convertSizeToLayer(int handle, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_size_to_layer(handle, width, height);

        return result;
    }

    public static function convertSizeFromLayer(int handle, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_size_from_layer(handle, width, height);

        return result;
    }

    public static function convertRectToLayer(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_rect_to_layer(handle, x, y, width, height);

        return result;
    }

    public static function convertRectFromLayer(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_convert_rect_from_layer(handle, x, y, width, height);

        return result;
    }

    public static function canDrawConcurrently(int handle) -> bool
    {
        int r;

        let r = nsview_can_draw_concurrently(handle);

        return r == 1;
    }

    public static function setCanDrawConcurrently(int handle, bool canDrawConcurrently) -> void
    {
        nsview_set_can_draw_concurrently(handle, canDrawConcurrently);
    }

    public static function setNeedsDisplayInRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_set_needs_display_in_rect(handle, x, y, width, height);
    }

    public static function needsDisplay(int handle) -> bool
    {
        int r;

        let r = nsview_needs_display(handle);

        return r == 1;
    }

    public static function setNeedsDisplay(int handle, bool needsDisplay) -> void
    {
        nsview_set_needs_display(handle, needsDisplay);
    }

    public static function focusView() -> int
    {
        return nsview_focus_view();
    }

    public static function visibleRect(int handle) -> array
    {
        var result;

        let result = nsview_visible_rect(handle);

        return result;
    }

    public static function display(int handle) -> void
    {
        nsview_display(handle);
    }

    public static function displayIfNeeded(int handle) -> void
    {
        nsview_display_if_needed(handle);
    }

    public static function displayIfNeededIgnoringOpacity(int handle) -> void
    {
        nsview_display_if_needed_ignoring_opacity(handle);
    }

    public static function displayRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_display_rect(handle, x, y, width, height);
    }

    public static function displayIfNeededInRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_display_if_needed_in_rect(handle, x, y, width, height);
    }

    public static function displayRectIgnoringOpacity(int handle, double x, double y, double width, double height) -> void
    {
        nsview_display_rect_ignoring_opacity(handle, x, y, width, height);
    }

    public static function displayIfNeededInRectIgnoringOpacity(int handle, double x, double y, double width, double height) -> void
    {
        nsview_display_if_needed_in_rect_ignoring_opacity(handle, x, y, width, height);
    }

    public static function drawRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_draw_rect(handle, x, y, width, height);
    }

    public static function displayRectIgnoringOpacityInContext(int handle, double x, double y, double width, double height, int context) -> void
    {
        nsview_display_rect_ignoring_opacity_in_context(handle, x, y, width, height, context);
    }

    public static function bitmapImageRepForCachingDisplayInRect(int handle, double x, double y, double width, double height) -> int
    {
        return nsview_bitmap_image_rep_for_caching_display_in_rect(handle, x, y, width, height);
    }

    public static function cacheDisplayInRectToBitmapImageRep(int handle, double x, double y, double width, double height, int bitmapImageRep) -> void
    {
        nsview_cache_display_in_rect_to_bitmap_image_rep(handle, x, y, width, height, bitmapImageRep);
    }

    public static function viewWillDraw(int handle) -> void
    {
        nsview_view_will_draw(handle);
    }

    public static function scrollPoint(int handle, double x, double y) -> void
    {
        nsview_scroll_point(handle, x, y);
    }

    public static function scrollRectToVisible(int handle, double x, double y, double width, double height) -> bool
    {
        int r;

        let r = nsview_scroll_rect_to_visible(handle, x, y, width, height);

        return r == 1;
    }

    public static function autoscroll(int handle, int event) -> bool
    {
        int r;

        let r = nsview_autoscroll(handle, event);

        return r == 1;
    }

    public static function adjustScroll(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_adjust_scroll(handle, x, y, width, height);

        return result;
    }

    public static function translateRectsNeedingDisplayInRectBy(int handle, double clipRectX, double clipRectY, double clipRectWidth, double clipRectHeight, double deltaWidth, double deltaHeight) -> void
    {
        nsview_translate_rects_needing_display_in_rect_by(handle, clipRectX, clipRectY, clipRectWidth, clipRectHeight, deltaWidth, deltaHeight);
    }

    public static function hitTest(int handle, double x, double y) -> int
    {
        return nsview_hit_test(handle, x, y);
    }

    public static function mouseInRect(int handle, double pointX, double pointY, double rectX, double rectY, double rectWidth, double rectHeight) -> bool
    {
        int r;

        let r = nsview_mouse_in_rect(handle, pointX, pointY, rectX, rectY, rectWidth, rectHeight);

        return r == 1;
    }

    public static function viewWithTag(int handle, int tag) -> int
    {
        return nsview_view_with_tag(handle, tag);
    }

    public static function tag(int handle) -> int
    {
        return nsview_tag(handle);
    }

    public static function performKeyEquivalent(int handle, int event) -> bool
    {
        int r;

        let r = nsview_perform_key_equivalent(handle, event);

        return r == 1;
    }

    public static function acceptsFirstMouse(int handle, int event) -> bool
    {
        int r;

        let r = nsview_accepts_first_mouse(handle, event);

        return r == 1;
    }

    public static function shouldDelayWindowOrderingForEvent(int handle, int event) -> bool
    {
        int r;

        let r = nsview_should_delay_window_ordering_for_event(handle, event);

        return r == 1;
    }

    public static function needsPanelToBecomeKey(int handle) -> bool
    {
        int r;

        let r = nsview_needs_panel_to_become_key(handle);

        return r == 1;
    }

    public static function mouseDownCanMoveWindow(int handle) -> bool
    {
        int r;

        let r = nsview_mouse_down_can_move_window(handle);

        return r == 1;
    }

    public static function wantsRestingTouches(int handle) -> bool
    {
        int r;

        let r = nsview_wants_resting_touches(handle);

        return r == 1;
    }

    public static function setWantsRestingTouches(int handle, bool wantsRestingTouches) -> void
    {
        nsview_set_wants_resting_touches(handle, wantsRestingTouches);
    }

    public static function makeBackingLayer(int handle) -> int
    {
        return nsview_make_backing_layer(handle);
    }

    public static function layerContentsRedrawPolicy(int handle) -> int
    {
        return nsview_layer_contents_redraw_policy(handle);
    }

    public static function setLayerContentsRedrawPolicy(int handle, int layerContentsRedrawPolicy) -> void
    {
        nsview_set_layer_contents_redraw_policy(handle, layerContentsRedrawPolicy);
    }

    public static function layerContentsPlacement(int handle) -> int
    {
        return nsview_layer_contents_placement(handle);
    }

    public static function setLayerContentsPlacement(int handle, int layerContentsPlacement) -> void
    {
        nsview_set_layer_contents_placement(handle, layerContentsPlacement);
    }

    public static function wantsLayer(int handle) -> bool
    {
        int r;

        let r = nsview_wants_layer(handle);

        return r == 1;
    }

    public static function setWantsLayer(int handle, bool wantsLayer) -> void
    {
        nsview_set_wants_layer(handle, wantsLayer);
    }

    public static function layer(int handle) -> int
    {
        return nsview_layer(handle);
    }

    public static function setLayer(int handle, int layer) -> void
    {
        nsview_set_layer(handle, layer);
    }

    public static function wantsUpdateLayer(int handle) -> bool
    {
        int r;

        let r = nsview_wants_update_layer(handle);

        return r == 1;
    }

    public static function updateLayer(int handle) -> void
    {
        nsview_update_layer(handle);
    }

    public static function canDrawSubviewsIntoLayer(int handle) -> bool
    {
        int r;

        let r = nsview_can_draw_subviews_into_layer(handle);

        return r == 1;
    }

    public static function setCanDrawSubviewsIntoLayer(int handle, bool canDrawSubviewsIntoLayer) -> void
    {
        nsview_set_can_draw_subviews_into_layer(handle, canDrawSubviewsIntoLayer);
    }

    public static function layoutSubtreeIfNeeded(int handle) -> void
    {
        nsview_layout_subtree_if_needed(handle);
    }

    public static function layout(int handle) -> void
    {
        nsview_layout(handle);
    }

    public static function needsLayout(int handle) -> bool
    {
        int r;

        let r = nsview_needs_layout(handle);

        return r == 1;
    }

    public static function setNeedsLayout(int handle, bool needsLayout) -> void
    {
        nsview_set_needs_layout(handle, needsLayout);
    }

    public static function alphaValue(int handle) -> double
    {
        return nsview_alpha_value(handle);
    }

    public static function setAlphaValue(int handle, double alphaValue) -> void
    {
        nsview_set_alpha_value(handle, alphaValue);
    }

    public static function layerUsesCoreImageFilters(int handle) -> bool
    {
        int r;

        let r = nsview_layer_uses_core_image_filters(handle);

        return r == 1;
    }

    public static function setLayerUsesCoreImageFilters(int handle, bool layerUsesCoreImageFilters) -> void
    {
        nsview_set_layer_uses_core_image_filters(handle, layerUsesCoreImageFilters);
    }

    public static function backgroundFilters(int handle) -> array
    {
        var result;

        let result = nsview_background_filters(handle);

        return result;
    }

    public static function setBackgroundFilters(int handle, array backgroundFilters) -> void
    {
        nsview_set_background_filters(handle, backgroundFilters);
    }

    public static function compositingFilter(int handle) -> int
    {
        return nsview_compositing_filter(handle);
    }

    public static function setCompositingFilter(int handle, int compositingFilter) -> void
    {
        nsview_set_compositing_filter(handle, compositingFilter);
    }

    public static function contentFilters(int handle) -> array
    {
        var result;

        let result = nsview_content_filters(handle);

        return result;
    }

    public static function setContentFilters(int handle, array contentFilters) -> void
    {
        nsview_set_content_filters(handle, contentFilters);
    }

    public static function shadow(int handle) -> int
    {
        return nsview_shadow(handle);
    }

    public static function setShadow(int handle, int shadow) -> void
    {
        nsview_set_shadow(handle, shadow);
    }

    public static function clipsToBounds(int handle) -> bool
    {
        int r;

        let r = nsview_clips_to_bounds(handle);

        return r == 1;
    }

    public static function setClipsToBounds(int handle, bool clipsToBounds) -> void
    {
        nsview_set_clips_to_bounds(handle, clipsToBounds);
    }

    public static function postsBoundsChangedNotifications(int handle) -> bool
    {
        int r;

        let r = nsview_posts_bounds_changed_notifications(handle);

        return r == 1;
    }

    public static function setPostsBoundsChangedNotifications(int handle, bool postsBoundsChangedNotifications) -> void
    {
        nsview_set_posts_bounds_changed_notifications(handle, postsBoundsChangedNotifications);
    }

    public static function enclosingScrollView(int handle) -> int
    {
        return nsview_enclosing_scroll_view(handle);
    }

    public static function menuForEvent(int handle, int event) -> int
    {
        return nsview_menu_for_event(handle, event);
    }

    public static function defaultMenu() -> int
    {
        return nsview_default_menu();
    }

    public static function willOpenMenuWithEvent(int handle, int menu, int event) -> void
    {
        nsview_will_open_menu_with_event(handle, menu, event);
    }

    public static function didCloseMenuWithEvent(int handle, int menu, int event) -> void
    {
        nsview_did_close_menu_with_event(handle, menu, event);
    }

    public static function toolTip(int handle) -> var
    {
        var result;

        let result = nsview_tool_tip(handle);

        return result;
    }

    public static function setToolTip(int handle, var toolTip) -> void
    {
        nsview_set_tool_tip(handle, toolTip);
    }

    public static function addToolTipRectOwnerUserData(int handle, double x, double y, double width, double height, int owner, int data) -> int
    {
        return nsview_add_tool_tip_rect_owner_user_data(handle, x, y, width, height, owner, data);
    }

    public static function removeToolTip(int handle, int tag) -> void
    {
        nsview_remove_tool_tip(handle, tag);
    }

    public static function removeAllToolTips(int handle) -> void
    {
        nsview_remove_all_tool_tips(handle);
    }

    public static function viewWillStartLiveResize(int handle) -> void
    {
        nsview_view_will_start_live_resize(handle);
    }

    public static function viewDidEndLiveResize(int handle) -> void
    {
        nsview_view_did_end_live_resize(handle);
    }

    public static function inLiveResize(int handle) -> bool
    {
        int r;

        let r = nsview_in_live_resize(handle);

        return r == 1;
    }

    public static function preservesContentDuringLiveResize(int handle) -> bool
    {
        int r;

        let r = nsview_preserves_content_during_live_resize(handle);

        return r == 1;
    }

    public static function rectPreservedDuringLiveResize(int handle) -> array
    {
        var result;

        let result = nsview_rect_preserved_during_live_resize(handle);

        return result;
    }

    public static function getRectsExposedDuringLiveResizeCount(int handle) -> array
    {
        var result;

        let result = nsview_get_rects_exposed_during_live_resize_count(handle);

        return result;
    }

    public static function inputContext(int handle) -> int
    {
        return nsview_input_context(handle);
    }

    public static function rectForSmartMagnificationAtPointInRect(int handle, double locationX, double locationY, double visibleRectX, double visibleRectY, double visibleRectWidth, double visibleRectHeight) -> array
    {
        var result;

        let result = nsview_rect_for_smart_magnification_at_point_in_rect(handle, locationX, locationY, visibleRectX, visibleRectY, visibleRectWidth, visibleRectHeight);

        return result;
    }

    public static function userInterfaceLayoutDirection(int handle) -> int
    {
        return nsview_user_interface_layout_direction(handle);
    }

    public static function setUserInterfaceLayoutDirection(int handle, int userInterfaceLayoutDirection) -> void
    {
        nsview_set_user_interface_layout_direction(handle, userInterfaceLayoutDirection);
    }

    public static function prepareForReuse(int handle) -> void
    {
        nsview_prepare_for_reuse(handle);
    }

    public static function isCompatibleWithResponsiveScrolling() -> bool
    {
        int r;

        let r = nsview_is_compatible_with_responsive_scrolling();

        return r == 1;
    }

    public static function prepareContentInRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_prepare_content_in_rect(handle, x, y, width, height);
    }

    public static function preparedContentRect(int handle) -> array
    {
        var result;

        let result = nsview_prepared_content_rect(handle);

        return result;
    }

    public static function setPreparedContentRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_set_prepared_content_rect(handle, x, y, width, height);
    }

    public static function allowsVibrancy(int handle) -> bool
    {
        int r;

        let r = nsview_allows_vibrancy(handle);

        return r == 1;
    }

    public static function viewDidChangeEffectiveAppearance(int handle) -> void
    {
        nsview_view_did_change_effective_appearance(handle);
    }

    public static function nextKeyView(int handle) -> int
    {
        return nsview_next_key_view(handle);
    }

    public static function setNextKeyView(int handle, int nextKeyView) -> void
    {
        nsview_set_next_key_view(handle, nextKeyView);
    }

    public static function previousKeyView(int handle) -> int
    {
        return nsview_previous_key_view(handle);
    }

    public static function nextValidKeyView(int handle) -> int
    {
        return nsview_next_valid_key_view(handle);
    }

    public static function previousValidKeyView(int handle) -> int
    {
        return nsview_previous_valid_key_view(handle);
    }

    public static function canBecomeKeyView(int handle) -> bool
    {
        int r;

        let r = nsview_can_become_key_view(handle);

        return r == 1;
    }

    public static function setKeyboardFocusRingNeedsDisplayInRect(int handle, double x, double y, double width, double height) -> void
    {
        nsview_set_keyboard_focus_ring_needs_display_in_rect(handle, x, y, width, height);
    }

    public static function focusRingType(int handle) -> int
    {
        return nsview_focus_ring_type(handle);
    }

    public static function setFocusRingType(int handle, int focusRingType) -> void
    {
        nsview_set_focus_ring_type(handle, focusRingType);
    }

    public static function defaultFocusRingType() -> int
    {
        return nsview_default_focus_ring_type();
    }

    public static function drawFocusRingMask(int handle) -> void
    {
        nsview_draw_focus_ring_mask(handle);
    }

    public static function focusRingMaskBounds(int handle) -> array
    {
        var result;

        let result = nsview_focus_ring_mask_bounds(handle);

        return result;
    }

    public static function noteFocusRingMaskChanged(int handle) -> void
    {
        nsview_note_focus_ring_mask_changed(handle);
    }

    public static function writeEPSInsideRectToPasteboard(int handle, double x, double y, double width, double height, int pasteboard) -> void
    {
        nsview_write_epsinside_rect_to_pasteboard(handle, x, y, width, height, pasteboard);
    }

    public static function writePDFInsideRectToPasteboard(int handle, double x, double y, double width, double height, int pasteboard) -> void
    {
        nsview_write_pdfinside_rect_to_pasteboard(handle, x, y, width, height, pasteboard);
    }

    public static function print_(int handle, int sender) -> void
    {
        nsview_print_(handle, sender);
    }

    public static function knowsPageRange(int handle) -> array
    {
        var result;

        let result = nsview_knows_page_range(handle);

        return result;
    }

    public static function heightAdjustLimit(int handle) -> double
    {
        return nsview_height_adjust_limit(handle);
    }

    public static function widthAdjustLimit(int handle) -> double
    {
        return nsview_width_adjust_limit(handle);
    }

    public static function adjustPageWidthNewLeftRightLimit(int handle, double oldLeft, double oldRight, double rightLimit) -> array
    {
        var result;

        let result = nsview_adjust_page_width_new_left_right_limit(handle, oldLeft, oldRight, rightLimit);

        return result;
    }

    public static function adjustPageHeightNewTopBottomLimit(int handle, double oldTop, double oldBottom, double bottomLimit) -> array
    {
        var result;

        let result = nsview_adjust_page_height_new_top_bottom_limit(handle, oldTop, oldBottom, bottomLimit);

        return result;
    }

    public static function rectForPage(int handle, int page) -> array
    {
        var result;

        let result = nsview_rect_for_page(handle, page);

        return result;
    }

    public static function locationOfPrintRect(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nsview_location_of_print_rect(handle, x, y, width, height);

        return result;
    }

    public static function drawPageBorderWithSize(int handle, double width, double height) -> void
    {
        nsview_draw_page_border_with_size(handle, width, height);
    }

    public static function printJobTitle(int handle) -> string
    {
        var result;

        let result = nsview_print_job_title(handle);

        return result;
    }

    public static function beginDocument(int handle) -> void
    {
        nsview_begin_document(handle);
    }

    public static function endDocument(int handle) -> void
    {
        nsview_end_document(handle);
    }

    public static function beginPageInRectAtPlacement(int handle, double rectX, double rectY, double rectWidth, double rectHeight, double locationX, double locationY) -> void
    {
        nsview_begin_page_in_rect_at_placement(handle, rectX, rectY, rectWidth, rectHeight, locationX, locationY);
    }

    public static function endPage(int handle) -> void
    {
        nsview_end_page(handle);
    }

    public static function beginDraggingSessionWithItemsEventSource(int handle, array items, int event, int source) -> int
    {
        return nsview_begin_dragging_session_with_items_event_source(handle, items, event, source);
    }

    public static function registeredDraggedTypes(int handle) -> array
    {
        var result;

        let result = nsview_registered_dragged_types(handle);

        return result;
    }

    public static function registerForDraggedTypes(int handle, array newTypes) -> void
    {
        nsview_register_for_dragged_types(handle, newTypes);
    }

    public static function unregisterDraggedTypes(int handle) -> void
    {
        nsview_unregister_dragged_types(handle);
    }

    public static function enterFullScreenModeWithOptions(int handle, int screen, int options) -> bool
    {
        int r;

        let r = nsview_enter_full_screen_mode_with_options(handle, screen, options);

        return r == 1;
    }

    public static function exitFullScreenModeWithOptions(int handle, int options) -> void
    {
        nsview_exit_full_screen_mode_with_options(handle, options);
    }

    public static function isInFullScreenMode(int handle) -> bool
    {
        int r;

        let r = nsview_is_in_full_screen_mode(handle);

        return r == 1;
    }

    public static function isDrawingFindIndicator(int handle) -> bool
    {
        int r;

        let r = nsview_is_drawing_find_indicator(handle);

        return r == 1;
    }

    public static function gestureRecognizers(int handle) -> array
    {
        var result;

        let result = nsview_gesture_recognizers(handle);

        return result;
    }

    public static function setGestureRecognizers(int handle, array gestureRecognizers) -> void
    {
        nsview_set_gesture_recognizers(handle, gestureRecognizers);
    }

    public static function addGestureRecognizer(int handle, int gestureRecognizer) -> void
    {
        nsview_add_gesture_recognizer(handle, gestureRecognizer);
    }

    public static function removeGestureRecognizer(int handle, int gestureRecognizer) -> void
    {
        nsview_remove_gesture_recognizer(handle, gestureRecognizer);
    }

    public static function allowedTouchTypes(int handle) -> int
    {
        return nsview_allowed_touch_types(handle);
    }

    public static function setAllowedTouchTypes(int handle, int allowedTouchTypes) -> void
    {
        nsview_set_allowed_touch_types(handle, allowedTouchTypes);
    }

    public static function safeAreaInsets(int handle) -> array
    {
        var result;

        let result = nsview_safe_area_insets(handle);

        return result;
    }

    public static function additionalSafeAreaInsets(int handle) -> array
    {
        var result;

        let result = nsview_additional_safe_area_insets(handle);

        return result;
    }

    public static function setAdditionalSafeAreaInsets(int handle, double top, double left, double bottom, double right) -> void
    {
        nsview_set_additional_safe_area_insets(handle, top, left, bottom, right);
    }

    public static function safeAreaLayoutGuide(int handle) -> int
    {
        return nsview_safe_area_layout_guide(handle);
    }

    public static function safeAreaRect(int handle) -> array
    {
        var result;

        let result = nsview_safe_area_rect(handle);

        return result;
    }

    public static function layoutMarginsGuide(int handle) -> int
    {
        return nsview_layout_margins_guide(handle);
    }

    public static function addTrackingArea(int handle, int trackingArea) -> void
    {
        nsview_add_tracking_area(handle, trackingArea);
    }

    public static function removeTrackingArea(int handle, int trackingArea) -> void
    {
        nsview_remove_tracking_area(handle, trackingArea);
    }

    public static function trackingAreas(int handle) -> array
    {
        var result;

        let result = nsview_tracking_areas(handle);

        return result;
    }

    public static function updateTrackingAreas(int handle) -> void
    {
        nsview_update_tracking_areas(handle);
    }

    public static function addCursorRectCursor(int handle, double x, double y, double width, double height, int object_) -> void
    {
        nsview_add_cursor_rect_cursor(handle, x, y, width, height, object_);
    }

    public static function removeCursorRectCursor(int handle, double x, double y, double width, double height, int object_) -> void
    {
        nsview_remove_cursor_rect_cursor(handle, x, y, width, height, object_);
    }

    public static function discardCursorRects(int handle) -> void
    {
        nsview_discard_cursor_rects(handle);
    }

    public static function resetCursorRects(int handle) -> void
    {
        nsview_reset_cursor_rects(handle);
    }

    public static function addTrackingRectOwnerUserDataAssumeInside(int handle, double x, double y, double width, double height, int owner, int data, bool flag) -> int
    {
        return nsview_add_tracking_rect_owner_user_data_assume_inside(handle, x, y, width, height, owner, data, flag);
    }

    public static function removeTrackingRect(int handle, int tag) -> void
    {
        nsview_remove_tracking_rect(handle, tag);
    }

    public static function displayLinkWithTargetSelector(int handle, int target, string selector) -> int
    {
        return nsview_display_link_with_target_selector(handle, target, selector);
    }

    public static function writingToolsCoordinator(int handle) -> int
    {
        return nsview_writing_tools_coordinator(handle);
    }

    public static function setWritingToolsCoordinator(int handle, int writingToolsCoordinator) -> void
    {
        nsview_set_writing_tools_coordinator(handle, writingToolsCoordinator);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
    // @reserved - (void)sortSubviewsUsingFunction:(NSComparisonResult (NS_NOESCAPE *)(__kindof NSView *, __kindof NSView *, void * _Nullable))compare context:(nullable void *)context;
    // @reserved @property (readonly) BOOL canDraw API_DEPRECATED("If a view needs display, -drawRect: or -updateLayer will be called automatically when the view is able to draw. To check whether a view is in a window, call -window. To check whether a view is hidden, call -isHiddenOrHasHiddenAncestor.", macos(10.0,10.14));
    // @reserved - (void)lockFocus API_DEPRECATED("To draw, subclass NSView and implement -drawRect:; AppKit's automatic deferred display mechanism will call -drawRect: as necessary to display the view.", macos(10.0,10.14));
    // @reserved - (void)unlockFocus API_DEPRECATED("To draw, subclass NSView and implement -drawRect:; AppKit's automatic deferred display mechanism will call -drawRect: as necessary to display the view.", macos(10.0,10.14));
    // @reserved - (BOOL)lockFocusIfCanDraw API_DEPRECATED("To draw, subclass NSView and implement -drawRect:; AppKit's automatic deferred display mechanism will call -drawRect: as necessary to display the view.", macos(10.0,10.14));
    // @reserved - (BOOL)lockFocusIfCanDrawInContext:(NSGraphicsContext *)context API_DEPRECATED("Use -[NSView displayRectIgnoringOpacity:inContext:] to draw a view subtree into a graphics context.", macos(10.4,10.13));
    // @reserved - (void)scrollRect:(NSRect)rect by:(NSSize)delta API_DEPRECATED("Use NSScrollView to achieve scrolling views.", macos(10.0,10.14));
    // @reserved @property BOOL acceptsTouchEvents API_DEPRECATED("Use allowedTouchTypes instead", macos(10.6,10.12.2)); — getter
    // @reserved @property BOOL acceptsTouchEvents API_DEPRECATED("Use allowedTouchTypes instead", macos(10.6,10.12.2)); — setter
    // @reserved - (NSData *)dataWithEPSInsideRect:(NSRect)rect;
    // @reserved - (NSData *)dataWithPDFInsideRect:(NSRect)rect;
    // @reserved @property (readonly, copy) NSAttributedString *pageHeader;
    // @reserved @property (readonly, copy) NSAttributedString *pageFooter;
    // @reserved - (void)drawSheetBorderWithSize:(NSSize)borderSize API_DEPRECATED("This is never invoked and the NSView implementation does nothing", macos(10.0,10.14));
    // @reserved - (void)showDefinitionForAttributedString:(nullable NSAttributedString *)attrString atPoint:(NSPoint)textBaselineOrigin API_AVAILABLE(macos(10.6));
    // @reserved - (void)showDefinitionForAttributedString:(nullable NSAttributedString *)attrString range:(NSRange)targetRange options:(nullable NSDictionary<NSDefinitionOptionKey, id> *)options baselineOriginProvider:(NSPoint (^ _Nullable)(NSRange adjustedRange))originProvider API_AVAILABLE(macos(10.6));
    // @reserved - (void)dragImage:(NSImage *)image at:(NSPoint)viewLocation offset:(NSSize)initialOffset event:(NSEvent *)event pasteboard:(NSPasteboard *)pboard source:(id)sourceObj slideBack:(BOOL)slideFlag API_DEPRECATED("Use -beginDraggingSessionWithItems:event:source: instead", macos(10.0,10.7));
    // @reserved - (BOOL)dragFile:(NSString *)filename fromRect:(NSRect)rect slideBack:(BOOL)flag event:(NSEvent *)event API_DEPRECATED("Use -beginDraggingSessionWithItems:event:source: instead", macos(10.0,10.13));
    // @reserved - (BOOL)dragPromisedFilesOfTypes:(NSArray<NSString *> *)typeArray fromRect:(NSRect)rect source:(id)sourceObject slideBack:(BOOL)flag event:(NSEvent *)event API_DEPRECATED("Use -beginDraggingSessionWithItems:event:source: with an NSFilePromiseProvider instead", macos(10.0,10.13));
    // @reserved - (NSPoint)convertPointToBase:(NSPoint)point API_DEPRECATED("", macos(10.5,10.7));
    // @reserved - (NSPoint)convertPointFromBase:(NSPoint)point API_DEPRECATED("", macos(10.5,10.7));
    // @reserved - (NSSize)convertSizeToBase:(NSSize)size API_DEPRECATED("", macos(10.5,10.7));
    // @reserved - (NSSize)convertSizeFromBase:(NSSize)size API_DEPRECATED("", macos(10.5,10.7));
    // @reserved - (NSRect)convertRectToBase:(NSRect)rect API_DEPRECATED("", macos(10.5,10.7));
    // @reserved - (NSRect)convertRectFromBase:(NSRect)rect API_DEPRECATED("", macos(10.5,10.7));
    // @reserved - (BOOL)performMnemonic:(NSString *)string API_DEPRECATED("This has always returned NO and had no effect on macOS", macos(10.0,10.8));
    // @reserved - (BOOL)shouldDrawColor API_DEPRECATED("This method no longer does anything", macos(10.0,10.10));
    // @reserved - (NSInteger)gState API_DEPRECATED("", macos(10.0,10.10));
    // @reserved - (void)allocateGState API_DEPRECATED("", macos(10.0,10.10));
    // @reserved - (oneway void)releaseGState API_DEPRECATED("", macos(10.0,10.10));
    // @reserved - (void)setUpGState API_DEPRECATED("", macos(10.0,10.10));
    // @reserved - (void)renewGState API_DEPRECATED("", macos(10.0,10.10));

}
