
extern zend_class_entry *appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout);

PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, create);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, wrap);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, destroy);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, nsCollectionViewGridLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMargins);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMinimumInteritemSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMinimumInteritemSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMinimumLineSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMinimumLineSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMaximumNumberOfRows);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMaximumNumberOfRows);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMaximumNumberOfColumns);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMaximumNumberOfColumns);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMinimumItemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMinimumItemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMaximumItemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMaximumItemSize);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsCollectionViewGridLayoutPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_nscollectionviewgridlayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmargins, 0, 5, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, top, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, left, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, bottom, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, right, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setminimuminteritemspacing, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, spacing, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getminimuminteritemspacing, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setminimumlinespacing, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, spacing, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getminimumlinespacing, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmaximumnumberofrows, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rows, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getmaximumnumberofrows, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmaximumnumberofcolumns, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, columns, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getmaximumnumberofcolumns, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setminimumitemsize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getminimumitemsize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmaximumitemsize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getmaximumitemsize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, create, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, wrap, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, destroy, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, nsCollectionViewGridLayout, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_nscollectionviewgridlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMargins, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmargins, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMinimumInteritemSpacing, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setminimuminteritemspacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMinimumInteritemSpacing, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getminimuminteritemspacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMinimumLineSpacing, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setminimumlinespacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMinimumLineSpacing, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getminimumlinespacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMaximumNumberOfRows, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmaximumnumberofrows, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMaximumNumberOfRows, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getmaximumnumberofrows, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMaximumNumberOfColumns, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmaximumnumberofcolumns, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMaximumNumberOfColumns, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getmaximumnumberofcolumns, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMinimumItemSize, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setminimumitemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMinimumItemSize, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getminimumitemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, setMaximumItemSize, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_setmaximumitemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout, getMaximumItemSize, arginfo_appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_getmaximumitemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
