// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSProgressIndicator;

class NSProgressIndicator
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nsprogressindicator_init_with_frame(x, y, width, height);
    }

    public static function isIndeterminate(int handle) -> bool
    {
        int r;

        let r = nsprogressindicator_is_indeterminate(handle);

        return r == 1;
    }

    public static function setIndeterminate(int handle, bool indeterminate) -> void
    {
        nsprogressindicator_set_indeterminate(handle, indeterminate);
    }

    public static function controlSize(int handle) -> int
    {
        return nsprogressindicator_control_size(handle);
    }

    public static function setControlSize(int handle, int controlSize) -> void
    {
        nsprogressindicator_set_control_size(handle, controlSize);
    }

    public static function doubleValue(int handle) -> double
    {
        return nsprogressindicator_double_value(handle);
    }

    public static function setDoubleValue(int handle, double doubleValue) -> void
    {
        nsprogressindicator_set_double_value(handle, doubleValue);
    }

    public static function incrementBy(int handle, double delta) -> void
    {
        nsprogressindicator_increment_by(handle, delta);
    }

    public static function minValue(int handle) -> double
    {
        return nsprogressindicator_min_value(handle);
    }

    public static function setMinValue(int handle, double minValue) -> void
    {
        nsprogressindicator_set_min_value(handle, minValue);
    }

    public static function maxValue(int handle) -> double
    {
        return nsprogressindicator_max_value(handle);
    }

    public static function setMaxValue(int handle, double maxValue) -> void
    {
        nsprogressindicator_set_max_value(handle, maxValue);
    }

    public static function observedProgress(int handle) -> int
    {
        return nsprogressindicator_observed_progress(handle);
    }

    public static function setObservedProgress(int handle, int observedProgress) -> void
    {
        nsprogressindicator_set_observed_progress(handle, observedProgress);
    }

    public static function usesThreadedAnimation(int handle) -> bool
    {
        int r;

        let r = nsprogressindicator_uses_threaded_animation(handle);

        return r == 1;
    }

    public static function setUsesThreadedAnimation(int handle, bool usesThreadedAnimation) -> void
    {
        nsprogressindicator_set_uses_threaded_animation(handle, usesThreadedAnimation);
    }

    public static function startAnimation(int handle, int sender) -> void
    {
        nsprogressindicator_start_animation(handle, sender);
    }

    public static function stopAnimation(int handle, int sender) -> void
    {
        nsprogressindicator_stop_animation(handle, sender);
    }

    public static function style(int handle) -> int
    {
        return nsprogressindicator_style(handle);
    }

    public static function setStyle(int handle, int style) -> void
    {
        nsprogressindicator_set_style(handle, style);
    }

    public static function sizeToFit(int handle) -> void
    {
        nsprogressindicator_size_to_fit(handle);
    }

    public static function isDisplayedWhenStopped(int handle) -> bool
    {
        int r;

        let r = nsprogressindicator_is_displayed_when_stopped(handle);

        return r == 1;
    }

    public static function setDisplayedWhenStopped(int handle, bool displayedWhenStopped) -> void
    {
        nsprogressindicator_set_displayed_when_stopped(handle, displayedWhenStopped);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (NSTimeInterval)animationDelay API_DEPRECATED
    // @reserved - (void)setAnimationDelay:(NSTimeInterval)delay API_DEPRECATED
    // @reserved - (void)animate:(nullable id)sender API_DEPRECATED
    // @reserved @property (getter=isBezeled) BOOL bezeled API_DEPRECATED — getter
    // @reserved @property (getter=isBezeled) BOOL bezeled API_DEPRECATED — setter
    // @reserved @property NSControlTint controlTint API_DEPRECATED — getter
    // @reserved @property NSControlTint controlTint API_DEPRECATED — setter

}
