
extern zend_class_entry *appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem);

PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, stepperWithFormatter);
PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, nsStepperTouchBarItem);
PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, setValue);
PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, getValue);
PHP_METHOD(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, pollAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_stepperwithformatter, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_nssteppertouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_setvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_getvalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_pollaction, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, stepperWithFormatter, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_stepperwithformatter, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, wrap, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, destroy, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, nsStepperTouchBarItem, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_nssteppertouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, setValue, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_setvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, getValue, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_getvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSStepperTouchBarItem_NSStepperTouchBarItem, pollAction, arginfo_appkit_ns_nssteppertouchbaritem_nssteppertouchbaritem_pollaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
