// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSPathCell;

class NSPathCell
{
    public static function initTextCell(string string_) -> int
    {
        return nspathcell_init_text_cell(string_);
    }

    public static function initImageCell(int image) -> int
    {
        return nspathcell_init_image_cell(image);
    }

    public static function pathStyle(int handle) -> int
    {
        return nspathcell_path_style(handle);
    }

    public static function setPathStyle(int handle, int pathStyle) -> void
    {
        nspathcell_set_path_style(handle, pathStyle);
    }

    public static function Url(int handle) -> int
    {
        return nspathcell_url(handle);
    }

    public static function setURL(int handle, int Url) -> void
    {
        nspathcell_set_url(handle, Url);
    }

    public static function setObjectValue(int handle, int obj) -> void
    {
        nspathcell_set_object_value(handle, obj);
    }

    public static function allowedTypes(int handle) -> var
    {
        var result;

        let result = nspathcell_allowed_types(handle);

        return result;
    }

    public static function setAllowedTypes(int handle, var allowedTypes) -> void
    {
        nspathcell_set_allowed_types(handle, allowedTypes);
    }

    public static function delegate(int handle) -> int
    {
        return nspathcell_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nspathcell_set_delegate(handle, delegate);
    }

    public static function pathComponentCells(int handle) -> array
    {
        var result;

        let result = nspathcell_path_component_cells(handle);

        return result;
    }

    public static function setPathComponentCells(int handle, array pathComponentCells) -> void
    {
        nspathcell_set_path_component_cells(handle, pathComponentCells);
    }

    public static function rectOfPathComponentCellWithFrameInView(int handle, int cell, double x, double y, double width, double height, int view) -> array
    {
        var result;

        let result = nspathcell_rect_of_path_component_cell_with_frame_in_view(handle, cell, x, y, width, height, view);

        return result;
    }

    public static function pathComponentCellAtPointWithFrameInView(int handle, double locationX, double locationY, double x, double y, double width, double height, int view) -> int
    {
        return nspathcell_path_component_cell_at_point_with_frame_in_view(handle, locationX, locationY, x, y, width, height, view);
    }

    public static function clickedPathComponentCell(int handle) -> int
    {
        return nspathcell_clicked_path_component_cell(handle);
    }

    public static function mouseEnteredWithFrameInView(int handle, int event, double x, double y, double width, double height, int view) -> void
    {
        nspathcell_mouse_entered_with_frame_in_view(handle, event, x, y, width, height, view);
    }

    public static function mouseExitedWithFrameInView(int handle, int event, double x, double y, double width, double height, int view) -> void
    {
        nspathcell_mouse_exited_with_frame_in_view(handle, event, x, y, width, height, view);
    }

    public static function doubleAction(int handle) -> var
    {
        var result;

        let result = nspathcell_double_action(handle);

        return result;
    }

    public static function setDoubleAction(int handle, var doubleAction) -> void
    {
        nspathcell_set_double_action(handle, doubleAction);
    }

    public static function backgroundColor(int handle) -> int
    {
        return nspathcell_background_color(handle);
    }

    public static function setBackgroundColor(int handle, int backgroundColor) -> void
    {
        nspathcell_set_background_color(handle, backgroundColor);
    }

    public static function placeholderString(int handle) -> var
    {
        var result;

        let result = nspathcell_placeholder_string(handle);

        return result;
    }

    public static function setPlaceholderString(int handle, var placeholderString) -> void
    {
        nspathcell_set_placeholder_string(handle, placeholderString);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (class, readonly) Class pathComponentCellClass — Class
    // @reserved @property (nullable, copy) NSAttributedString *placeholderAttributedString — getter
    // @reserved @property (nullable, copy) NSAttributedString *placeholderAttributedString — setter

}
