
extern zend_class_entry *appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController);

PHP_METHOD(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, wrap);
PHP_METHOD(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, destroy);
PHP_METHOD(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, viewportBounds);
PHP_METHOD(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, layoutViewport);
PHP_METHOD(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, adjustViewportByVerticalOffset);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTextViewportLayoutControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_viewportbounds, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_layoutviewport, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_adjustviewportbyverticaloffset, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_method_entry) {
	PHP_ME(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, wrap, arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, destroy, arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, viewportBounds, arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_viewportbounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, layoutViewport, arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_layoutviewport, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController, adjustViewportByVerticalOffset, arginfo_appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_adjustviewportbyverticaloffset, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
