// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSCollectionViewFlowLayoutInvalidationContext;

class NSCollectionViewFlowLayoutInvalidationContext
{
    public static function init() -> int
    {
        return nscollectionviewflowlayoutinvalidationcontext_init();
    }

    public static function invalidateFlowLayoutDelegateMetrics(int handle) -> bool
    {
        int r;

        let r = nscollectionviewflowlayoutinvalidationcontext_invalidate_flow_layout_delegate_metrics(handle);

        return r == 1;
    }

    public static function setInvalidateFlowLayoutDelegateMetrics(int handle, bool invalidateFlowLayoutDelegateMetrics) -> void
    {
        nscollectionviewflowlayoutinvalidationcontext_set_invalidate_flow_layout_delegate_metrics(handle, invalidateFlowLayoutDelegateMetrics);
    }

    public static function invalidateFlowLayoutAttributes(int handle) -> bool
    {
        int r;

        let r = nscollectionviewflowlayoutinvalidationcontext_invalidate_flow_layout_attributes(handle);

        return r == 1;
    }

    public static function setInvalidateFlowLayoutAttributes(int handle, bool invalidateFlowLayoutAttributes) -> void
    {
        nscollectionviewflowlayoutinvalidationcontext_set_invalidate_flow_layout_attributes(handle, invalidateFlowLayoutAttributes);
    }
}
