// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSGridView;

class NSGridView
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nsgridview_init_with_frame(x, y, width, height);
    }

    public static function gridViewWithNumberOfColumnsRows(int columnCount, int rowCount) -> int
    {
        return nsgridview_grid_view_with_number_of_columns_rows(columnCount, rowCount);
    }

    public static function gridViewWithViews(array rows) -> int
    {
        return nsgridview_grid_view_with_views(rows);
    }

    public static function numberOfRows(int handle) -> int
    {
        return nsgridview_number_of_rows(handle);
    }

    public static function numberOfColumns(int handle) -> int
    {
        return nsgridview_number_of_columns(handle);
    }

    public static function rowAtIndex(int handle, int index) -> int
    {
        return nsgridview_row_at_index(handle, index);
    }

    public static function indexOfRow(int handle, int row) -> int
    {
        return nsgridview_index_of_row(handle, row);
    }

    public static function columnAtIndex(int handle, int index) -> int
    {
        return nsgridview_column_at_index(handle, index);
    }

    public static function indexOfColumn(int handle, int column) -> int
    {
        return nsgridview_index_of_column(handle, column);
    }

    public static function cellAtColumnIndexRowIndex(int handle, int columnIndex, int rowIndex) -> int
    {
        return nsgridview_cell_at_column_index_row_index(handle, columnIndex, rowIndex);
    }

    public static function cellForView(int handle, int view) -> int
    {
        return nsgridview_cell_for_view(handle, view);
    }

    public static function addRowWithViews(int handle, array views) -> int
    {
        return nsgridview_add_row_with_views(handle, views);
    }

    public static function insertRowAtIndexWithViews(int handle, int index, array views) -> int
    {
        return nsgridview_insert_row_at_index_with_views(handle, index, views);
    }

    public static function moveRowAtIndexToIndex(int handle, int fromIndex, int toIndex) -> void
    {
        nsgridview_move_row_at_index_to_index(handle, fromIndex, toIndex);
    }

    public static function removeRowAtIndex(int handle, int index) -> void
    {
        nsgridview_remove_row_at_index(handle, index);
    }

    public static function addColumnWithViews(int handle, array views) -> int
    {
        return nsgridview_add_column_with_views(handle, views);
    }

    public static function insertColumnAtIndexWithViews(int handle, int index, array views) -> int
    {
        return nsgridview_insert_column_at_index_with_views(handle, index, views);
    }

    public static function moveColumnAtIndexToIndex(int handle, int fromIndex, int toIndex) -> void
    {
        nsgridview_move_column_at_index_to_index(handle, fromIndex, toIndex);
    }

    public static function removeColumnAtIndex(int handle, int index) -> void
    {
        nsgridview_remove_column_at_index(handle, index);
    }

    public static function xPlacement(int handle) -> int
    {
        return nsgridview_x_placement(handle);
    }

    public static function setXPlacement(int handle, int xPlacement) -> void
    {
        nsgridview_set_x_placement(handle, xPlacement);
    }

    public static function yPlacement(int handle) -> int
    {
        return nsgridview_y_placement(handle);
    }

    public static function setYPlacement(int handle, int yPlacement) -> void
    {
        nsgridview_set_y_placement(handle, yPlacement);
    }

    public static function rowAlignment(int handle) -> int
    {
        return nsgridview_row_alignment(handle);
    }

    public static function setRowAlignment(int handle, int rowAlignment) -> void
    {
        nsgridview_set_row_alignment(handle, rowAlignment);
    }

    public static function rowSpacing(int handle) -> double
    {
        return nsgridview_row_spacing(handle);
    }

    public static function setRowSpacing(int handle, double rowSpacing) -> void
    {
        nsgridview_set_row_spacing(handle, rowSpacing);
    }

    public static function columnSpacing(int handle) -> double
    {
        return nsgridview_column_spacing(handle);
    }

    public static function setColumnSpacing(int handle, double columnSpacing) -> void
    {
        nsgridview_set_column_spacing(handle, columnSpacing);
    }

    public static function mergeCellsInHorizontalRangeVerticalRange(int handle, int hLocation, int hLength, int vLocation, int vLength) -> void
    {
        nsgridview_merge_cells_in_horizontal_range_vertical_range(handle, hLocation, hLength, vLocation, vLength);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

}
