// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSFont;

class NSFont
{
    public static function fontWithNameSize(string fontName, double fontSize) -> int
    {
        return nsfont_font_with_name_size(fontName, fontSize);
    }

    public static function fontWithDescriptorSize(int fontDescriptor, double fontSize) -> int
    {
        return nsfont_font_with_descriptor_size(fontDescriptor, fontSize);
    }

    public static function fontWithDescriptorTextTransform(int fontDescriptor, int textTransform) -> int
    {
        return nsfont_font_with_descriptor_text_transform(fontDescriptor, textTransform);
    }

    public static function userFontOfSize(double fontSize) -> int
    {
        return nsfont_user_font_of_size(fontSize);
    }

    public static function userFixedPitchFontOfSize(double fontSize) -> int
    {
        return nsfont_user_fixed_pitch_font_of_size(fontSize);
    }

    public static function setUserFont(int font) -> void
    {
        nsfont_set_user_font(font);
    }

    public static function setUserFixedPitchFont(int font) -> void
    {
        nsfont_set_user_fixed_pitch_font(font);
    }

    public static function systemFontOfSize(double fontSize) -> int
    {
        return nsfont_system_font_of_size(fontSize);
    }

    public static function boldSystemFontOfSize(double fontSize) -> int
    {
        return nsfont_bold_system_font_of_size(fontSize);
    }

    public static function labelFontOfSize(double fontSize) -> int
    {
        return nsfont_label_font_of_size(fontSize);
    }

    public static function titleBarFontOfSize(double fontSize) -> int
    {
        return nsfont_title_bar_font_of_size(fontSize);
    }

    public static function menuFontOfSize(double fontSize) -> int
    {
        return nsfont_menu_font_of_size(fontSize);
    }

    public static function menuBarFontOfSize(double fontSize) -> int
    {
        return nsfont_menu_bar_font_of_size(fontSize);
    }

    public static function messageFontOfSize(double fontSize) -> int
    {
        return nsfont_message_font_of_size(fontSize);
    }

    public static function paletteFontOfSize(double fontSize) -> int
    {
        return nsfont_palette_font_of_size(fontSize);
    }

    public static function toolTipsFontOfSize(double fontSize) -> int
    {
        return nsfont_tool_tips_font_of_size(fontSize);
    }

    public static function controlContentFontOfSize(double fontSize) -> int
    {
        return nsfont_control_content_font_of_size(fontSize);
    }

    public static function systemFontOfSizeWeight(double fontSize, double weight) -> int
    {
        return nsfont_system_font_of_size_weight(fontSize, weight);
    }

    public static function monospacedDigitSystemFontOfSizeWeight(double fontSize, double weight) -> int
    {
        return nsfont_monospaced_digit_system_font_of_size_weight(fontSize, weight);
    }

    public static function systemFontOfSizeWeightWidth(double fontSize, double weight, double width) -> int
    {
        return nsfont_system_font_of_size_weight_width(fontSize, weight, width);
    }

    public static function monospacedSystemFontOfSizeWeight(double fontSize, double weight) -> int
    {
        return nsfont_monospaced_system_font_of_size_weight(fontSize, weight);
    }

    public static function fontWithSize(int handle, double fontSize) -> int
    {
        return nsfont_font_with_size(handle, fontSize);
    }

    public static function systemFontSize() -> double
    {
        return nsfont_system_font_size();
    }

    public static function smallSystemFontSize() -> double
    {
        return nsfont_small_system_font_size();
    }

    public static function labelFontSize() -> double
    {
        return nsfont_label_font_size();
    }

    public static function systemFontSizeForControlSize(int controlSize) -> double
    {
        return nsfont_system_font_size_for_control_size(controlSize);
    }

    public static function fontName(int handle) -> string
    {
        var result;

        let result = nsfont_font_name(handle);

        return result;
    }

    public static function pointSize(int handle) -> double
    {
        return nsfont_point_size(handle);
    }

    public static function familyName(int handle) -> var
    {
        var result;

        let result = nsfont_family_name(handle);

        return result;
    }

    public static function displayName(int handle) -> var
    {
        var result;

        let result = nsfont_display_name(handle);

        return result;
    }

    public static function fontDescriptor(int handle) -> int
    {
        return nsfont_font_descriptor(handle);
    }

    public static function textTransform(int handle) -> int
    {
        return nsfont_text_transform(handle);
    }

    public static function numberOfGlyphs(int handle) -> int
    {
        return nsfont_number_of_glyphs(handle);
    }

    public static function mostCompatibleStringEncoding(int handle) -> int
    {
        return nsfont_most_compatible_string_encoding(handle);
    }

    public static function coveredCharacterSet(int handle) -> int
    {
        return nsfont_covered_character_set(handle);
    }

    public static function boundingRectForFont(int handle) -> array
    {
        var result;

        let result = nsfont_bounding_rect_for_font(handle);

        return result;
    }

    public static function maximumAdvancement(int handle) -> array
    {
        var result;

        let result = nsfont_maximum_advancement(handle);

        return result;
    }

    public static function ascender(int handle) -> double
    {
        return nsfont_ascender(handle);
    }

    public static function descender(int handle) -> double
    {
        return nsfont_descender(handle);
    }

    public static function leading(int handle) -> double
    {
        return nsfont_leading(handle);
    }

    public static function underlinePosition(int handle) -> double
    {
        return nsfont_underline_position(handle);
    }

    public static function underlineThickness(int handle) -> double
    {
        return nsfont_underline_thickness(handle);
    }

    public static function italicAngle(int handle) -> double
    {
        return nsfont_italic_angle(handle);
    }

    public static function capHeight(int handle) -> double
    {
        return nsfont_cap_height(handle);
    }

    public static function xHeight(int handle) -> double
    {
        return nsfont_x_height(handle);
    }

    public static function isFixedPitch(int handle) -> bool
    {
        int r;

        let r = nsfont_is_fixed_pitch(handle);

        return r == 1;
    }

    public static function boundingRectForCGGlyph(int handle, int glyph) -> array
    {
        var result;

        let result = nsfont_bounding_rect_for_cg_glyph(handle, glyph);

        return result;
    }

    public static function advancementForCGGlyph(int handle, int glyph) -> array
    {
        var result;

        let result = nsfont_advancement_for_cg_glyph(handle, glyph);

        return result;
    }

    public static function set(int handle) -> void
    {
        nsfont_set(handle);
    }

    public static function setInContext(int handle, int graphicsContext) -> void
    {
        nsfont_set_in_context(handle, graphicsContext);
    }

    public static function verticalFont(int handle) -> int
    {
        return nsfont_vertical_font(handle);
    }

    public static function isVertical(int handle) -> bool
    {
        int r;

        let r = nsfont_is_vertical(handle);

        return r == 1;
    }

    public static function glyphWithName(int handle, string name) -> int
    {
        return nsfont_glyph_with_name(handle, name);
    }

    public static function boundingRectForGlyph(int handle, int glyph) -> array
    {
        var result;

        let result = nsfont_bounding_rect_for_glyph(handle, glyph);

        return result;
    }

    public static function advancementForGlyph(int handle, int glyph) -> array
    {
        var result;

        let result = nsfont_advancement_for_glyph(handle, glyph);

        return result;
    }

    public static function printerFont(int handle) -> int
    {
        return nsfont_printer_font(handle);
    }

    public static function screenFont(int handle) -> int
    {
        return nsfont_screen_font(handle);
    }

    public static function screenFontWithRenderingMode(int handle, int renderingMode) -> int
    {
        return nsfont_screen_font_with_rendering_mode(handle, renderingMode);
    }

    public static function renderingMode(int handle) -> int
    {
        return nsfont_rendering_mode(handle);
    }

    public static function preferredFontForTextStyleOptions(string style, int options) -> int
    {
        return nsfont_preferred_font_for_text_style_options(style, options);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved + (nullable NSFont *)fontWithName:(NSString *)fontName matrix:(const CGFloat *)fontMatrix — C font-matrix pointer
    // @reserved @property (readonly) const CGFloat *matrix NS_RETURNS_INNER_POINTER — C font-matrix pointer
    // @reserved - (void)getBoundingRects:(NSRectArray)bounds forCGGlyphs:(const CGGlyph *)glyphs count:(NSUInteger)glyphCount — C rect/glyph buffers
    // @reserved - (void)getAdvancements:(NSSizeArray)advancements forCGGlyphs:(const CGGlyph *)glyphs count:(NSUInteger)glyphCount — C size/glyph buffers
    // @reserved - (void)getBoundingRects:(NSRectArray)bounds forGlyphs:(const NSGlyph *)glyphs count:(NSUInteger)glyphCount — C rect/glyph buffers
    // @reserved - (void)getAdvancements:(NSSizeArray)advancements forGlyphs:(const NSGlyph *)glyphs count:(NSUInteger)glyphCount — C size/glyph buffers
    // @reserved - (void)getAdvancements:(NSSizeArray)advancements forPackedGlyphs:(const void *)packedGlyphs length:(NSUInteger)length — C size/packed-glyph buffers

}
