// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSecureTextFieldCell;

class NSSecureTextFieldCell
{
    public static function initTextCell(string string_) -> int
    {
        return nssecuretextfieldcell_init_text_cell(string_);
    }

    public static function echosBullets(int handle) -> bool
    {
        int r;

        let r = nssecuretextfieldcell_echos_bullets(handle);

        return r == 1;
    }

    public static function setEchosBullets(int handle, bool echosBullets) -> void
    {
        nssecuretextfieldcell_set_echos_bullets(handle, echosBullets);
    }
}
