
extern zend_class_entry *appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer);

PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, create);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, destroy);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, setEnabled);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, isEnabled);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, state);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, addToView);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, removeFromView);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, locationInView);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, rotation);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, rotationInDegrees);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, setRotation);
PHP_METHOD(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, nsRotationGestureRecognizer);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_setenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, enabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_isenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_state, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_addtoview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_removefromview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_locationinview, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_rotation, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_rotationindegrees, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_setrotation, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, radians, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_nsrotationgesturerecognizer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_method_entry) {
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, create, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, destroy, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, setEnabled, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_setenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, isEnabled, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_isenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, state, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_state, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, addToView, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_addtoview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, removeFromView, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_removefromview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, locationInView, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_locationinview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, rotation, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_rotation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, rotationInDegrees, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_rotationindegrees, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, setRotation, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_setrotation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer, nsRotationGestureRecognizer, arginfo_appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_nsrotationgesturerecognizer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
