
extern zend_class_entry *appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource);

PHP_METHOD(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, create);
PHP_METHOD(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, destroy);
PHP_METHOD(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, setItemTitle);
PHP_METHOD(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, apply);
PHP_METHOD(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, itemCount);
PHP_METHOD(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, itemIdAt);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, collection, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_setitemtitle, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, itemId, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_apply, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionId, IS_STRING, 0)
	ZEND_ARG_ARRAY_INFO(0, itemIds, 0)
	ZEND_ARG_TYPE_INFO(0, animating, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_itemcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_itemidat, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, create, arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, destroy, arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, setItemTitle, arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_setitemtitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, apply, arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_apply, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, itemCount, arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_itemcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource, itemIdAt, arginfo_appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_itemidat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
