
extern zend_class_entry *appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout);

PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, create);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, wrap);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, destroy);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, nsCollectionViewTransitionLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, setProgress);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, getProgress);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, currentLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, nextLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, updateValue);
PHP_METHOD(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, valueForKey);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_create, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, currentLayout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nextLayout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsCollectionViewTransitionLayoutPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_setprogress, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, progress, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_getprogress, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_currentlayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_nextlayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_updatevalue, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, key, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_valueforkey, 0, 2, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, key, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, create, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, wrap, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, destroy, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, nsCollectionViewTransitionLayout, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, setProgress, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_setprogress, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, getProgress, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_getprogress, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, currentLayout, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_currentlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, nextLayout, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_nextlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, updateValue, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_updatevalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout, valueForKey, arginfo_appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_valueforkey, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
