
extern zend_class_entry *appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem);

PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, colorPicker);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, textColorPicker);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, strokeColorPicker);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, colorPickerWithButtonImage);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, nsColorPickerTouchBarItem);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, setColor);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, getColor);
PHP_METHOD(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, pollAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_colorpicker, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_textcolorpicker, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_strokecolorpicker, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_colorpickerwithbuttonimage, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, image, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_nscolorpickertouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_setcolor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, color, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_getcolor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_pollaction, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, colorPicker, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_colorpicker, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, textColorPicker, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_textcolorpicker, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, strokeColorPicker, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_strokecolorpicker, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, colorPickerWithButtonImage, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_colorpickerwithbuttonimage, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, wrap, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, destroy, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, nsColorPickerTouchBarItem, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_nscolorpickertouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, setColor, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_setcolor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, getColor, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_getcolor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSColorPickerTouchBarItem_NSColorPickerTouchBarItem, pollAction, arginfo_appkit_ns_nscolorpickertouchbaritem_nscolorpickertouchbaritem_pollaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
