#ifndef PHP_APPKIT_NS_TITLEBARACCESSORYVIEWCONTROLLER_H
#define PHP_APPKIT_NS_TITLEBARACCESSORYVIEWCONTROLLER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t ns_titlebaraccessoryviewcontroller_create(void);
uintptr_t ns_titlebaraccessoryviewcontroller_create_with_view(uintptr_t view);
uintptr_t ns_titlebaraccessoryviewcontroller_wrap(void *controller);
void ns_titlebaraccessoryviewcontroller_destroy(uintptr_t controller);
void *ns_titlebaraccessoryviewcontroller_nstitlebaraccessoryviewcontroller(uintptr_t controller);
void ns_titlebaraccessoryviewcontroller_set_view(uintptr_t controller, uintptr_t view);
uintptr_t ns_titlebaraccessoryviewcontroller_view(uintptr_t controller);
void ns_titlebaraccessoryviewcontroller_set_layout_attribute(uintptr_t controller, int attribute);
int ns_titlebaraccessoryviewcontroller_layout_attribute(uintptr_t controller);
void ns_titlebaraccessoryviewcontroller_set_full_screen_min_height(uintptr_t controller, double height);
double ns_titlebaraccessoryviewcontroller_full_screen_min_height(uintptr_t controller);
void ns_titlebaraccessoryviewcontroller_set_hidden(uintptr_t controller, int hidden);
int ns_titlebaraccessoryviewcontroller_is_hidden(uintptr_t controller);
void ns_titlebaraccessoryviewcontroller_set_automatically_adjusts_size(uintptr_t controller, int adjusts);
int ns_titlebaraccessoryviewcontroller_automatically_adjusts_size(uintptr_t controller);

#ifdef __cplusplus
}
#endif

#endif /* PHP_APPKIT_NS_TITLEBARACCESSORYVIEWCONTROLLER_H */
