// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSliderCell;

class NSSliderCell
{
    public static function initTextCell(string string_) -> int
    {
        return nsslidercell_init_text_cell(string_);
    }

    public static function initImageCell(int image) -> int
    {
        return nsslidercell_init_image_cell(image);
    }

    public static function prefersTrackingUntilMouseUp() -> bool
    {
        int r;

        let r = nsslidercell_prefers_tracking_until_mouse_up();

        return r == 1;
    }

    public static function minValue(int handle) -> double
    {
        return nsslidercell_min_value(handle);
    }

    public static function setMinValue(int handle, double minValue) -> void
    {
        nsslidercell_set_min_value(handle, minValue);
    }

    public static function maxValue(int handle) -> double
    {
        return nsslidercell_max_value(handle);
    }

    public static function setMaxValue(int handle, double maxValue) -> void
    {
        nsslidercell_set_max_value(handle, maxValue);
    }

    public static function altIncrementValue(int handle) -> double
    {
        return nsslidercell_alt_increment_value(handle);
    }

    public static function setAltIncrementValue(int handle, double altIncrementValue) -> void
    {
        nsslidercell_set_alt_increment_value(handle, altIncrementValue);
    }

    public static function sliderType(int handle) -> int
    {
        return nsslidercell_slider_type(handle);
    }

    public static function setSliderType(int handle, int sliderType) -> void
    {
        nsslidercell_set_slider_type(handle, sliderType);
    }

    public static function isVertical(int handle) -> bool
    {
        int r;

        let r = nsslidercell_is_vertical(handle);

        return r == 1;
    }

    public static function setVertical(int handle, bool vertical) -> void
    {
        nsslidercell_set_vertical(handle, vertical);
    }

    public static function trackRect(int handle) -> array
    {
        var result;

        let result = nsslidercell_track_rect(handle);

        return result;
    }

    public static function knobThickness(int handle) -> double
    {
        return nsslidercell_knob_thickness(handle);
    }

    public static function knobRectFlipped(int handle, bool flipped) -> array
    {
        var result;

        let result = nsslidercell_knob_rect_flipped(handle, flipped);

        return result;
    }

    public static function barRectFlipped(int handle, bool flipped) -> array
    {
        var result;

        let result = nsslidercell_bar_rect_flipped(handle, flipped);

        return result;
    }

    public static function drawKnobRect(int handle, double x, double y, double width, double height) -> void
    {
        nsslidercell_draw_knob_rect(handle, x, y, width, height);
    }

    public static function drawKnob(int handle) -> void
    {
        nsslidercell_draw_knob(handle);
    }

    public static function drawBarInsideFlipped(int handle, double x, double y, double width, double height, bool flipped) -> void
    {
        nsslidercell_draw_bar_inside_flipped(handle, x, y, width, height, flipped);
    }

    public static function numberOfTickMarks(int handle) -> int
    {
        return nsslidercell_number_of_tick_marks(handle);
    }

    public static function setNumberOfTickMarks(int handle, int numberOfTickMarks) -> void
    {
        nsslidercell_set_number_of_tick_marks(handle, numberOfTickMarks);
    }

    public static function tickMarkPosition(int handle) -> int
    {
        return nsslidercell_tick_mark_position(handle);
    }

    public static function setTickMarkPosition(int handle, int tickMarkPosition) -> void
    {
        nsslidercell_set_tick_mark_position(handle, tickMarkPosition);
    }

    public static function allowsTickMarkValuesOnly(int handle) -> bool
    {
        int r;

        let r = nsslidercell_allows_tick_mark_values_only(handle);

        return r == 1;
    }

    public static function setAllowsTickMarkValuesOnly(int handle, bool allowsTickMarkValuesOnly) -> void
    {
        nsslidercell_set_allows_tick_mark_values_only(handle, allowsTickMarkValuesOnly);
    }

    public static function tickMarkValueAtIndex(int handle, int index) -> double
    {
        return nsslidercell_tick_mark_value_at_index(handle, index);
    }

    public static function rectOfTickMarkAtIndex(int handle, int index) -> array
    {
        var result;

        let result = nsslidercell_rect_of_tick_mark_at_index(handle, index);

        return result;
    }

    public static function indexOfTickMarkAtPoint(int handle, double x, double y) -> int
    {
        return nsslidercell_index_of_tick_mark_at_point(handle, x, y);
    }

    public static function closestTickMarkValueToValue(int handle, double value) -> double
    {
        return nsslidercell_closest_tick_mark_value_to_value(handle, value);
    }

    public static function drawTickMarks(int handle) -> void
    {
        nsslidercell_draw_tick_marks(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (readonly, getter=isVertical) BOOL vertical — NSSliderCellVerticalGetter duplicate of the 10.11 readwrite property
    // @reserved - (void)setTitleCell:(null_unspecified NSCell *)cell API_DEPRECATED
    // @reserved - (null_unspecified id)titleCell API_DEPRECATED
    // @reserved - (void)setTitleColor:(null_unspecified NSColor *)newColor API_DEPRECATED
    // @reserved - (null_unspecified NSColor *)titleColor API_DEPRECATED
    // @reserved - (void)setTitleFont:(null_unspecified NSFont *)fontObj API_DEPRECATED
    // @reserved - (null_unspecified NSFont *)titleFont API_DEPRECATED
    // @reserved - (null_unspecified NSString *)title API_DEPRECATED
    // @reserved - (void)setTitle:(null_unspecified NSString *)string API_DEPRECATED
    // @reserved - (void)setKnobThickness:(CGFloat)thickness API_DEPRECATED
    // @reserved - (void)setImage:(null_unspecified NSImage *)backgroundImage API_DEPRECATED
    // @reserved - (null_unspecified NSImage *)image API_DEPRECATED

}
