
extern zend_class_entry *appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes);

PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, frame);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setFrame);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, size);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setSize);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, alpha);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setAlpha);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, zIndex);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setZIndex);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, isHidden);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setHidden);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, indexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, representedElementCategory);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, representedElementKind);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForItemWithIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForInterItemGapBeforeIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForSupplementaryViewOfKindWithIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForDecorationViewOfKindWithIndexPath);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_frame, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setframe, 0, 5, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_size, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setsize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_alpha, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setalpha, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, alpha, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_zindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setzindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, zIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_ishidden, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_sethidden, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, hidden, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_indexpath, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setindexpath, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_representedelementcategory, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_representedelementkind, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesforitemwithindexpath, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesforinteritemgapbeforeindexpath, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesforsupplementaryviewofkindwithindexpath, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesfordecorationviewofkindwithindexpath, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, decorationViewKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, frame, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_frame, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setFrame, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setframe, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, size, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_size, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setSize, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, alpha, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_alpha, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setAlpha, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setalpha, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, zIndex, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_zindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setZIndex, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setzindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, isHidden, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_ishidden, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setHidden, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_sethidden, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, indexPath, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_indexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, setIndexPath, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_setindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, representedElementCategory, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_representedelementcategory, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, representedElementKind, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_representedelementkind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForItemWithIndexPath, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesforitemwithindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForInterItemGapBeforeIndexPath, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesforinteritemgapbeforeindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForSupplementaryViewOfKindWithIndexPath, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesforsupplementaryviewofkindwithindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutAttributes_NSCollectionViewLayoutAttributes, layoutAttributesForDecorationViewOfKindWithIndexPath, arginfo_appkit_ns_nscollectionviewlayoutattributes_nscollectionviewlayoutattributes_layoutattributesfordecorationviewofkindwithindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
