// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSImageView;

class NSImageView
{
    public static function imageViewWithImage(int image) -> int
    {
        return nsimageview_image_view_with_image(image);
    }

    public static function image(int handle) -> int
    {
        return nsimageview_image(handle);
    }

    public static function setImage(int handle, int image) -> void
    {
        nsimageview_set_image(handle, image);
    }

    public static function isEditable(int handle) -> bool
    {
        int r;

        let r = nsimageview_is_editable(handle);

        return r == 1;
    }

    public static function setEditable(int handle, bool editable) -> void
    {
        nsimageview_set_editable(handle, editable);
    }

    public static function imageAlignment(int handle) -> int
    {
        return nsimageview_image_alignment(handle);
    }

    public static function setImageAlignment(int handle, int imageAlignment) -> void
    {
        nsimageview_set_image_alignment(handle, imageAlignment);
    }

    public static function imageScaling(int handle) -> int
    {
        return nsimageview_image_scaling(handle);
    }

    public static function setImageScaling(int handle, int imageScaling) -> void
    {
        nsimageview_set_image_scaling(handle, imageScaling);
    }

    public static function imageFrameStyle(int handle) -> int
    {
        return nsimageview_image_frame_style(handle);
    }

    public static function setImageFrameStyle(int handle, int imageFrameStyle) -> void
    {
        nsimageview_set_image_frame_style(handle, imageFrameStyle);
    }

    public static function symbolConfiguration(int handle) -> int
    {
        return nsimageview_symbol_configuration(handle);
    }

    public static function setSymbolConfiguration(int handle, int symbolConfiguration) -> void
    {
        nsimageview_set_symbol_configuration(handle, symbolConfiguration);
    }

    public static function contentTintColor(int handle) -> int
    {
        return nsimageview_content_tint_color(handle);
    }

    public static function setContentTintColor(int handle, int contentTintColor) -> void
    {
        nsimageview_set_content_tint_color(handle, contentTintColor);
    }

    public static function animates(int handle) -> bool
    {
        int r;

        let r = nsimageview_animates(handle);

        return r == 1;
    }

    public static function setAnimates(int handle, bool animates) -> void
    {
        nsimageview_set_animates(handle, animates);
    }

    public static function allowsCutCopyPaste(int handle) -> bool
    {
        int r;

        let r = nsimageview_allows_cut_copy_paste(handle);

        return r == 1;
    }

    public static function setAllowsCutCopyPaste(int handle, bool allowsCutCopyPaste) -> void
    {
        nsimageview_set_allows_cut_copy_paste(handle, allowsCutCopyPaste);
    }

    public static function defaultPreferredImageDynamicRange() -> int
    {
        return nsimageview_default_preferred_image_dynamic_range();
    }

    public static function setDefaultPreferredImageDynamicRange(int defaultPreferredImageDynamicRange) -> void
    {
        nsimageview_set_default_preferred_image_dynamic_range(defaultPreferredImageDynamicRange);
    }

    public static function preferredImageDynamicRange(int handle) -> int
    {
        return nsimageview_preferred_image_dynamic_range(handle);
    }

    public static function setPreferredImageDynamicRange(int handle, int preferredImageDynamicRange) -> void
    {
        nsimageview_set_preferred_image_dynamic_range(handle, preferredImageDynamicRange);
    }

    public static function imageDynamicRange(int handle) -> int
    {
        return nsimageview_image_dynamic_range(handle);
    }

    public static function addSymbolEffect(int handle, int symbolEffect) -> void
    {
        nsimageview_add_symbol_effect(handle, symbolEffect);
    }

    public static function addSymbolEffectOptions(int handle, int symbolEffect, int options) -> void
    {
        nsimageview_add_symbol_effect_options(handle, symbolEffect, options);
    }

    public static function addSymbolEffectOptionsAnimated(int handle, int symbolEffect, int options, bool animated) -> void
    {
        nsimageview_add_symbol_effect_options_animated(handle, symbolEffect, options, animated);
    }

    public static function removeSymbolEffectOfType(int handle, int symbolEffect) -> void
    {
        nsimageview_remove_symbol_effect_of_type(handle, symbolEffect);
    }

    public static function removeSymbolEffectOfTypeOptions(int handle, int symbolEffect, int options) -> void
    {
        nsimageview_remove_symbol_effect_of_type_options(handle, symbolEffect, options);
    }

    public static function removeSymbolEffectOfTypeOptionsAnimated(int handle, int symbolEffect, int options, bool animated) -> void
    {
        nsimageview_remove_symbol_effect_of_type_options_animated(handle, symbolEffect, options, animated);
    }

    public static function removeAllSymbolEffects(int handle) -> void
    {
        nsimageview_remove_all_symbol_effects(handle);
    }

    public static function removeAllSymbolEffectsWithOptions(int handle, int options) -> void
    {
        nsimageview_remove_all_symbol_effects_with_options(handle, options);
    }

    public static function removeAllSymbolEffectsWithOptionsAnimated(int handle, int options, bool animated) -> void
    {
        nsimageview_remove_all_symbol_effects_with_options_animated(handle, options, animated);
    }

    public static function setSymbolImageWithContentTransition(int handle, int symbolImage, int transition) -> void
    {
        nsimageview_set_symbol_image_with_content_transition(handle, symbolImage, transition);
    }

    public static function setSymbolImageWithContentTransitionOptions(int handle, int symbolImage, int transition, int options) -> void
    {
        nsimageview_set_symbol_image_with_content_transition_options(handle, symbolImage, transition, options);
    }
}
