
extern zend_class_entry *appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem);

PHP_METHOD(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, create);
PHP_METHOD(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, nsSharingServicePickerTouchBarItem);
PHP_METHOD(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, setShareStrings);
PHP_METHOD(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, pollShareRequest);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_setsharestrings, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, strings, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_pollsharerequest, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, create, arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, wrap, arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, destroy, arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, nsSharingServicePickerTouchBarItem, arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, setShareStrings, arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_setsharestrings, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerTouchBarItem_NSSharingServicePickerTouchBarItem, pollShareRequest, arginfo_appkit_ns_nssharingservicepickertouchbaritem_nssharingservicepickertouchbaritem_pollsharerequest, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
