// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\GC\GCControllerDirectionPad;

class GCControllerDirectionPad
{
    public static function xAxis(int handle) -> int
    {
        return gccontrollerdirectionpad_x_axis(handle);
    }

    public static function yAxis(int handle) -> int
    {
        return gccontrollerdirectionpad_y_axis(handle);
    }

    public static function up(int handle) -> int
    {
        return gccontrollerdirectionpad_up(handle);
    }

    public static function down(int handle) -> int
    {
        return gccontrollerdirectionpad_down(handle);
    }

    public static function left(int handle) -> int
    {
        return gccontrollerdirectionpad_left(handle);
    }

    public static function right(int handle) -> int
    {
        return gccontrollerdirectionpad_right(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (nonatomic, copy, nullable) GCControllerDirectionPadValueChangedHandler valueChangedHandler — getter (block)
    // @reserved @property (nonatomic, copy, nullable) GCControllerDirectionPadValueChangedHandler valueChangedHandler — setter (block)
    // @reserved - (void)setValueForXAxis:(float)xAxis yAxis:(float)yAxis — snapshot write, not bound in this slice

}
