// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSToolbar;

class NSToolbar
{
    public static function initWithIdentifier(string identifier) -> int
    {
        return nstoolbar_init_with_identifier(identifier);
    }

    public static function init() -> int
    {
        return nstoolbar_init();
    }

    public static function insertItemWithItemIdentifierAtIndex(int handle, string itemIdentifier, int index) -> void
    {
        nstoolbar_insert_item_with_item_identifier_at_index(handle, itemIdentifier, index);
    }

    public static function removeItemAtIndex(int handle, int index) -> void
    {
        nstoolbar_remove_item_at_index(handle, index);
    }

    public static function removeItemWithItemIdentifier(int handle, string itemIdentifier) -> void
    {
        nstoolbar_remove_item_with_item_identifier(handle, itemIdentifier);
    }

    public static function delegate(int handle) -> int
    {
        return nstoolbar_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nstoolbar_set_delegate(handle, delegate);
    }

    public static function isVisible(int handle) -> bool
    {
        int r;

        let r = nstoolbar_is_visible(handle);

        return r == 1;
    }

    public static function setVisible(int handle, bool visible) -> void
    {
        nstoolbar_set_visible(handle, visible);
    }

    public static function runCustomizationPalette(int handle, int sender) -> void
    {
        nstoolbar_run_customization_palette(handle, sender);
    }

    public static function customizationPaletteIsRunning(int handle) -> bool
    {
        int r;

        let r = nstoolbar_customization_palette_is_running(handle);

        return r == 1;
    }

    public static function displayMode(int handle) -> int
    {
        return nstoolbar_display_mode(handle);
    }

    public static function setDisplayMode(int handle, int displayMode) -> void
    {
        nstoolbar_set_display_mode(handle, displayMode);
    }

    public static function selectedItemIdentifier(int handle) -> var
    {
        var result;

        let result = nstoolbar_selected_item_identifier(handle);

        return result;
    }

    public static function setSelectedItemIdentifier(int handle, var selectedItemIdentifier) -> void
    {
        nstoolbar_set_selected_item_identifier(handle, selectedItemIdentifier);
    }

    public static function allowsUserCustomization(int handle) -> bool
    {
        int r;

        let r = nstoolbar_allows_user_customization(handle);

        return r == 1;
    }

    public static function setAllowsUserCustomization(int handle, bool allowsUserCustomization) -> void
    {
        nstoolbar_set_allows_user_customization(handle, allowsUserCustomization);
    }

    public static function allowsDisplayModeCustomization(int handle) -> bool
    {
        int r;

        let r = nstoolbar_allows_display_mode_customization(handle);

        return r == 1;
    }

    public static function setAllowsDisplayModeCustomization(int handle, bool allowsDisplayModeCustomization) -> void
    {
        nstoolbar_set_allows_display_mode_customization(handle, allowsDisplayModeCustomization);
    }

    public static function identifier(int handle) -> string
    {
        var result;

        let result = nstoolbar_identifier(handle);

        return result;
    }

    public static function items(int handle) -> array
    {
        var result;

        let result = nstoolbar_items(handle);

        return result;
    }

    public static function visibleItems(int handle) -> array
    {
        var result;

        let result = nstoolbar_visible_items(handle);

        return result;
    }

    public static function itemIdentifiers(int handle) -> array
    {
        var result;

        let result = nstoolbar_item_identifiers(handle);

        return result;
    }

    public static function setItemIdentifiers(int handle, array itemIdentifiers) -> void
    {
        nstoolbar_set_item_identifiers(handle, itemIdentifiers);
    }

    public static function centeredItemIdentifiers(int handle) -> array
    {
        var result;

        let result = nstoolbar_centered_item_identifiers(handle);

        return result;
    }

    public static function setCenteredItemIdentifiers(int handle, array centeredItemIdentifiers) -> void
    {
        nstoolbar_set_centered_item_identifiers(handle, centeredItemIdentifiers);
    }

    public static function autosavesConfiguration(int handle) -> bool
    {
        int r;

        let r = nstoolbar_autosaves_configuration(handle);

        return r == 1;
    }

    public static function setAutosavesConfiguration(int handle, bool autosavesConfiguration) -> void
    {
        nstoolbar_set_autosaves_configuration(handle, autosavesConfiguration);
    }

    public static function validateVisibleItems(int handle) -> void
    {
        nstoolbar_validate_visible_items(handle);
    }

    public static function allowsExtensionItems(int handle) -> bool
    {
        int r;

        let r = nstoolbar_allows_extension_items(handle);

        return r == 1;
    }

    public static function setAllowsExtensionItems(int handle, bool allowsExtensionItems) -> void
    {
        nstoolbar_set_allows_extension_items(handle, allowsExtensionItems);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property NSToolbarSizeMode sizeMode API_DEPRECATED — getter
    // @reserved @property NSToolbarSizeMode sizeMode API_DEPRECATED — setter
    // @reserved @property (nullable, copy) NSToolbarItemIdentifier centeredItemIdentifier API_DEPRECATED — getter
    // @reserved @property (nullable, copy) NSToolbarItemIdentifier centeredItemIdentifier API_DEPRECATED — setter
    // @reserved @property (nullable, strong) NSView *fullScreenAccessoryView API_DEPRECATED — getter
    // @reserved @property (nullable, strong) NSView *fullScreenAccessoryView API_DEPRECATED — setter
    // @reserved @property CGFloat fullScreenAccessoryViewMinHeight API_DEPRECATED — getter
    // @reserved @property CGFloat fullScreenAccessoryViewMinHeight API_DEPRECATED — setter
    // @reserved @property CGFloat fullScreenAccessoryViewMaxHeight API_DEPRECATED — getter
    // @reserved @property CGFloat fullScreenAccessoryViewMaxHeight API_DEPRECATED — setter
    // @reserved @property BOOL showsBaselineSeparator API_DEPRECATED — getter
    // @reserved @property BOOL showsBaselineSeparator API_DEPRECATED — setter
    // @reserved @property (readonly, copy) NSDictionary<NSString *, id> *configurationDictionary API_DEPRECATED
    // @reserved - (void)setConfigurationFromDictionary:(NSDictionary<NSString *, id> *)configDict API_DEPRECATED

}
