
extern zend_class_entry *appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController);

PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, shared);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, create);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, createWithInitialValues);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, wrap);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, destroy);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, nsUserDefaultsController);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, discardEditing);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, commitEditing);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, isEditing);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, defaults);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, setInitialValues);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, initialValues);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, setAppliesImmediately);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, appliesImmediately);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, hasUnappliedChanges);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, values);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, revert);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, save);
PHP_METHOD(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, revertToInitialValues);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_shared, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_createwithinitialvalues, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dictionaryHandle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsUserDefaultsControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_nsuserdefaultscontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_discardediting, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_commitediting, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_isediting, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_defaults, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_setinitialvalues, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dictionaryHandle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_initialvalues, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_setappliesimmediately, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_appliesimmediately, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_hasunappliedchanges, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_values, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_revert, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_save, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_reverttoinitialvalues, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_method_entry) {
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, shared, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_shared, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, create, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, createWithInitialValues, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_createwithinitialvalues, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, wrap, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, destroy, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, nsUserDefaultsController, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_nsuserdefaultscontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, discardEditing, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_discardediting, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, commitEditing, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_commitediting, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, isEditing, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_isediting, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, defaults, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_defaults, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, setInitialValues, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_setinitialvalues, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, initialValues, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_initialvalues, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, setAppliesImmediately, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_setappliesimmediately, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, appliesImmediately, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_appliesimmediately, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, hasUnappliedChanges, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_hasunappliedchanges, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, values, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_values, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, revert, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_revert, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, save, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_save, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSUserDefaultsController_NSUserDefaultsController, revertToInitialValues, arginfo_appkit_ns_nsuserdefaultscontroller_nsuserdefaultscontroller_reverttoinitialvalues, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
