
extern zend_class_entry *appkit_ns_nsarraycontroller_nsarraycontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSArrayController_NSArrayController);

PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, create);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, wrap);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, destroy);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, nsArrayController);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, discardEditing);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, commitEditing);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, isEditing);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setContent);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, content);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setEditable);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, isEditable);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, canAdd);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, canRemove);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, prepareContent);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, newObject);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, selectedObjectsCount);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, selectedObjectAt);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, rearrangeObjects);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setAutomaticallyRearrangesObjects);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, automaticallyRearrangesObjects);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, automaticRearrangementKeyPathsCount);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, automaticRearrangementKeyPathAt);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, didChangeArrangementCriteria);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setClearsFilterPredicateOnInsertion);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, clearsFilterPredicateOnInsertion);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, arrangedObjectsCount);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, arrangedObjectAt);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setAvoidsEmptySelection);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, avoidsEmptySelection);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setPreservesSelection);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, preservesSelection);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setSelectsInsertedObjects);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, selectsInsertedObjects);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setAlwaysUsesMultipleValuesMarker);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, alwaysUsesMultipleValuesMarker);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setSelectionIndex);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, selectionIndex);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, setSelectionIndexes);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, selectionIndexesCount);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, selectionIndexAtOrdinal);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, canInsert);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, canSelectNext);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, canSelectPrevious);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, insertObjectAtArrangedObjectIndex);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, removeObjectAtArrangedObjectIndex);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, addObject);
PHP_METHOD(AppKit_NS_NSArrayController_NSArrayController, removeObject);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsArrayControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_nsarraycontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_discardediting, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_commitediting, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_isediting, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setcontent, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, contentPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_content, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_seteditable, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_iseditable, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canadd, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canremove, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_preparecontent, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_newobject, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectedobjectscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectedobjectat, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_rearrangeobjects, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setautomaticallyrearrangesobjects, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_automaticallyrearrangesobjects, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_automaticrearrangementkeypathscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_automaticrearrangementkeypathat, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_didchangearrangementcriteria, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setclearsfilterpredicateoninsertion, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_clearsfilterpredicateoninsertion, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_arrangedobjectscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_arrangedobjectat, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setavoidsemptyselection, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_avoidsemptyselection, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setpreservesselection, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_preservesselection, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setselectsinsertedobjects, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectsinsertedobjects, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setalwaysusesmultiplevaluesmarker, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_alwaysusesmultiplevaluesmarker, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setselectionindex, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectionindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setselectionindexes, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, indexes, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectionindexescount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectionindexatordinal, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ordinal, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_caninsert, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canselectnext, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canselectprevious, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_insertobjectatarrangedobjectindex, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, objectPtr, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_removeobjectatarrangedobjectindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_addobject, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, objectPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_removeobject, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, objectPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsarraycontroller_nsarraycontroller_method_entry) {
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, create, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, wrap, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, destroy, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, nsArrayController, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_nsarraycontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, discardEditing, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_discardediting, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, commitEditing, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_commitediting, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, isEditing, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_isediting, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setContent, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setcontent, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, content, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_content, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setEditable, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_seteditable, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, isEditable, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_iseditable, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, canAdd, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canadd, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, canRemove, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canremove, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, prepareContent, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_preparecontent, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, newObject, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_newobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, selectedObjectsCount, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectedobjectscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, selectedObjectAt, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectedobjectat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, rearrangeObjects, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_rearrangeobjects, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setAutomaticallyRearrangesObjects, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setautomaticallyrearrangesobjects, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, automaticallyRearrangesObjects, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_automaticallyrearrangesobjects, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, automaticRearrangementKeyPathsCount, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_automaticrearrangementkeypathscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, automaticRearrangementKeyPathAt, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_automaticrearrangementkeypathat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, didChangeArrangementCriteria, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_didchangearrangementcriteria, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setClearsFilterPredicateOnInsertion, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setclearsfilterpredicateoninsertion, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, clearsFilterPredicateOnInsertion, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_clearsfilterpredicateoninsertion, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, arrangedObjectsCount, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_arrangedobjectscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, arrangedObjectAt, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_arrangedobjectat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setAvoidsEmptySelection, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setavoidsemptyselection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, avoidsEmptySelection, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_avoidsemptyselection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setPreservesSelection, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setpreservesselection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, preservesSelection, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_preservesselection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setSelectsInsertedObjects, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setselectsinsertedobjects, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, selectsInsertedObjects, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectsinsertedobjects, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setAlwaysUsesMultipleValuesMarker, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setalwaysusesmultiplevaluesmarker, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, alwaysUsesMultipleValuesMarker, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_alwaysusesmultiplevaluesmarker, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setSelectionIndex, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setselectionindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, selectionIndex, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectionindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, setSelectionIndexes, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_setselectionindexes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, selectionIndexesCount, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectionindexescount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, selectionIndexAtOrdinal, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_selectionindexatordinal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, canInsert, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_caninsert, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, canSelectNext, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canselectnext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, canSelectPrevious, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_canselectprevious, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, insertObjectAtArrangedObjectIndex, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_insertobjectatarrangedobjectindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, removeObjectAtArrangedObjectIndex, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_removeobjectatarrangedobjectindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, addObject, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_addobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSArrayController_NSArrayController, removeObject, arginfo_appkit_ns_nsarraycontroller_nsarraycontroller_removeobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
