
extern zend_class_entry *appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem);

PHP_METHOD(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, init);
PHP_METHOD(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, indexPathBeforeUpdate);
PHP_METHOD(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, indexPathAfterUpdate);
PHP_METHOD(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, updateAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_init, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_indexpathbeforeupdate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_indexpathafterupdate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_updateaction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, init, arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_init, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, indexPathBeforeUpdate, arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_indexpathbeforeupdate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, indexPathAfterUpdate, arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_indexpathafterupdate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewUpdateItem_NSCollectionViewUpdateItem, updateAction, arginfo_appkit_ns_nscollectionviewupdateitem_nscollectionviewupdateitem_updateaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
