
extern zend_class_entry *appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem);

PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, buttonWithTitle);
PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, buttonWithImage);
PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, nsButtonTouchBarItem);
PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, setTitle);
PHP_METHOD(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, pollAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_buttonwithtitle, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_buttonwithimage, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, image, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_nsbuttontouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_settitle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_pollaction, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, buttonWithTitle, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_buttonwithtitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, buttonWithImage, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_buttonwithimage, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, wrap, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, destroy, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, nsButtonTouchBarItem, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_nsbuttontouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, setTitle, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_settitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSButtonTouchBarItem_NSButtonTouchBarItem, pollAction, arginfo_appkit_ns_nsbuttontouchbaritem_nsbuttontouchbaritem_pollaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
