// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\GC\GCExtendedGamepad;

class GCExtendedGamepad
{
    public static function controller(int handle) -> int
    {
        return gcextendedgamepad_controller(handle);
    }

    public static function dpad(int handle) -> int
    {
        return gcextendedgamepad_dpad(handle);
    }

    public static function buttonA(int handle) -> int
    {
        return gcextendedgamepad_button_a(handle);
    }

    public static function buttonB(int handle) -> int
    {
        return gcextendedgamepad_button_b(handle);
    }

    public static function buttonX(int handle) -> int
    {
        return gcextendedgamepad_button_x(handle);
    }

    public static function buttonY(int handle) -> int
    {
        return gcextendedgamepad_button_y(handle);
    }

    public static function buttonMenu(int handle) -> int
    {
        return gcextendedgamepad_button_menu(handle);
    }

    public static function buttonOptions(int handle) -> int
    {
        return gcextendedgamepad_button_options(handle);
    }

    public static function buttonHome(int handle) -> int
    {
        return gcextendedgamepad_button_home(handle);
    }

    public static function leftThumbstick(int handle) -> int
    {
        return gcextendedgamepad_left_thumbstick(handle);
    }

    public static function rightThumbstick(int handle) -> int
    {
        return gcextendedgamepad_right_thumbstick(handle);
    }

    public static function leftShoulder(int handle) -> int
    {
        return gcextendedgamepad_left_shoulder(handle);
    }

    public static function rightShoulder(int handle) -> int
    {
        return gcextendedgamepad_right_shoulder(handle);
    }

    public static function leftTrigger(int handle) -> int
    {
        return gcextendedgamepad_left_trigger(handle);
    }

    public static function rightTrigger(int handle) -> int
    {
        return gcextendedgamepad_right_trigger(handle);
    }

    public static function leftThumbstickButton(int handle) -> int
    {
        return gcextendedgamepad_left_thumbstick_button(handle);
    }

    public static function rightThumbstickButton(int handle) -> int
    {
        return gcextendedgamepad_right_thumbstick_button(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (nonatomic, copy, nullable) GCExtendedGamepadValueChangedHandler valueChangedHandler — getter (block)
    // @reserved @property (nonatomic, copy, nullable) GCExtendedGamepadValueChangedHandler valueChangedHandler — setter (block)
    // @reserved - (GCExtendedGamepadSnapshot *)saveSnapshot API_DEPRECATED — deprecated
    // @reserved - (void)setStateFromExtendedGamepad:(GCExtendedGamepad *)extendedGamepad — snapshot write, not bound in this slice

}
