
extern zend_class_entry *appkit_ns_nsdocumentcontroller_nsdocumentcontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSDocumentController_NSDocumentController);

PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, shared);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, create);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, wrap);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, destroy);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, nsDocumentController);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, documentsCount);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, documentAt);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, currentDocument);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, currentDirectory);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, documentForURL);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, documentForWindow);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, addDocument);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, removeDocument);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, defaultType);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, openUntitledDocumentAndDisplay);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, hasEditedDocuments);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, documentClassNamesCount);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, documentClassNameAt);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, displayNameForType);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, recentDocumentURLsCount);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, recentDocumentURLAt);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, noteNewRecentDocument);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, noteNewRecentDocumentURL);
PHP_METHOD(AppKit_NS_NSDocumentController_NSDocumentController, clearRecentDocuments);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_shared, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsDocumentControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_nsdocumentcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentat, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_currentdocument, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_currentdirectory, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentforurl, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, url, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentforwindow, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, window, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_adddocument, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_removedocument, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_defaulttype, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_openuntitleddocumentanddisplay, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, displayDocument, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_hasediteddocuments, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentclassnamescount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentclassnameat, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_displaynamefortype, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, typeName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_recentdocumenturlscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_recentdocumenturlat, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_notenewrecentdocument, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, document, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_notenewrecentdocumenturl, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, url, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_clearrecentdocuments, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsdocumentcontroller_nsdocumentcontroller_method_entry) {
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, shared, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_shared, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, create, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, wrap, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, destroy, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, nsDocumentController, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_nsdocumentcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, documentsCount, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, documentAt, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, currentDocument, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_currentdocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, currentDirectory, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_currentdirectory, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, documentForURL, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentforurl, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, documentForWindow, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentforwindow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, addDocument, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_adddocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, removeDocument, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_removedocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, defaultType, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_defaulttype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, openUntitledDocumentAndDisplay, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_openuntitleddocumentanddisplay, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, hasEditedDocuments, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_hasediteddocuments, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, documentClassNamesCount, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentclassnamescount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, documentClassNameAt, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_documentclassnameat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, displayNameForType, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_displaynamefortype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, recentDocumentURLsCount, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_recentdocumenturlscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, recentDocumentURLAt, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_recentdocumenturlat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, noteNewRecentDocument, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_notenewrecentdocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, noteNewRecentDocumentURL, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_notenewrecentdocumenturl, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSDocumentController_NSDocumentController, clearRecentDocuments, arginfo_appkit_ns_nsdocumentcontroller_nsdocumentcontroller_clearrecentdocuments, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
