// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSOpenPanel;

class NSOpenPanel
{
    public static function openPanel() -> int
    {
        return nsopenpanel_open_panel();
    }

    public static function URLs(int handle) -> array
    {
        var result;

        let result = nsopenpanel_urls(handle);

        return result;
    }

    public static function resolvesAliases(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_resolves_aliases(handle);

        return r == 1;
    }

    public static function setResolvesAliases(int handle, bool resolvesAliases) -> void
    {
        nsopenpanel_set_resolves_aliases(handle, resolvesAliases);
    }

    public static function canChooseDirectories(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_can_choose_directories(handle);

        return r == 1;
    }

    public static function setCanChooseDirectories(int handle, bool canChooseDirectories) -> void
    {
        nsopenpanel_set_can_choose_directories(handle, canChooseDirectories);
    }

    public static function allowsMultipleSelection(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_allows_multiple_selection(handle);

        return r == 1;
    }

    public static function setAllowsMultipleSelection(int handle, bool allowsMultipleSelection) -> void
    {
        nsopenpanel_set_allows_multiple_selection(handle, allowsMultipleSelection);
    }

    public static function canChooseFiles(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_can_choose_files(handle);

        return r == 1;
    }

    public static function setCanChooseFiles(int handle, bool canChooseFiles) -> void
    {
        nsopenpanel_set_can_choose_files(handle, canChooseFiles);
    }

    public static function canResolveUbiquitousConflicts(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_can_resolve_ubiquitous_conflicts(handle);

        return r == 1;
    }

    public static function setCanResolveUbiquitousConflicts(int handle, bool canResolveUbiquitousConflicts) -> void
    {
        nsopenpanel_set_can_resolve_ubiquitous_conflicts(handle, canResolveUbiquitousConflicts);
    }

    public static function canDownloadUbiquitousContents(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_can_download_ubiquitous_contents(handle);

        return r == 1;
    }

    public static function setCanDownloadUbiquitousContents(int handle, bool canDownloadUbiquitousContents) -> void
    {
        nsopenpanel_set_can_download_ubiquitous_contents(handle, canDownloadUbiquitousContents);
    }

    public static function isAccessoryViewDisclosed(int handle) -> bool
    {
        int r;

        let r = nsopenpanel_is_accessory_view_disclosed(handle);

        return r == 1;
    }

    public static function setAccessoryViewDisclosed(int handle, bool accessoryViewDisclosed) -> void
    {
        nsopenpanel_set_accessory_view_disclosed(handle, accessoryViewDisclosed);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property BOOL showsContentTypes NS_UNAVAILABLE — getter
    // @reserved @property BOOL showsContentTypes NS_UNAVAILABLE — setter
    // @reserved - (NSArray *)filenames API_DEPRECATED
    // @reserved - (void)beginSheetForDirectory:file:types:modalForWindow:modalDelegate:didEndSelector:contextInfo: API_DEPRECATED
    // @reserved - (void)beginForDirectory:file:types:modelessDelegate:didEndSelector:contextInfo: API_DEPRECATED
    // @reserved - (NSInteger)runModalForDirectory:(nullable NSString *)path file:(nullable NSString *)name types:(nullable NSArray *)fileTypes API_DEPRECATED
    // @reserved - (NSInteger)runModalForTypes:(nullable NSArray *)fileTypes API_DEPRECATED

}
