<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NscellPrefersTrackingUntilMouseUpOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'nscell_prefers_tracking_until_mouse_up' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/ns-cell');


        return new CompiledExpression(
            'int',
            'ns_nscell_prefers_tracking_until_mouse_up(' . ')',
            $expression
        );
    }
}
