<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NscollectionviewflowlayoutSectionHeadersPinToVisibleBoundsOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 1) {
            throw new CompilerException("'nscollectionviewflowlayout_section_headers_pin_to_visible_bounds' requires exactly one parameter", $expression);
        }

        $context->headersManager->add('src/ns-collectionviewflowlayout');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        return new CompiledExpression(
            'int',
            'ns_nscollectionviewflowlayout_section_headers_pin_to_visible_bounds(' . $resolvedParams[0] . ')',
            $expression
        );
    }
}
