<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NscollectionviewlayoutPrepareForAnimatedBoundsChangeOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 5) {
            throw new CompilerException("'nscollectionviewlayout_prepare_for_animated_bounds_change' requires exactly 5 parameters", $expression);
        }

        $context->headersManager->add('src/ns-collectionviewlayout');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('ns_nscollectionviewlayout_prepare_for_animated_bounds_change(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
