<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NscolorwellDrawWellInsideOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 5) {
            throw new CompilerException("'nscolorwell_draw_well_inside' requires exactly 5 parameters", $expression);
        }

        $context->headersManager->add('src/ns-colorwell');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('ns_nscolorwell_draw_well_inside(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
