<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NseventDoubleClickIntervalOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'nsevent_double_click_interval' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/ns-event');


        return new CompiledExpression(
            'double',
            'ns_nsevent_double_click_interval(' . ')',
            $expression
        );
    }
}
