<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NslayoutmanagerSetBoundsRectForTextBlockGlyphRangeOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 8) {
            throw new CompilerException("'nslayoutmanager_set_bounds_rect_for_text_block_glyph_range' requires exactly 8 parameters", $expression);
        }

        $context->headersManager->add('src/ns-layoutmanager');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('ns_nslayoutmanager_set_bounds_rect_for_text_block_glyph_range(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ', ' . $resolvedParams[6] . ', ' . $resolvedParams[7] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
