<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NsresponderPresentErrorModalForWindowDelegateDidPresentSelectorContextInfoOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 6) {
            throw new CompilerException("'nsresponder_present_error_modal_for_window_delegate_did_present_selector_context_info' requires exactly 6 parameters", $expression);
        }

        $context->headersManager->add('src/ns-responder');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('ns_nsresponder_present_error_modal_for_window_delegate_did_present_selector_context_info(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
