<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NstableheadercellDrawSortIndicatorWithFrameInViewAscendingPriorityOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 8) {
            throw new CompilerException("'nstableheadercell_draw_sort_indicator_with_frame_in_view_ascending_priority' requires exactly 8 parameters", $expression);
        }

        $context->headersManager->add('src/ns-tableheadercell');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('ns_nstableheadercell_draw_sort_indicator_with_frame_in_view_ascending_priority(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ', ' . $resolvedParams[4] . ', ' . $resolvedParams[5] . ', ' . $resolvedParams[6] . ', ' . $resolvedParams[7] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
