<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class NstableviewNoteHeightOfRowsWithIndexesChangedOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 2) {
            throw new CompilerException("'nstableview_note_height_of_rows_with_indexes_changed' requires exactly 2 parameters", $expression);
        }

        $context->headersManager->add('src/ns-tableview');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('ns_nstableview_note_height_of_rows_with_indexes_changed(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
