// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSNotificationCenter;

class NSNotificationCenter
{
    public static function defaultCenter() -> int
    {
        return nsnotificationcenter_default_center();
    }

    public static function postNotification(int handle, int notification) -> void
    {
        nsnotificationcenter_post_notification(handle, notification);
    }

    public static function postNotificationNameObject(int handle, string name, int object_) -> void
    {
        nsnotificationcenter_post_notification_name_object(handle, name, object_);
    }

    public static function postNotificationNameObjectUserInfo(int handle, string name, int object_, var userInfo) -> void
    {
        nsnotificationcenter_post_notification_name_object_user_info(handle, name, object_, userInfo);
    }

    public static function removeObserver(int handle, int observer) -> void
    {
        nsnotificationcenter_remove_observer(handle, observer);
    }

    public static function removeObserverNameObject(int handle, int observer, var name, int object_) -> void
    {
        nsnotificationcenter_remove_observer_name_object(handle, observer, name, object_);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (void)addObserver:(id)observer selector:(SEL)aSelector name:(nullable NSNotificationName)aName object:(nullable id)anObject — observe lives in Bridge
    // @reserved - (id <NSObject>)addObserverForName:(nullable NSNotificationName)name object:(nullable id)obj queue:(nullable NSOperationQueue *)queue usingBlock:(void (^)(NSNotification *notification))block — block; observe lives in Bridge

}
