
extern zend_class_entry *appkit_ns_nscollectionviewdatasource_nscollectionviewdatasource_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewDataSource_NSCollectionViewDataSource);

PHP_METHOD(AppKit_NS_NSCollectionViewDataSource_NSCollectionViewDataSource, attach);
PHP_METHOD(AppKit_NS_NSCollectionViewDataSource_NSCollectionViewDataSource, poll);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdatasource_nscollectionviewdatasource_attach, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewdatasource_nscollectionviewdatasource_poll, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewdatasource_nscollectionviewdatasource_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewDataSource_NSCollectionViewDataSource, attach, arginfo_appkit_ns_nscollectionviewdatasource_nscollectionviewdatasource_attach, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewDataSource_NSCollectionViewDataSource, poll, arginfo_appkit_ns_nscollectionviewdatasource_nscollectionviewdatasource_poll, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
