// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSOpenGLView;

class NSOpenGLView
{
    public static function defaultPixelFormat() -> int
    {
        return nsopenglview_default_pixel_format();
    }

    public static function initWithFramePixelFormat(double x, double y, double width, double height, int format) -> int
    {
        return nsopenglview_init_with_frame_pixel_format(x, y, width, height, format);
    }

    public static function openGLContext(int handle) -> int
    {
        return nsopenglview_open_gl_context(handle);
    }

    public static function setOpenGLContext(int handle, int openGLContext) -> void
    {
        nsopenglview_set_open_gl_context(handle, openGLContext);
    }

    public static function clearGLContext(int handle) -> void
    {
        nsopenglview_clear_gl_context(handle);
    }

    public static function update(int handle) -> void
    {
        nsopenglview_update(handle);
    }

    public static function reshape(int handle) -> void
    {
        nsopenglview_reshape(handle);
    }

    public static function pixelFormat(int handle) -> int
    {
        return nsopenglview_pixel_format(handle);
    }

    public static function setPixelFormat(int handle, int pixelFormat) -> void
    {
        nsopenglview_set_pixel_format(handle, pixelFormat);
    }

    public static function prepareOpenGL(int handle) -> void
    {
        nsopenglview_prepare_open_gl(handle);
    }

    public static function wantsBestResolutionOpenGLSurface(int handle) -> bool
    {
        int r;

        let r = nsopenglview_wants_best_resolution_open_gl_surface(handle);

        return r == 1;
    }

    public static function setWantsBestResolutionOpenGLSurface(int handle, bool wantsBestResolutionOpenGLSurface) -> void
    {
        nsopenglview_set_wants_best_resolution_open_gl_surface(handle, wantsBestResolutionOpenGLSurface);
    }

    public static function wantsExtendedDynamicRangeOpenGLSurface(int handle) -> bool
    {
        int r;

        let r = nsopenglview_wants_extended_dynamic_range_open_gl_surface(handle);

        return r == 1;
    }

    public static function setWantsExtendedDynamicRangeOpenGLSurface(int handle, bool wantsExtendedDynamicRangeOpenGLSurface) -> void
    {
        nsopenglview_set_wants_extended_dynamic_range_open_gl_surface(handle, wantsExtendedDynamicRangeOpenGLSurface);
    }
}
