
extern zend_class_entry *appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext);

PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, init);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateEverything);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateDataSourceCounts);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateItemsAtIndexPaths);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateSupplementaryElementsOfKindAtIndexPaths);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateDecorationElementsOfKindAtIndexPaths);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidatedItemIndexPaths);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidatedSupplementaryIndexPaths);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidatedDecorationIndexPaths);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, contentOffsetAdjustment);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, setContentOffsetAdjustment);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, contentSizeAdjustment);
PHP_METHOD(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, setContentSizeAdjustment);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_init, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateeverything, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatedatasourcecounts, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateitemsatindexpaths, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, indexPaths, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatesupplementaryelementsofkindatindexpaths, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_ARRAY_INFO(0, indexPaths, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatedecorationelementsofkindatindexpaths, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_ARRAY_INFO(0, indexPaths, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateditemindexpaths, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatedsupplementaryindexpaths, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateddecorationindexpaths, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_contentoffsetadjustment, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_setcontentoffsetadjustment, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_contentsizeadjustment, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_setcontentsizeadjustment, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, init, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_init, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateEverything, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateeverything, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateDataSourceCounts, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatedatasourcecounts, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateItemsAtIndexPaths, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateitemsatindexpaths, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateSupplementaryElementsOfKindAtIndexPaths, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatesupplementaryelementsofkindatindexpaths, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidateDecorationElementsOfKindAtIndexPaths, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatedecorationelementsofkindatindexpaths, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidatedItemIndexPaths, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateditemindexpaths, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidatedSupplementaryIndexPaths, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidatedsupplementaryindexpaths, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, invalidatedDecorationIndexPaths, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_invalidateddecorationindexpaths, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, contentOffsetAdjustment, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_contentoffsetadjustment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, setContentOffsetAdjustment, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_setcontentoffsetadjustment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, contentSizeAdjustment, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_contentsizeadjustment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayoutInvalidationContext_NSCollectionViewLayoutInvalidationContext, setContentSizeAdjustment, arginfo_appkit_ns_nscollectionviewlayoutinvalidationcontext_nscollectionviewlayoutinvalidationcontext_setcontentsizeadjustment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
