// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSResponder;

class NSResponder
{
    public static function init() -> int
    {
        return nsresponder_init();
    }

    public static function nextResponder(int handle) -> int
    {
        return nsresponder_next_responder(handle);
    }

    public static function setNextResponder(int handle, int nextResponder) -> void
    {
        nsresponder_set_next_responder(handle, nextResponder);
    }

    public static function tryToPerformWith(int handle, string action, int object_) -> bool
    {
        int r;

        let r = nsresponder_try_to_perform_with(handle, action, object_);

        return r == 1;
    }

    public static function performKeyEquivalent(int handle, int event) -> bool
    {
        int r;

        let r = nsresponder_perform_key_equivalent(handle, event);

        return r == 1;
    }

    public static function validRequestorForSendTypeReturnType(int handle, var sendType, var returnType) -> int
    {
        return nsresponder_valid_requestor_for_send_type_return_type(handle, sendType, returnType);
    }

    public static function mouseDown(int handle, int event) -> void
    {
        nsresponder_mouse_down(handle, event);
    }

    public static function rightMouseDown(int handle, int event) -> void
    {
        nsresponder_right_mouse_down(handle, event);
    }

    public static function otherMouseDown(int handle, int event) -> void
    {
        nsresponder_other_mouse_down(handle, event);
    }

    public static function mouseUp(int handle, int event) -> void
    {
        nsresponder_mouse_up(handle, event);
    }

    public static function rightMouseUp(int handle, int event) -> void
    {
        nsresponder_right_mouse_up(handle, event);
    }

    public static function otherMouseUp(int handle, int event) -> void
    {
        nsresponder_other_mouse_up(handle, event);
    }

    public static function mouseMoved(int handle, int event) -> void
    {
        nsresponder_mouse_moved(handle, event);
    }

    public static function mouseDragged(int handle, int event) -> void
    {
        nsresponder_mouse_dragged(handle, event);
    }

    public static function scrollWheel(int handle, int event) -> void
    {
        nsresponder_scroll_wheel(handle, event);
    }

    public static function rightMouseDragged(int handle, int event) -> void
    {
        nsresponder_right_mouse_dragged(handle, event);
    }

    public static function otherMouseDragged(int handle, int event) -> void
    {
        nsresponder_other_mouse_dragged(handle, event);
    }

    public static function mouseEntered(int handle, int event) -> void
    {
        nsresponder_mouse_entered(handle, event);
    }

    public static function mouseExited(int handle, int event) -> void
    {
        nsresponder_mouse_exited(handle, event);
    }

    public static function keyDown(int handle, int event) -> void
    {
        nsresponder_key_down(handle, event);
    }

    public static function keyUp(int handle, int event) -> void
    {
        nsresponder_key_up(handle, event);
    }

    public static function flagsChanged(int handle, int event) -> void
    {
        nsresponder_flags_changed(handle, event);
    }

    public static function tabletPoint(int handle, int event) -> void
    {
        nsresponder_tablet_point(handle, event);
    }

    public static function tabletProximity(int handle, int event) -> void
    {
        nsresponder_tablet_proximity(handle, event);
    }

    public static function cursorUpdate(int handle, int event) -> void
    {
        nsresponder_cursor_update(handle, event);
    }

    public static function magnifyWithEvent(int handle, int event) -> void
    {
        nsresponder_magnify_with_event(handle, event);
    }

    public static function rotateWithEvent(int handle, int event) -> void
    {
        nsresponder_rotate_with_event(handle, event);
    }

    public static function swipeWithEvent(int handle, int event) -> void
    {
        nsresponder_swipe_with_event(handle, event);
    }

    public static function beginGestureWithEvent(int handle, int event) -> void
    {
        nsresponder_begin_gesture_with_event(handle, event);
    }

    public static function endGestureWithEvent(int handle, int event) -> void
    {
        nsresponder_end_gesture_with_event(handle, event);
    }

    public static function smartMagnifyWithEvent(int handle, int event) -> void
    {
        nsresponder_smart_magnify_with_event(handle, event);
    }

    public static function changeModeWithEvent(int handle, int event) -> void
    {
        nsresponder_change_mode_with_event(handle, event);
    }

    public static function touchesBeganWithEvent(int handle, int event) -> void
    {
        nsresponder_touches_began_with_event(handle, event);
    }

    public static function touchesMovedWithEvent(int handle, int event) -> void
    {
        nsresponder_touches_moved_with_event(handle, event);
    }

    public static function touchesEndedWithEvent(int handle, int event) -> void
    {
        nsresponder_touches_ended_with_event(handle, event);
    }

    public static function touchesCancelledWithEvent(int handle, int event) -> void
    {
        nsresponder_touches_cancelled_with_event(handle, event);
    }

    public static function quickLookWithEvent(int handle, int event) -> void
    {
        nsresponder_quick_look_with_event(handle, event);
    }

    public static function pressureChangeWithEvent(int handle, int event) -> void
    {
        nsresponder_pressure_change_with_event(handle, event);
    }

    public static function contextMenuKeyDown(int handle, int event) -> void
    {
        nsresponder_context_menu_key_down(handle, event);
    }

    public static function noResponderFor(int handle, string eventSelector) -> void
    {
        nsresponder_no_responder_for(handle, eventSelector);
    }

    public static function acceptsFirstResponder(int handle) -> bool
    {
        int r;

        let r = nsresponder_accepts_first_responder(handle);

        return r == 1;
    }

    public static function becomeFirstResponder(int handle) -> bool
    {
        int r;

        let r = nsresponder_become_first_responder(handle);

        return r == 1;
    }

    public static function resignFirstResponder(int handle) -> bool
    {
        int r;

        let r = nsresponder_resign_first_responder(handle);

        return r == 1;
    }

    public static function interpretKeyEvents(int handle, array eventArray) -> void
    {
        nsresponder_interpret_key_events(handle, eventArray);
    }

    public static function flushBufferedKeyEvents(int handle) -> void
    {
        nsresponder_flush_buffered_key_events(handle);
    }

    public static function menu(int handle) -> int
    {
        return nsresponder_menu(handle);
    }

    public static function setMenu(int handle, int menu) -> void
    {
        nsresponder_set_menu(handle, menu);
    }

    public static function showContextHelp(int handle, int sender) -> void
    {
        nsresponder_show_context_help(handle, sender);
    }

    public static function helpRequested(int handle, int eventPtr) -> void
    {
        nsresponder_help_requested(handle, eventPtr);
    }

    public static function shouldBeTreatedAsInkEvent(int handle, int event) -> bool
    {
        int r;

        let r = nsresponder_should_be_treated_as_ink_event(handle, event);

        return r == 1;
    }

    public static function wantsScrollEventsForSwipeTrackingOnAxis(int handle, int axis) -> bool
    {
        int r;

        let r = nsresponder_wants_scroll_events_for_swipe_tracking_on_axis(handle, axis);

        return r == 1;
    }

    public static function wantsForwardedScrollEventsForAxis(int handle, int axis) -> bool
    {
        int r;

        let r = nsresponder_wants_forwarded_scroll_events_for_axis(handle, axis);

        return r == 1;
    }

    public static function supplementalTargetForActionSender(int handle, string action, int sender) -> int
    {
        return nsresponder_supplemental_target_for_action_sender(handle, action, sender);
    }

    public static function undoManager(int handle) -> int
    {
        return nsresponder_undo_manager(handle);
    }

    public static function validateProposedFirstResponderForEvent(int handle, int responder, int event) -> bool
    {
        int r;

        let r = nsresponder_validate_proposed_first_responder_for_event(handle, responder, event);

        return r == 1;
    }

    public static function presentErrorModalForWindowDelegateDidPresentSelectorContextInfo(int handle, int error, int window, int delegate, var didPresentSelector, int contextInfo) -> void
    {
        nsresponder_present_error_modal_for_window_delegate_did_present_selector_context_info(handle, error, window, delegate, didPresentSelector, contextInfo);
    }

    public static function presentError(int handle, int error) -> bool
    {
        int r;

        let r = nsresponder_present_error(handle, error);

        return r == 1;
    }

    public static function willPresentError(int handle, int error) -> int
    {
        return nsresponder_will_present_error(handle, error);
    }

    public static function performTextFinderAction(int handle, int sender) -> void
    {
        nsresponder_perform_text_finder_action(handle, sender);
    }

    public static function newWindowForTab(int handle, int sender) -> void
    {
        nsresponder_new_window_for_tab(handle, sender);
    }

    public static function showWritingTools(int handle, int sender) -> void
    {
        nsresponder_show_writing_tools(handle, sender);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
    // @reserved - (BOOL)performMnemonic:(NSString *)string API_DEPRECATED("This has always returned NO and had no effect on macOS", macos(10.0,10.8));

}
