
extern zend_class_entry *appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView);

PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, create);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, wrap);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, destroy);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, nsScrubberArrangedView);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, setSelected);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, isSelected);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, setHighlighted);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, isHighlighted);
PHP_METHOD(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, applyLayoutAttributes);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_create, 0, 4, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsScrubberArrangedViewPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_nsscrubberarrangedview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_setselected, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_isselected, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_sethighlighted, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_ishighlighted, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_applylayoutattributes, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layoutAttributesPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_method_entry) {
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, create, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, wrap, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, destroy, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, nsScrubberArrangedView, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_nsscrubberarrangedview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, setSelected, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_setselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, isSelected, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_isselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, setHighlighted, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_sethighlighted, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, isHighlighted, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_ishighlighted, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberArrangedView_NSScrubberArrangedView, applyLayoutAttributes, arginfo_appkit_ns_nsscrubberarrangedview_nsscrubberarrangedview_applylayoutattributes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
