// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSearchField;

class NSSearchField
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nssearchfield_init_with_frame(x, y, width, height);
    }

    public static function searchTextBounds(int handle) -> array
    {
        var result;

        let result = nssearchfield_search_text_bounds(handle);

        return result;
    }

    public static function searchButtonBounds(int handle) -> array
    {
        var result;

        let result = nssearchfield_search_button_bounds(handle);

        return result;
    }

    public static function cancelButtonBounds(int handle) -> array
    {
        var result;

        let result = nssearchfield_cancel_button_bounds(handle);

        return result;
    }

    public static function recentSearches(int handle) -> array
    {
        var result;

        let result = nssearchfield_recent_searches(handle);

        return result;
    }

    public static function setRecentSearches(int handle, array recentSearches) -> void
    {
        nssearchfield_set_recent_searches(handle, recentSearches);
    }

    public static function recentsAutosaveName(int handle) -> var
    {
        var result;

        let result = nssearchfield_recents_autosave_name(handle);

        return result;
    }

    public static function setRecentsAutosaveName(int handle, var recentsAutosaveName) -> void
    {
        nssearchfield_set_recents_autosave_name(handle, recentsAutosaveName);
    }

    public static function searchMenuTemplate(int handle) -> int
    {
        return nssearchfield_search_menu_template(handle);
    }

    public static function setSearchMenuTemplate(int handle, int searchMenuTemplate) -> void
    {
        nssearchfield_set_search_menu_template(handle, searchMenuTemplate);
    }

    public static function sendsWholeSearchString(int handle) -> bool
    {
        int r;

        let r = nssearchfield_sends_whole_search_string(handle);

        return r == 1;
    }

    public static function setSendsWholeSearchString(int handle, bool sendsWholeSearchString) -> void
    {
        nssearchfield_set_sends_whole_search_string(handle, sendsWholeSearchString);
    }

    public static function maximumRecents(int handle) -> int
    {
        return nssearchfield_maximum_recents(handle);
    }

    public static function setMaximumRecents(int handle, int maximumRecents) -> void
    {
        nssearchfield_set_maximum_recents(handle, maximumRecents);
    }

    public static function sendsSearchStringImmediately(int handle) -> bool
    {
        int r;

        let r = nssearchfield_sends_search_string_immediately(handle);

        return r == 1;
    }

    public static function setSendsSearchStringImmediately(int handle, bool sendsSearchStringImmediately) -> void
    {
        nssearchfield_set_sends_search_string_immediately(handle, sendsSearchStringImmediately);
    }

    public static function delegate(int handle) -> int
    {
        return nssearchfield_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nssearchfield_set_delegate(handle, delegate);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (NSRect)rectForSearchTextWhenCentered:(BOOL)isCentered API_DEPRECATED
    // @reserved - (NSRect)rectForSearchButtonWhenCentered:(BOOL)isCentered API_DEPRECATED
    // @reserved - (NSRect)rectForCancelButtonWhenCentered:(BOOL)isCentered API_DEPRECATED
    // @reserved @property BOOL centersPlaceholder API_DEPRECATED — getter
    // @reserved @property BOOL centersPlaceholder API_DEPRECATED — setter

}
