
extern zend_class_entry *appkit_ns_nsspeechrecognizer_nsspeechrecognizer_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer);

PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, create);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, wrap);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, destroy);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, nsSpeechRecognizer);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, startListening);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, stopListening);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setCommands);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, commandsCount);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, commandAt);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, displayedCommandsTitle);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setDisplayedCommandsTitle);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, listensInForegroundOnly);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setListensInForegroundOnly);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, blocksOtherRecognizers);
PHP_METHOD(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setBlocksOtherRecognizers);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsSpeechRecognizerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_nsspeechrecognizer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_startlistening, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_stoplistening, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setcommands, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, commands, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_commandscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_commandat, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_displayedcommandstitle, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setdisplayedcommandstitle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_listensinforegroundonly, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setlistensinforegroundonly, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_blocksotherrecognizers, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setblocksotherrecognizers, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsspeechrecognizer_nsspeechrecognizer_method_entry) {
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, create, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, wrap, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, destroy, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, nsSpeechRecognizer, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_nsspeechrecognizer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, startListening, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_startlistening, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, stopListening, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_stoplistening, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setCommands, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setcommands, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, commandsCount, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_commandscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, commandAt, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_commandat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, displayedCommandsTitle, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_displayedcommandstitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setDisplayedCommandsTitle, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setdisplayedcommandstitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, listensInForegroundOnly, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_listensinforegroundonly, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setListensInForegroundOnly, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setlistensinforegroundonly, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, blocksOtherRecognizers, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_blocksotherrecognizers, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSpeechRecognizer_NSSpeechRecognizer, setBlocksOtherRecognizers, arginfo_appkit_ns_nsspeechrecognizer_nsspeechrecognizer_setblocksotherrecognizers, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
