// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\AV\AVPlayerView;

class AVPlayerView
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return avplayerview_init_with_frame(x, y, width, height);
    }

    public static function player(int handle) -> int
    {
        return avplayerview_player(handle);
    }

    public static function setPlayer(int handle, int player) -> void
    {
        avplayerview_set_player(handle, player);
    }

    public static function controlsStyle(int handle) -> int
    {
        return avplayerview_controls_style(handle);
    }

    public static function setControlsStyle(int handle, int controlsStyle) -> void
    {
        avplayerview_set_controls_style(handle, controlsStyle);
    }

    public static function videoGravity(int handle) -> var
    {
        var result;

        let result = avplayerview_video_gravity(handle);

        return result;
    }

    public static function setVideoGravity(int handle, string videoGravity) -> void
    {
        avplayerview_set_video_gravity(handle, videoGravity);
    }

    public static function showsFullScreenToggleButton(int handle) -> bool
    {
        int r;

        let r = avplayerview_shows_full_screen_toggle_button(handle);

        return r == 1;
    }

    public static function setShowsFullScreenToggleButton(int handle, bool shows) -> void
    {
        avplayerview_set_shows_full_screen_toggle_button(handle, shows);
    }
}
