// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSlider;

class NSSlider
{
    public static function sliderType(int handle) -> int
    {
        return nsslider_slider_type(handle);
    }

    public static function setSliderType(int handle, int sliderType) -> void
    {
        nsslider_set_slider_type(handle, sliderType);
    }

    public static function minValue(int handle) -> double
    {
        return nsslider_min_value(handle);
    }

    public static function setMinValue(int handle, double minValue) -> void
    {
        nsslider_set_min_value(handle, minValue);
    }

    public static function maxValue(int handle) -> double
    {
        return nsslider_max_value(handle);
    }

    public static function setMaxValue(int handle, double maxValue) -> void
    {
        nsslider_set_max_value(handle, maxValue);
    }

    public static function altIncrementValue(int handle) -> double
    {
        return nsslider_alt_increment_value(handle);
    }

    public static function setAltIncrementValue(int handle, double altIncrementValue) -> void
    {
        nsslider_set_alt_increment_value(handle, altIncrementValue);
    }

    public static function knobThickness(int handle) -> double
    {
        return nsslider_knob_thickness(handle);
    }

    public static function acceptsFirstMouse(int handle, int event) -> bool
    {
        int r;

        let r = nsslider_accepts_first_mouse(handle, event);

        return r == 1;
    }

    public static function isVertical(int handle) -> bool
    {
        int r;

        let r = nsslider_is_vertical(handle);

        return r == 1;
    }

    public static function setVertical(int handle, bool vertical) -> void
    {
        nsslider_set_vertical(handle, vertical);
    }

    public static function trackFillColor(int handle) -> int
    {
        return nsslider_track_fill_color(handle);
    }

    public static function setTrackFillColor(int handle, int trackFillColor) -> void
    {
        nsslider_set_track_fill_color(handle, trackFillColor);
    }

    public static function numberOfTickMarks(int handle) -> int
    {
        return nsslider_number_of_tick_marks(handle);
    }

    public static function setNumberOfTickMarks(int handle, int numberOfTickMarks) -> void
    {
        nsslider_set_number_of_tick_marks(handle, numberOfTickMarks);
    }

    public static function tickMarkPosition(int handle) -> int
    {
        return nsslider_tick_mark_position(handle);
    }

    public static function setTickMarkPosition(int handle, int tickMarkPosition) -> void
    {
        nsslider_set_tick_mark_position(handle, tickMarkPosition);
    }

    public static function allowsTickMarkValuesOnly(int handle) -> bool
    {
        int r;

        let r = nsslider_allows_tick_mark_values_only(handle);

        return r == 1;
    }

    public static function setAllowsTickMarkValuesOnly(int handle, bool allowsTickMarkValuesOnly) -> void
    {
        nsslider_set_allows_tick_mark_values_only(handle, allowsTickMarkValuesOnly);
    }

    public static function tickMarkValueAtIndex(int handle, int index) -> double
    {
        return nsslider_tick_mark_value_at_index(handle, index);
    }

    public static function rectOfTickMarkAtIndex(int handle, int index) -> array
    {
        var result;

        let result = nsslider_rect_of_tick_mark_at_index(handle, index);

        return result;
    }

    public static function indexOfTickMarkAtPoint(int handle, double x, double y) -> int
    {
        return nsslider_index_of_tick_mark_at_point(handle, x, y);
    }

    public static function closestTickMarkValueToValue(int handle, double value) -> double
    {
        return nsslider_closest_tick_mark_value_to_value(handle, value);
    }

    public static function sliderWithTargetAction(int target, var action) -> int
    {
        return nsslider_slider_with_target_action(target, action);
    }

    public static function sliderWithValueMinValueMaxValueTargetAction(double value, double minValue, double maxValue, int target, var action) -> int
    {
        return nsslider_slider_with_value_min_value_max_value_target_action(value, minValue, maxValue, target, action);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (readonly, getter=isVertical) BOOL vertical — NSSliderVerticalGetter duplicate of the 10.12 readwrite property
    // @reserved - (void)setTitleCell:(null_unspecified NSCell *)cell API_DEPRECATED
    // @reserved - (null_unspecified id)titleCell API_DEPRECATED
    // @reserved - (void)setTitleColor:(null_unspecified NSColor *)newColor API_DEPRECATED
    // @reserved - (null_unspecified NSColor *)titleColor API_DEPRECATED
    // @reserved - (void)setTitleFont:(null_unspecified NSFont *)fontObj API_DEPRECATED
    // @reserved - (null_unspecified NSFont *)titleFont API_DEPRECATED
    // @reserved - (null_unspecified NSString *)title API_DEPRECATED
    // @reserved - (void)setTitle:(null_unspecified NSString *)string API_DEPRECATED
    // @reserved - (void)setKnobThickness:(CGFloat)thickness API_DEPRECATED
    // @reserved - (void)setImage:(null_unspecified NSImage *)backgroundImage API_DEPRECATED
    // @reserved - (null_unspecified NSImage *)image API_DEPRECATED

}
