// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\GC\GCControllerAxisInput;

class GCControllerAxisInput
{
    public static function value(int handle) -> double
    {
        return gccontrolleraxisinput_value(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (nonatomic, copy, nullable) GCControllerAxisValueChangedHandler valueChangedHandler — getter (block)
    // @reserved @property (nonatomic, copy, nullable) GCControllerAxisValueChangedHandler valueChangedHandler — setter (block)
    // @reserved - (void)setValue:(float)value — snapshot write, not bound in this slice

}
