
extern zend_class_entry *appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration);

PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithPointSizeWeightScale);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithPointSizeWeight);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithTextStyleScale);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithTextStyle);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithScale);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationPreferringMonochrome);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationPreferringHierarchical);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithHierarchicalColor);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithPaletteColors);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationPreferringMulticolor);
PHP_METHOD(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationByApplyingConfiguration);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithpointsizeweightscale, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pointSize, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, weight, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, scale, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithpointsizeweight, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pointSize, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, weight, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithtextstylescale, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, style, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, scale, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithtextstyle, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, style, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithscale, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, scale, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationpreferringmonochrome, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationpreferringhierarchical, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithhierarchicalcolor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, hierarchicalColor, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithpalettecolors, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, paletteColors, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationpreferringmulticolor, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationbyapplyingconfiguration, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, configuration, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_method_entry) {
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithPointSizeWeightScale, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithpointsizeweightscale, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithPointSizeWeight, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithpointsizeweight, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithTextStyleScale, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithtextstylescale, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithTextStyle, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithtextstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithScale, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithscale, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationPreferringMonochrome, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationpreferringmonochrome, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationPreferringHierarchical, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationpreferringhierarchical, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithHierarchicalColor, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithhierarchicalcolor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationWithPaletteColors, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationwithpalettecolors, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationPreferringMulticolor, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationpreferringmulticolor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSImageSymbolConfiguration_NSImageSymbolConfiguration, configurationByApplyingConfiguration, arginfo_appkit_ns_nsimagesymbolconfiguration_nsimagesymbolconfiguration_configurationbyapplyingconfiguration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
