
extern zend_class_entry *appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource);

PHP_METHOD(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, create);
PHP_METHOD(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, destroy);
PHP_METHOD(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, setItemTitle);
PHP_METHOD(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, apply);
PHP_METHOD(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, itemCount);
PHP_METHOD(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, itemIdAt);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, table, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_setitemtitle, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, itemId, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_apply, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionId, IS_STRING, 0)
	ZEND_ARG_ARRAY_INFO(0, itemIds, 0)
	ZEND_ARG_TYPE_INFO(0, animating, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_itemcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_itemidat, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, source, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_method_entry) {
	PHP_ME(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, create, arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, destroy, arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, setItemTitle, arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_setitemtitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, apply, arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_apply, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, itemCount, arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_itemcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource, itemIdAt, arginfo_appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_itemidat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
