
extern zend_class_entry *appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout);

PHP_METHOD(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, create);
PHP_METHOD(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, wrap);
PHP_METHOD(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, destroy);
PHP_METHOD(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, nsScrubberProportionalLayout);
PHP_METHOD(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, setNumberOfVisibleItems);
PHP_METHOD(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, getNumberOfVisibleItems);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, numberOfVisibleItems, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsScrubberProportionalLayoutPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_nsscrubberproportionallayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_setnumberofvisibleitems, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_getnumberofvisibleitems, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_method_entry) {
	PHP_ME(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, create, arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, wrap, arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, destroy, arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, nsScrubberProportionalLayout, arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_nsscrubberproportionallayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, setNumberOfVisibleItems, arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_setnumberofvisibleitems, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberProportionalLayout_NSScrubberProportionalLayout, getNumberOfVisibleItems, arginfo_appkit_ns_nsscrubberproportionallayout_nsscrubberproportionallayout_getnumberofvisibleitems, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
