
extern zend_class_entry *appkit_ns_nstextcontentstorage_nstextcontentstorage_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTextContentStorage_NSTextContentStorage);

PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, create);
PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, wrap);
PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, destroy);
PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, getAttributedString);
PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, setAttributedString);
PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, textElementForAttributedString);
PHP_METHOD(AppKit_NS_NSTextContentStorage_NSTextContentStorage, attributedStringForTextElement);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTextContentStoragePtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, storage, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_getattributedstring, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, storage, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_setattributedstring, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, storage, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_textelementforattributedstring, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, storage, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_attributedstringfortextelement, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, storage, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, element, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstextcontentstorage_nstextcontentstorage_method_entry) {
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, create, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, wrap, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, destroy, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, getAttributedString, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_getattributedstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, setAttributedString, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_setattributedstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, textElementForAttributedString, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_textelementforattributedstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextContentStorage_NSTextContentStorage, attributedStringForTextElement, arginfo_appkit_ns_nstextcontentstorage_nstextcontentstorage_attributedstringfortextelement, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
