
extern zend_class_entry *appkit_ns_nswindowcontroller_nswindowcontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSWindowController_NSWindowController);

PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, create);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, createEmpty);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, wrap);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, destroy);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, nsWindowController);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, nsWindow);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, showWindow);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, close);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, setContentViewController);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, isWindowLoaded);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, setShouldCloseDocument);
PHP_METHOD(AppKit_NS_NSWindowController_NSWindowController, shouldCloseDocument);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, window, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_createempty, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsWindowControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_nswindowcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_nswindow, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_showwindow, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_close, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_setcontentviewcontroller, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, viewController, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_iswindowloaded, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_setshouldclosedocument, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, shouldClose, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_shouldclosedocument, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nswindowcontroller_nswindowcontroller_method_entry) {
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, create, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, createEmpty, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_createempty, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, wrap, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, destroy, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, nsWindowController, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_nswindowcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, nsWindow, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_nswindow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, showWindow, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_showwindow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, close, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_close, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, setContentViewController, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_setcontentviewcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, isWindowLoaded, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_iswindowloaded, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, setShouldCloseDocument, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_setshouldclosedocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSWindowController_NSWindowController, shouldCloseDocument, arginfo_appkit_ns_nswindowcontroller_nswindowcontroller_shouldclosedocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
