
extern zend_class_entry *appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem);

PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, create);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, trackingSeparator);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, wrap);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, destroy);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, nsTrackingSeparatorToolbarItem);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, setSplitView);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, getSplitView);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, setDividerIndex);
PHP_METHOD(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, getDividerIndex);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_trackingseparator, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, splitView, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dividerIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTrackingSeparatorToolbarItemPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_setsplitview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, splitView, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_getsplitview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_setdividerindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dividerIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_getdividerindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, create, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, trackingSeparator, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_trackingseparator, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, wrap, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, destroy, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, nsTrackingSeparatorToolbarItem, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, setSplitView, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_setsplitview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, getSplitView, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_getsplitview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, setDividerIndex, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_setdividerindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTrackingSeparatorToolbarItem_NSTrackingSeparatorToolbarItem, getDividerIndex, arginfo_appkit_ns_nstrackingseparatortoolbaritem_nstrackingseparatortoolbaritem_getdividerindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
