
extern zend_class_entry *appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver);

PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, readableDraggedTypes);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, wrap);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, destroy);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, nsFilePromiseReceiver);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, fileTypes);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, fileNames);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, receiveAtDestination);
PHP_METHOD(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, pollReceivedFile);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_readabledraggedtypes, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsFilePromiseReceiverPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, receiver, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_nsfilepromisereceiver, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, receiver, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_filetypes, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, receiver, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_filenames, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, receiver, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_receiveatdestination, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, receiver, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, destinationDir, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_pollreceivedfile, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, receiver, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_method_entry) {
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, readableDraggedTypes, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_readabledraggedtypes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, wrap, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, destroy, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, nsFilePromiseReceiver, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_nsfilepromisereceiver, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, fileTypes, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_filetypes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, fileNames, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_filenames, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, receiveAtDestination, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_receiveatdestination, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSFilePromiseReceiver_NSFilePromiseReceiver, pollReceivedFile, arginfo_appkit_ns_nsfilepromisereceiver_nsfilepromisereceiver_pollreceivedfile, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
