
extern zend_class_entry *appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout);

PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, init);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, minimumLineSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setMinimumLineSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, minimumInteritemSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setMinimumInteritemSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, itemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setItemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, estimatedItemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setEstimatedItemSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, scrollDirection);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setScrollDirection);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, headerReferenceSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setHeaderReferenceSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, footerReferenceSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setFooterReferenceSize);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionInset);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setSectionInset);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionHeadersPinToVisibleBounds);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setSectionHeadersPinToVisibleBounds);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionFootersPinToVisibleBounds);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setSectionFootersPinToVisibleBounds);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionAtIndexIsCollapsed);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, collapseSectionAtIndex);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, expandSectionAtIndex);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_init, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_minimumlinespacing, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setminimumlinespacing, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, minimumLineSpacing, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_minimuminteritemspacing, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setminimuminteritemspacing, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, minimumInteritemSpacing, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_itemsize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setitemsize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_estimateditemsize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setestimateditemsize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_scrolldirection, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setscrolldirection, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, scrollDirection, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_headerreferencesize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setheaderreferencesize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_footerreferencesize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setfooterreferencesize, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectioninset, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setsectioninset, 0, 5, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, top, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, left, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, bottom, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, right, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectionheaderspintovisiblebounds, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setsectionheaderspintovisiblebounds, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionHeadersPinToVisibleBounds, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectionfooterspintovisiblebounds, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setsectionfooterspintovisiblebounds, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionFootersPinToVisibleBounds, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectionatindexiscollapsed, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_collapsesectionatindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_expandsectionatindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, sectionIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, init, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_init, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, minimumLineSpacing, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_minimumlinespacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setMinimumLineSpacing, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setminimumlinespacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, minimumInteritemSpacing, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_minimuminteritemspacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setMinimumInteritemSpacing, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setminimuminteritemspacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, itemSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_itemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setItemSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setitemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, estimatedItemSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_estimateditemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setEstimatedItemSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setestimateditemsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, scrollDirection, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_scrolldirection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setScrollDirection, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setscrolldirection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, headerReferenceSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_headerreferencesize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setHeaderReferenceSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setheaderreferencesize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, footerReferenceSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_footerreferencesize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setFooterReferenceSize, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setfooterreferencesize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionInset, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectioninset, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setSectionInset, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setsectioninset, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionHeadersPinToVisibleBounds, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectionheaderspintovisiblebounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setSectionHeadersPinToVisibleBounds, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setsectionheaderspintovisiblebounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionFootersPinToVisibleBounds, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectionfooterspintovisiblebounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, setSectionFootersPinToVisibleBounds, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_setsectionfooterspintovisiblebounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, sectionAtIndexIsCollapsed, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_sectionatindexiscollapsed, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, collapseSectionAtIndex, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_collapsesectionatindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout, expandSectionAtIndex, arginfo_appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_expandsectionatindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
