
/* This file was generated automatically by Zephir do not modify it! */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <php.h>

#include "php_ext.h"
#include "appkit.h"

#include <ext/standard/info.h>

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/globals.h"
#include "kernel/main.h"
#include "kernel/fcall.h"
#include "kernel/memory.h"



zend_class_entry *appkit_ns_nsactioncell_nsactioncell_ce;
zend_class_entry *appkit_ns_nsadaptiveimageglyph_nsadaptiveimageglyph_ce;
zend_class_entry *appkit_ns_nsalert_nsalert_ce;
zend_class_entry *appkit_ns_nsanimation_nsanimation_ce;
zend_class_entry *appkit_ns_nsanimationcontext_nsanimationcontext_ce;
zend_class_entry *appkit_ns_nsappearance_nsappearance_ce;
zend_class_entry *appkit_ns_nsapplication_nsapplication_ce;
zend_class_entry *appkit_ns_nsatstypesetter_nsatstypesetter_ce;
zend_class_entry *appkit_ns_nsbezierpath_nsbezierpath_ce;
zend_class_entry *appkit_ns_nsbitmapimagerep_nsbitmapimagerep_ce;
zend_class_entry *appkit_ns_nsbox_nsbox_ce;
zend_class_entry *appkit_ns_nsbrowser_nsbrowser_ce;
zend_class_entry *appkit_ns_nsbrowsercell_nsbrowsercell_ce;
zend_class_entry *appkit_ns_nsbutton_nsbutton_ce;
zend_class_entry *appkit_ns_nsbuttoncell_nsbuttoncell_ce;
zend_class_entry *appkit_ns_nscachedimagerep_nscachedimagerep_ce;
zend_class_entry *appkit_ns_nscell_nscell_ce;
zend_class_entry *appkit_ns_nsciimagerep_nsciimagerep_ce;
zend_class_entry *appkit_ns_nsclickgesturerecognizer_nsclickgesturerecognizer_ce;
zend_class_entry *appkit_ns_nsclipview_nsclipview_ce;
zend_class_entry *appkit_ns_nscollectionview_nscollectionview_ce;
zend_class_entry *appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_ce;
zend_class_entry *appkit_ns_nscollectionviewdiffabledatasource_nscollectionviewdiffabledatasource_ce;
zend_class_entry *appkit_ns_nscollectionviewflowlayout_nscollectionviewflowlayout_ce;
zend_class_entry *appkit_ns_nscollectionviewgridlayout_nscollectionviewgridlayout_ce;
zend_class_entry *appkit_ns_nscollectionviewitem_nscollectionviewitem_ce;
zend_class_entry *appkit_ns_nscollectionviewlayout_nscollectionviewlayout_ce;
zend_class_entry *appkit_ns_nscollectionviewtransitionlayout_nscollectionviewtransitionlayout_ce;
zend_class_entry *appkit_ns_nscolor_nscolor_ce;
zend_class_entry *appkit_ns_nscolorlist_nscolorlist_ce;
zend_class_entry *appkit_ns_nscolorpanel_nscolorpanel_ce;
zend_class_entry *appkit_ns_nscolorpicker_nscolorpicker_ce;
zend_class_entry *appkit_ns_nscolorsampler_nscolorsampler_ce;
zend_class_entry *appkit_ns_nscolorspace_nscolorspace_ce;
zend_class_entry *appkit_ns_nscolorwell_nscolorwell_ce;
zend_class_entry *appkit_ns_nscombobox_nscombobox_ce;
zend_class_entry *appkit_ns_nscombobutton_nscombobutton_ce;
zend_class_entry *appkit_ns_nscontrol_nscontrol_ce;
zend_class_entry *appkit_ns_nscontroller_nscontroller_ce;
zend_class_entry *appkit_ns_nscursor_nscursor_ce;
zend_class_entry *appkit_ns_nscustomimagerep_nscustomimagerep_ce;
zend_class_entry *appkit_ns_nsdatepicker_nsdatepicker_ce;
zend_class_entry *appkit_ns_nsdictionary_nsdictionary_ce;
zend_class_entry *appkit_ns_nsepsimagerep_nsepsimagerep_ce;
zend_class_entry *appkit_ns_nsevent_nsevent_ce;
zend_class_entry *appkit_ns_nsfont_nsfont_ce;
zend_class_entry *appkit_ns_nsfontcollection_nsfontcollection_ce;
zend_class_entry *appkit_ns_nsfontdescriptor_nsfontdescriptor_ce;
zend_class_entry *appkit_ns_nsfontmanager_nsfontmanager_ce;
zend_class_entry *appkit_ns_nsfontpanel_nsfontpanel_ce;
zend_class_entry *appkit_ns_nsform_nsform_ce;
zend_class_entry *appkit_ns_nsformcell_nsformcell_ce;
zend_class_entry *appkit_ns_nsgesturerecognizer_nsgesturerecognizer_ce;
zend_class_entry *appkit_ns_nsglyphgenerator_nsglyphgenerator_ce;
zend_class_entry *appkit_ns_nsgradient_nsgradient_ce;
zend_class_entry *appkit_ns_nsgraphicscontext_nsgraphicscontext_ce;
zend_class_entry *appkit_ns_nsgridcell_nsgridcell_ce;
zend_class_entry *appkit_ns_nsgridcolumn_nsgridcolumn_ce;
zend_class_entry *appkit_ns_nsgridrow_nsgridrow_ce;
zend_class_entry *appkit_ns_nsgridview_nsgridview_ce;
zend_class_entry *appkit_ns_nsimage_nsimage_ce;
zend_class_entry *appkit_ns_nsimagerep_nsimagerep_ce;
zend_class_entry *appkit_ns_nsimageview_nsimageview_ce;
zend_class_entry *appkit_ns_nslayoutmanager_nslayoutmanager_ce;
zend_class_entry *appkit_ns_nslevelindicator_nslevelindicator_ce;
zend_class_entry *appkit_ns_nslevelindicatorcell_nslevelindicatorcell_ce;
zend_class_entry *appkit_ns_nsmagnificationgesturerecognizer_nsmagnificationgesturerecognizer_ce;
zend_class_entry *appkit_ns_nsmatrix_nsmatrix_ce;
zend_class_entry *appkit_ns_nsmenu_nsmenu_ce;
zend_class_entry *appkit_ns_nsmenuitem_nsmenuitem_ce;
zend_class_entry *appkit_ns_nsmenutoolbaritem_nsmenutoolbaritem_ce;
zend_class_entry *appkit_ns_nsopenpanel_nsopenpanel_ce;
zend_class_entry *appkit_ns_nsoutlineview_nsoutlineview_ce;
zend_class_entry *appkit_ns_nspagecontroller_nspagecontroller_ce;
zend_class_entry *appkit_ns_nspanel_nspanel_ce;
zend_class_entry *appkit_ns_nspangesturerecognizer_nspangesturerecognizer_ce;
zend_class_entry *appkit_ns_nsparagraphstyle_nsparagraphstyle_ce;
zend_class_entry *appkit_ns_nspathcell_nspathcell_ce;
zend_class_entry *appkit_ns_nspathcomponentcell_nspathcomponentcell_ce;
zend_class_entry *appkit_ns_nspathcontrol_nspathcontrol_ce;
zend_class_entry *appkit_ns_nspdfimagerep_nspdfimagerep_ce;
zend_class_entry *appkit_ns_nspopover_nspopover_ce;
zend_class_entry *appkit_ns_nspopupbutton_nspopupbutton_ce;
zend_class_entry *appkit_ns_nspopupbuttoncell_nspopupbuttoncell_ce;
zend_class_entry *appkit_ns_nspredicateeditor_nspredicateeditor_ce;
zend_class_entry *appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_ce;
zend_class_entry *appkit_ns_nsprogressindicator_nsprogressindicator_ce;
zend_class_entry *appkit_ns_nsresponder_nsresponder_ce;
zend_class_entry *appkit_ns_nsrotationgesturerecognizer_nsrotationgesturerecognizer_ce;
zend_class_entry *appkit_ns_nsruleeditor_nsruleeditor_ce;
zend_class_entry *appkit_ns_nsrulermarker_nsrulermarker_ce;
zend_class_entry *appkit_ns_nsrulerview_nsrulerview_ce;
zend_class_entry *appkit_ns_nssavepanel_nssavepanel_ce;
zend_class_entry *appkit_ns_nsscreen_nsscreen_ce;
zend_class_entry *appkit_ns_nsscroller_nsscroller_ce;
zend_class_entry *appkit_ns_nsscrollview_nsscrollview_ce;
zend_class_entry *appkit_ns_nsscrubber_nsscrubber_ce;
zend_class_entry *appkit_ns_nssearchfield_nssearchfield_ce;
zend_class_entry *appkit_ns_nssearchfieldcell_nssearchfieldcell_ce;
zend_class_entry *appkit_ns_nssecuretextfield_nssecuretextfield_ce;
zend_class_entry *appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_ce;
zend_class_entry *appkit_ns_nssegmentedcell_nssegmentedcell_ce;
zend_class_entry *appkit_ns_nssegmentedcontrol_nssegmentedcontrol_ce;
zend_class_entry *appkit_ns_nsshadow_nsshadow_ce;
zend_class_entry *appkit_ns_nsslider_nsslider_ce;
zend_class_entry *appkit_ns_nsslidercell_nsslidercell_ce;
zend_class_entry *appkit_ns_nsspellchecker_nsspellchecker_ce;
zend_class_entry *appkit_ns_nssplitview_nssplitview_ce;
zend_class_entry *appkit_ns_nssplitviewcontroller_nssplitviewcontroller_ce;
zend_class_entry *appkit_ns_nssplitviewitem_nssplitviewitem_ce;
zend_class_entry *appkit_ns_nsstackview_nsstackview_ce;
zend_class_entry *appkit_ns_nsstatusbar_nsstatusbar_ce;
zend_class_entry *appkit_ns_nsstatusbarbutton_nsstatusbarbutton_ce;
zend_class_entry *appkit_ns_nsstatusitem_nsstatusitem_ce;
zend_class_entry *appkit_ns_nsstepper_nsstepper_ce;
zend_class_entry *appkit_ns_nssteppercell_nssteppercell_ce;
zend_class_entry *appkit_ns_nsswitch_nsswitch_ce;
zend_class_entry *appkit_ns_nstablecellview_nstablecellview_ce;
zend_class_entry *appkit_ns_nstablecolumn_nstablecolumn_ce;
zend_class_entry *appkit_ns_nstableheadercell_nstableheadercell_ce;
zend_class_entry *appkit_ns_nstableheaderview_nstableheaderview_ce;
zend_class_entry *appkit_ns_nstablerowview_nstablerowview_ce;
zend_class_entry *appkit_ns_nstableview_nstableview_ce;
zend_class_entry *appkit_ns_nstableviewdiffabledatasource_nstableviewdiffabledatasource_ce;
zend_class_entry *appkit_ns_nstabview_nstabview_ce;
zend_class_entry *appkit_ns_nstabviewcontroller_nstabviewcontroller_ce;
zend_class_entry *appkit_ns_nstabviewitem_nstabviewitem_ce;
zend_class_entry *appkit_ns_nstext_nstext_ce;
zend_class_entry *appkit_ns_nstextattachment_nstextattachment_ce;
zend_class_entry *appkit_ns_nstextattachmentcell_nstextattachmentcell_ce;
zend_class_entry *appkit_ns_nstextblock_nstextblock_ce;
zend_class_entry *appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_ce;
zend_class_entry *appkit_ns_nstextcontainer_nstextcontainer_ce;
zend_class_entry *appkit_ns_nstextcontentmanager_nstextcontentmanager_ce;
zend_class_entry *appkit_ns_nstextcontentstorage_nstextcontentstorage_ce;
zend_class_entry *appkit_ns_nstextelement_nstextelement_ce;
zend_class_entry *appkit_ns_nstextfield_nstextfield_ce;
zend_class_entry *appkit_ns_nstextfieldcell_nstextfieldcell_ce;
zend_class_entry *appkit_ns_nstextfinder_nstextfinder_ce;
zend_class_entry *appkit_ns_nstextinputcontext_nstextinputcontext_ce;
zend_class_entry *appkit_ns_nstextinsertionindicator_nstextinsertionindicator_ce;
zend_class_entry *appkit_ns_nstextlayoutfragment_nstextlayoutfragment_ce;
zend_class_entry *appkit_ns_nstextlayoutmanager_nstextlayoutmanager_ce;
zend_class_entry *appkit_ns_nstextlinefragment_nstextlinefragment_ce;
zend_class_entry *appkit_ns_nstextlist_nstextlist_ce;
zend_class_entry *appkit_ns_nstextparagraph_nstextparagraph_ce;
zend_class_entry *appkit_ns_nstextselection_nstextselection_ce;
zend_class_entry *appkit_ns_nstextstorage_nstextstorage_ce;
zend_class_entry *appkit_ns_nstexttable_nstexttable_ce;
zend_class_entry *appkit_ns_nstextview_nstextview_ce;
zend_class_entry *appkit_ns_nstextviewportlayoutcontroller_nstextviewportlayoutcontroller_ce;
zend_class_entry *appkit_ns_nstokenfield_nstokenfield_ce;
zend_class_entry *appkit_ns_nstokenfieldcell_nstokenfieldcell_ce;
zend_class_entry *appkit_ns_nstoolbar_nstoolbar_ce;
zend_class_entry *appkit_ns_nstouch_nstouch_ce;
zend_class_entry *appkit_ns_nstrackingarea_nstrackingarea_ce;
zend_class_entry *appkit_ns_nstypesetter_nstypesetter_ce;
zend_class_entry *appkit_ns_nsview_nsview_ce;
zend_class_entry *appkit_ns_nsviewanimation_nsviewanimation_ce;
zend_class_entry *appkit_ns_nsviewcontroller_nsviewcontroller_ce;
zend_class_entry *appkit_ns_nsvisualeffectview_nsvisualeffectview_ce;
zend_class_entry *appkit_ns_nswindow_nswindow_ce;
zend_class_entry *appkit_ns_nswindowcontroller_nswindowcontroller_ce;
zend_class_entry *appkit_ns_nsworkspace_nsworkspace_ce;

ZEND_DECLARE_MODULE_GLOBALS(appkit)

PHP_INI_BEGIN()
	
PHP_INI_END()

static PHP_MINIT_FUNCTION(appkit)
{
	REGISTER_INI_ENTRIES();
	zephir_module_init();
	ZEPHIR_INIT(AppKit_NS_NSATSTypesetter_NSATSTypesetter);
	ZEPHIR_INIT(AppKit_NS_NSActionCell_NSActionCell);
	ZEPHIR_INIT(AppKit_NS_NSAdaptiveImageGlyph_NSAdaptiveImageGlyph);
	ZEPHIR_INIT(AppKit_NS_NSAlert_NSAlert);
	ZEPHIR_INIT(AppKit_NS_NSAnimationContext_NSAnimationContext);
	ZEPHIR_INIT(AppKit_NS_NSAnimation_NSAnimation);
	ZEPHIR_INIT(AppKit_NS_NSAppearance_NSAppearance);
	ZEPHIR_INIT(AppKit_NS_NSApplication_NSApplication);
	ZEPHIR_INIT(AppKit_NS_NSBezierPath_NSBezierPath);
	ZEPHIR_INIT(AppKit_NS_NSBitmapImageRep_NSBitmapImageRep);
	ZEPHIR_INIT(AppKit_NS_NSBox_NSBox);
	ZEPHIR_INIT(AppKit_NS_NSBrowserCell_NSBrowserCell);
	ZEPHIR_INIT(AppKit_NS_NSBrowser_NSBrowser);
	ZEPHIR_INIT(AppKit_NS_NSButtonCell_NSButtonCell);
	ZEPHIR_INIT(AppKit_NS_NSButton_NSButton);
	ZEPHIR_INIT(AppKit_NS_NSCIImageRep_NSCIImageRep);
	ZEPHIR_INIT(AppKit_NS_NSCachedImageRep_NSCachedImageRep);
	ZEPHIR_INIT(AppKit_NS_NSCell_NSCell);
	ZEPHIR_INIT(AppKit_NS_NSClickGestureRecognizer_NSClickGestureRecognizer);
	ZEPHIR_INIT(AppKit_NS_NSClipView_NSClipView);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewDiffableDataSource_NSCollectionViewDiffableDataSource);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewFlowLayout_NSCollectionViewFlowLayout);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewGridLayout_NSCollectionViewGridLayout);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout);
	ZEPHIR_INIT(AppKit_NS_NSCollectionViewTransitionLayout_NSCollectionViewTransitionLayout);
	ZEPHIR_INIT(AppKit_NS_NSCollectionView_NSCollectionView);
	ZEPHIR_INIT(AppKit_NS_NSColorList_NSColorList);
	ZEPHIR_INIT(AppKit_NS_NSColorPanel_NSColorPanel);
	ZEPHIR_INIT(AppKit_NS_NSColorPicker_NSColorPicker);
	ZEPHIR_INIT(AppKit_NS_NSColorSampler_NSColorSampler);
	ZEPHIR_INIT(AppKit_NS_NSColorSpace_NSColorSpace);
	ZEPHIR_INIT(AppKit_NS_NSColorWell_NSColorWell);
	ZEPHIR_INIT(AppKit_NS_NSColor_NSColor);
	ZEPHIR_INIT(AppKit_NS_NSComboBox_NSComboBox);
	ZEPHIR_INIT(AppKit_NS_NSComboButton_NSComboButton);
	ZEPHIR_INIT(AppKit_NS_NSControl_NSControl);
	ZEPHIR_INIT(AppKit_NS_NSController_NSController);
	ZEPHIR_INIT(AppKit_NS_NSCursor_NSCursor);
	ZEPHIR_INIT(AppKit_NS_NSCustomImageRep_NSCustomImageRep);
	ZEPHIR_INIT(AppKit_NS_NSDatePicker_NSDatePicker);
	ZEPHIR_INIT(AppKit_NS_NSDictionary_NSDictionary);
	ZEPHIR_INIT(AppKit_NS_NSEPSImageRep_NSEPSImageRep);
	ZEPHIR_INIT(AppKit_NS_NSEvent_NSEvent);
	ZEPHIR_INIT(AppKit_NS_NSFontCollection_NSFontCollection);
	ZEPHIR_INIT(AppKit_NS_NSFontDescriptor_NSFontDescriptor);
	ZEPHIR_INIT(AppKit_NS_NSFontManager_NSFontManager);
	ZEPHIR_INIT(AppKit_NS_NSFontPanel_NSFontPanel);
	ZEPHIR_INIT(AppKit_NS_NSFont_NSFont);
	ZEPHIR_INIT(AppKit_NS_NSFormCell_NSFormCell);
	ZEPHIR_INIT(AppKit_NS_NSForm_NSForm);
	ZEPHIR_INIT(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer);
	ZEPHIR_INIT(AppKit_NS_NSGlyphGenerator_NSGlyphGenerator);
	ZEPHIR_INIT(AppKit_NS_NSGradient_NSGradient);
	ZEPHIR_INIT(AppKit_NS_NSGraphicsContext_NSGraphicsContext);
	ZEPHIR_INIT(AppKit_NS_NSGridCell_NSGridCell);
	ZEPHIR_INIT(AppKit_NS_NSGridColumn_NSGridColumn);
	ZEPHIR_INIT(AppKit_NS_NSGridRow_NSGridRow);
	ZEPHIR_INIT(AppKit_NS_NSGridView_NSGridView);
	ZEPHIR_INIT(AppKit_NS_NSImageRep_NSImageRep);
	ZEPHIR_INIT(AppKit_NS_NSImageView_NSImageView);
	ZEPHIR_INIT(AppKit_NS_NSImage_NSImage);
	ZEPHIR_INIT(AppKit_NS_NSLayoutManager_NSLayoutManager);
	ZEPHIR_INIT(AppKit_NS_NSLevelIndicatorCell_NSLevelIndicatorCell);
	ZEPHIR_INIT(AppKit_NS_NSLevelIndicator_NSLevelIndicator);
	ZEPHIR_INIT(AppKit_NS_NSMagnificationGestureRecognizer_NSMagnificationGestureRecognizer);
	ZEPHIR_INIT(AppKit_NS_NSMatrix_NSMatrix);
	ZEPHIR_INIT(AppKit_NS_NSMenuItem_NSMenuItem);
	ZEPHIR_INIT(AppKit_NS_NSMenuToolbarItem_NSMenuToolbarItem);
	ZEPHIR_INIT(AppKit_NS_NSMenu_NSMenu);
	ZEPHIR_INIT(AppKit_NS_NSOpenPanel_NSOpenPanel);
	ZEPHIR_INIT(AppKit_NS_NSOutlineView_NSOutlineView);
	ZEPHIR_INIT(AppKit_NS_NSPDFImageRep_NSPDFImageRep);
	ZEPHIR_INIT(AppKit_NS_NSPageController_NSPageController);
	ZEPHIR_INIT(AppKit_NS_NSPanGestureRecognizer_NSPanGestureRecognizer);
	ZEPHIR_INIT(AppKit_NS_NSPanel_NSPanel);
	ZEPHIR_INIT(AppKit_NS_NSParagraphStyle_NSParagraphStyle);
	ZEPHIR_INIT(AppKit_NS_NSPathCell_NSPathCell);
	ZEPHIR_INIT(AppKit_NS_NSPathComponentCell_NSPathComponentCell);
	ZEPHIR_INIT(AppKit_NS_NSPathControl_NSPathControl);
	ZEPHIR_INIT(AppKit_NS_NSPopUpButtonCell_NSPopUpButtonCell);
	ZEPHIR_INIT(AppKit_NS_NSPopUpButton_NSPopUpButton);
	ZEPHIR_INIT(AppKit_NS_NSPopover_NSPopover);
	ZEPHIR_INIT(AppKit_NS_NSPredicateEditor_NSPredicateEditor);
	ZEPHIR_INIT(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer);
	ZEPHIR_INIT(AppKit_NS_NSProgressIndicator_NSProgressIndicator);
	ZEPHIR_INIT(AppKit_NS_NSResponder_NSResponder);
	ZEPHIR_INIT(AppKit_NS_NSRotationGestureRecognizer_NSRotationGestureRecognizer);
	ZEPHIR_INIT(AppKit_NS_NSRuleEditor_NSRuleEditor);
	ZEPHIR_INIT(AppKit_NS_NSRulerMarker_NSRulerMarker);
	ZEPHIR_INIT(AppKit_NS_NSRulerView_NSRulerView);
	ZEPHIR_INIT(AppKit_NS_NSSavePanel_NSSavePanel);
	ZEPHIR_INIT(AppKit_NS_NSScreen_NSScreen);
	ZEPHIR_INIT(AppKit_NS_NSScrollView_NSScrollView);
	ZEPHIR_INIT(AppKit_NS_NSScroller_NSScroller);
	ZEPHIR_INIT(AppKit_NS_NSScrubber_NSScrubber);
	ZEPHIR_INIT(AppKit_NS_NSSearchFieldCell_NSSearchFieldCell);
	ZEPHIR_INIT(AppKit_NS_NSSearchField_NSSearchField);
	ZEPHIR_INIT(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell);
	ZEPHIR_INIT(AppKit_NS_NSSecureTextField_NSSecureTextField);
	ZEPHIR_INIT(AppKit_NS_NSSegmentedCell_NSSegmentedCell);
	ZEPHIR_INIT(AppKit_NS_NSSegmentedControl_NSSegmentedControl);
	ZEPHIR_INIT(AppKit_NS_NSShadow_NSShadow);
	ZEPHIR_INIT(AppKit_NS_NSSliderCell_NSSliderCell);
	ZEPHIR_INIT(AppKit_NS_NSSlider_NSSlider);
	ZEPHIR_INIT(AppKit_NS_NSSpellChecker_NSSpellChecker);
	ZEPHIR_INIT(AppKit_NS_NSSplitViewController_NSSplitViewController);
	ZEPHIR_INIT(AppKit_NS_NSSplitViewItem_NSSplitViewItem);
	ZEPHIR_INIT(AppKit_NS_NSSplitView_NSSplitView);
	ZEPHIR_INIT(AppKit_NS_NSStackView_NSStackView);
	ZEPHIR_INIT(AppKit_NS_NSStatusBarButton_NSStatusBarButton);
	ZEPHIR_INIT(AppKit_NS_NSStatusBar_NSStatusBar);
	ZEPHIR_INIT(AppKit_NS_NSStatusItem_NSStatusItem);
	ZEPHIR_INIT(AppKit_NS_NSStepperCell_NSStepperCell);
	ZEPHIR_INIT(AppKit_NS_NSStepper_NSStepper);
	ZEPHIR_INIT(AppKit_NS_NSSwitch_NSSwitch);
	ZEPHIR_INIT(AppKit_NS_NSTabViewController_NSTabViewController);
	ZEPHIR_INIT(AppKit_NS_NSTabViewItem_NSTabViewItem);
	ZEPHIR_INIT(AppKit_NS_NSTabView_NSTabView);
	ZEPHIR_INIT(AppKit_NS_NSTableCellView_NSTableCellView);
	ZEPHIR_INIT(AppKit_NS_NSTableColumn_NSTableColumn);
	ZEPHIR_INIT(AppKit_NS_NSTableHeaderCell_NSTableHeaderCell);
	ZEPHIR_INIT(AppKit_NS_NSTableHeaderView_NSTableHeaderView);
	ZEPHIR_INIT(AppKit_NS_NSTableRowView_NSTableRowView);
	ZEPHIR_INIT(AppKit_NS_NSTableViewDiffableDataSource_NSTableViewDiffableDataSource);
	ZEPHIR_INIT(AppKit_NS_NSTableView_NSTableView);
	ZEPHIR_INIT(AppKit_NS_NSTextAttachmentCell_NSTextAttachmentCell);
	ZEPHIR_INIT(AppKit_NS_NSTextAttachment_NSTextAttachment);
	ZEPHIR_INIT(AppKit_NS_NSTextBlock_NSTextBlock);
	ZEPHIR_INIT(AppKit_NS_NSTextCheckingController_NSTextCheckingController);
	ZEPHIR_INIT(AppKit_NS_NSTextContainer_NSTextContainer);
	ZEPHIR_INIT(AppKit_NS_NSTextContentManager_NSTextContentManager);
	ZEPHIR_INIT(AppKit_NS_NSTextContentStorage_NSTextContentStorage);
	ZEPHIR_INIT(AppKit_NS_NSTextElement_NSTextElement);
	ZEPHIR_INIT(AppKit_NS_NSTextFieldCell_NSTextFieldCell);
	ZEPHIR_INIT(AppKit_NS_NSTextField_NSTextField);
	ZEPHIR_INIT(AppKit_NS_NSTextFinder_NSTextFinder);
	ZEPHIR_INIT(AppKit_NS_NSTextInputContext_NSTextInputContext);
	ZEPHIR_INIT(AppKit_NS_NSTextInsertionIndicator_NSTextInsertionIndicator);
	ZEPHIR_INIT(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment);
	ZEPHIR_INIT(AppKit_NS_NSTextLayoutManager_NSTextLayoutManager);
	ZEPHIR_INIT(AppKit_NS_NSTextLineFragment_NSTextLineFragment);
	ZEPHIR_INIT(AppKit_NS_NSTextList_NSTextList);
	ZEPHIR_INIT(AppKit_NS_NSTextParagraph_NSTextParagraph);
	ZEPHIR_INIT(AppKit_NS_NSTextSelection_NSTextSelection);
	ZEPHIR_INIT(AppKit_NS_NSTextStorage_NSTextStorage);
	ZEPHIR_INIT(AppKit_NS_NSTextTable_NSTextTable);
	ZEPHIR_INIT(AppKit_NS_NSTextView_NSTextView);
	ZEPHIR_INIT(AppKit_NS_NSTextViewportLayoutController_NSTextViewportLayoutController);
	ZEPHIR_INIT(AppKit_NS_NSText_NSText);
	ZEPHIR_INIT(AppKit_NS_NSTokenFieldCell_NSTokenFieldCell);
	ZEPHIR_INIT(AppKit_NS_NSTokenField_NSTokenField);
	ZEPHIR_INIT(AppKit_NS_NSToolbar_NSToolbar);
	ZEPHIR_INIT(AppKit_NS_NSTouch_NSTouch);
	ZEPHIR_INIT(AppKit_NS_NSTrackingArea_NSTrackingArea);
	ZEPHIR_INIT(AppKit_NS_NSTypesetter_NSTypesetter);
	ZEPHIR_INIT(AppKit_NS_NSViewAnimation_NSViewAnimation);
	ZEPHIR_INIT(AppKit_NS_NSViewController_NSViewController);
	ZEPHIR_INIT(AppKit_NS_NSView_NSView);
	ZEPHIR_INIT(AppKit_NS_NSVisualEffectView_NSVisualEffectView);
	ZEPHIR_INIT(AppKit_NS_NSWindowController_NSWindowController);
	ZEPHIR_INIT(AppKit_NS_NSWindow_NSWindow);
	ZEPHIR_INIT(AppKit_NS_NSWorkspace_NSWorkspace);
	
	return SUCCESS;
}

#ifndef ZEPHIR_RELEASE
static PHP_MSHUTDOWN_FUNCTION(appkit)
{
	
	zephir_deinitialize_memory();
	UNREGISTER_INI_ENTRIES();
	return SUCCESS;
}
#endif

/**
 * Initialize globals on each request or each thread started
 */
static void php_zephir_init_globals(zend_appkit_globals *appkit_globals)
{
	appkit_globals->initialized = 0;

	/* Cache Enabled */
	appkit_globals->cache_enabled = 1;

	/* Recursive Lock */
	appkit_globals->recursive_lock = 0;

	/* Static cache */
	memset(appkit_globals->scache, '\0', sizeof(zephir_fcall_cache_entry*) * ZEPHIR_MAX_CACHE_SLOTS);

	
	
}

/**
 * Initialize globals only on each thread started
 */
static void php_zephir_init_module_globals(zend_appkit_globals *appkit_globals)
{
	
}

static PHP_RINIT_FUNCTION(appkit)
{
	zend_appkit_globals *appkit_globals_ptr;
	appkit_globals_ptr = ZEPHIR_VGLOBAL;

	php_zephir_init_globals(appkit_globals_ptr);
	zephir_initialize_memory(appkit_globals_ptr);

	
	return SUCCESS;
}

static PHP_RSHUTDOWN_FUNCTION(appkit)
{
	
	zephir_deinitialize_memory();
	return SUCCESS;
}



static PHP_MINFO_FUNCTION(appkit)
{
	php_info_print_box_start(0);
	php_printf("%s", PHP_APPKIT_DESCRIPTION);
	php_info_print_box_end();

	php_info_print_table_start();
	php_info_print_table_header(2, PHP_APPKIT_NAME, "enabled");
	php_info_print_table_row(2, "Author", PHP_APPKIT_AUTHOR);
	php_info_print_table_row(2, "Version", PHP_APPKIT_VERSION);
	php_info_print_table_row(2, "Build Date", __DATE__ " " __TIME__ );
	php_info_print_table_row(2, "Powered by Zephir", "Version " PHP_APPKIT_ZEPVERSION);
	php_info_print_table_end();
	
	DISPLAY_INI_ENTRIES();
}

static PHP_GINIT_FUNCTION(appkit)
{
#if defined(COMPILE_DL_APPKIT) && defined(ZTS)
	ZEND_TSRMLS_CACHE_UPDATE();
#endif

	php_zephir_init_globals(appkit_globals);
	php_zephir_init_module_globals(appkit_globals);
}

static PHP_GSHUTDOWN_FUNCTION(appkit)
{
	
}


zend_function_entry php_appkit_functions[] = {
	ZEND_FE_END

};

static const zend_module_dep php_appkit_deps[] = {
	
	ZEND_MOD_END
};

zend_module_entry appkit_module_entry = {
	STANDARD_MODULE_HEADER_EX,
	NULL,
	php_appkit_deps,
	PHP_APPKIT_EXTNAME,
	php_appkit_functions,
	PHP_MINIT(appkit),
#ifndef ZEPHIR_RELEASE
	PHP_MSHUTDOWN(appkit),
#else
	NULL,
#endif
	PHP_RINIT(appkit),
	PHP_RSHUTDOWN(appkit),
	PHP_MINFO(appkit),
	PHP_APPKIT_VERSION,
	ZEND_MODULE_GLOBALS(appkit),
	PHP_GINIT(appkit),
	PHP_GSHUTDOWN(appkit),
#ifdef ZEPHIR_POST_REQUEST
	PHP_PRSHUTDOWN(appkit),
#else
	NULL,
#endif
	STANDARD_MODULE_PROPERTIES_EX
};

/* implement standard "stub" routine to introduce ourselves to Zend */
#ifdef COMPILE_DL_APPKIT
# ifdef ZTS
ZEND_TSRMLS_CACHE_DEFINE()
# endif
ZEND_GET_MODULE(appkit)
#endif
