
extern zend_class_entry *appkit_ns_nscollectionviewitem_nscollectionviewitem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem);

PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, initWithNibNameBundle);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, collectionView);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, isSelected);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setSelected);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, highlightState);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setHighlightState);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, imageView);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setImageView);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, textField);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setTextField);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, draggingImageComponents);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_initwithnibnamebundle, 0, 2, IS_LONG, 0)
	ZEND_ARG_INFO(0, nibName)
	ZEND_ARG_TYPE_INFO(0, bundle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_collectionview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_isselected, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setselected, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, selected, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_highlightstate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_sethighlightstate, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, highlightState, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_imageview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setimageview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, imageView, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_textfield, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_settextfield, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, textField, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_draggingimagecomponents, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewitem_nscollectionviewitem_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, initWithNibNameBundle, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_initwithnibnamebundle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, collectionView, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_collectionview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, isSelected, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_isselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setSelected, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, highlightState, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_highlightstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setHighlightState, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_sethighlightstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, imageView, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_imageview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setImageView, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setimageview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, textField, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_textfield, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setTextField, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_settextfield, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, draggingImageComponents, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_draggingimagecomponents, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
