
extern zend_class_entry *appkit_ns_nscollectionviewitem_nscollectionviewitem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem);

PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, create);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, wrap);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, destroy);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, nsCollectionViewItem);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setView);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, view);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setTitle);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, getTitle);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setText);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, getText);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setSelected);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, isSelected);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setHighlightState);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, getHighlightState);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, textField);
PHP_METHOD(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, imageView);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsCollectionViewItemPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_nscollectionviewitem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_view, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_settitle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, title, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_gettitle, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_settext, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_gettext, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setselected, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_isselected, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_sethighlightstate, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, state, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_gethighlightstate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_textfield, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_imageview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewitem_nscollectionviewitem_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, create, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, wrap, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, destroy, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, nsCollectionViewItem, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_nscollectionviewitem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setView, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, view, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_view, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setTitle, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_settitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, getTitle, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_gettitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setText, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_settext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, getText, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_gettext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setSelected, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_setselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, isSelected, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_isselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, setHighlightState, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_sethighlightstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, getHighlightState, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_gethighlightstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, textField, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_textfield, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewItem_NSCollectionViewItem, imageView, arginfo_appkit_ns_nscollectionviewitem_nscollectionviewitem_imageview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
