
extern zend_class_entry *appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext);

PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, init);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, invalidateFlowLayoutDelegateMetrics);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, setInvalidateFlowLayoutDelegateMetrics);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, invalidateFlowLayoutAttributes);
PHP_METHOD(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, setInvalidateFlowLayoutAttributes);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_init, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_invalidateflowlayoutdelegatemetrics, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_setinvalidateflowlayoutdelegatemetrics, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, invalidateFlowLayoutDelegateMetrics, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_invalidateflowlayoutattributes, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_setinvalidateflowlayoutattributes, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, invalidateFlowLayoutAttributes, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, init, arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_init, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, invalidateFlowLayoutDelegateMetrics, arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_invalidateflowlayoutdelegatemetrics, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, setInvalidateFlowLayoutDelegateMetrics, arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_setinvalidateflowlayoutdelegatemetrics, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, invalidateFlowLayoutAttributes, arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_invalidateflowlayoutattributes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewFlowLayoutInvalidationContext_NSCollectionViewFlowLayoutInvalidationContext, setInvalidateFlowLayoutAttributes, arginfo_appkit_ns_nscollectionviewflowlayoutinvalidationcontext_nscollectionviewflowlayoutinvalidationcontext_setinvalidateflowlayoutattributes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
