
extern zend_class_entry *appkit_ns_nstextlinefragment_nstextlinefragment_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTextLineFragment_NSTextLineFragment);

PHP_METHOD(AppKit_NS_NSTextLineFragment_NSTextLineFragment, createWithString);
PHP_METHOD(AppKit_NS_NSTextLineFragment_NSTextLineFragment, wrap);
PHP_METHOD(AppKit_NS_NSTextLineFragment_NSTextLineFragment, destroy);
PHP_METHOD(AppKit_NS_NSTextLineFragment_NSTextLineFragment, characterRange);
PHP_METHOD(AppKit_NS_NSTextLineFragment_NSTextLineFragment, typographicBounds);
PHP_METHOD(AppKit_NS_NSTextLineFragment_NSTextLineFragment, glyphOrigin);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_createwithstring, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTextLineFragmentPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_characterrange, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_typographicbounds, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_glyphorigin, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstextlinefragment_nstextlinefragment_method_entry) {
	PHP_ME(AppKit_NS_NSTextLineFragment_NSTextLineFragment, createWithString, arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_createwithstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLineFragment_NSTextLineFragment, wrap, arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLineFragment_NSTextLineFragment, destroy, arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLineFragment_NSTextLineFragment, characterRange, arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_characterrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLineFragment_NSTextLineFragment, typographicBounds, arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_typographicbounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLineFragment_NSTextLineFragment, glyphOrigin, arginfo_appkit_ns_nstextlinefragment_nstextlinefragment_glyphorigin, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
