
extern zend_class_entry *appkit_ns_nstabviewcontroller_nstabviewcontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTabViewController_NSTabViewController);

PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, create);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, wrap);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, destroy);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, nsTabViewController);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, setTabStyle);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, getTabStyle);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, setSelectedTabViewItemIndex);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, getSelectedTabViewItemIndex);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, addTabViewItem);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, removeTabViewItem);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, tabViewItemCount);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, tabView);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, setCanPropagateSelectedChildViewControllerTitle);
PHP_METHOD(AppKit_NS_NSTabViewController_NSTabViewController, canPropagateSelectedChildViewControllerTitle);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTabViewControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_nstabviewcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_settabstyle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, style, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_gettabstyle, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_setselectedtabviewitemindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_getselectedtabviewitemindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_addtabviewitem, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_removetabviewitem, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_tabviewitemcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_tabview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_setcanpropagateselectedchildviewcontrollertitle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, flag, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_canpropagateselectedchildviewcontrollertitle, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstabviewcontroller_nstabviewcontroller_method_entry) {
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, create, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, wrap, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, destroy, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, nsTabViewController, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_nstabviewcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, setTabStyle, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_settabstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, getTabStyle, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_gettabstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, setSelectedTabViewItemIndex, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_setselectedtabviewitemindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, getSelectedTabViewItemIndex, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_getselectedtabviewitemindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, addTabViewItem, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_addtabviewitem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, removeTabViewItem, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_removetabviewitem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, tabViewItemCount, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_tabviewitemcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, tabView, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_tabview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, setCanPropagateSelectedChildViewControllerTitle, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_setcanpropagateselectedchildviewcontrollertitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTabViewController_NSTabViewController, canPropagateSelectedChildViewControllerTitle, arginfo_appkit_ns_nstabviewcontroller_nstabviewcontroller_canpropagateselectedchildviewcontrollertitle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
