
extern zend_class_entry *appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell);

PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, initTextCell);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, echosBullets);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setEchosBullets);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_inittextcell, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, string_, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_echosbullets, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setechosbullets, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, echosBullets, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_method_entry) {
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, initTextCell, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_inittextcell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, echosBullets, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_echosbullets, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setEchosBullets, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setechosbullets, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
