
extern zend_class_entry *appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell);

PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, createText);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, wrap);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, destroy);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, nsSecureTextFieldCell);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setEchosBullets);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, echosBullets);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setStringValue);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, getStringValue);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setPlaceholderString);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, getPlaceholderString);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setBezelStyle);
PHP_METHOD(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, getBezelStyle);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_createtext, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsSecureTextFieldCellPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_nssecuretextfieldcell, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setechosbullets, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, echosBullets, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_echosbullets, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setstringvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_getstringvalue, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setplaceholderstring, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, placeholder, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_getplaceholderstring, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setbezelstyle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, style, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_getbezelstyle, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cell, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_method_entry) {
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, createText, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_createtext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, wrap, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, destroy, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, nsSecureTextFieldCell, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_nssecuretextfieldcell, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setEchosBullets, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setechosbullets, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, echosBullets, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_echosbullets, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setStringValue, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setstringvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, getStringValue, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_getstringvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setPlaceholderString, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setplaceholderstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, getPlaceholderString, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_getplaceholderstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, setBezelStyle, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_setbezelstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSecureTextFieldCell_NSSecureTextFieldCell, getBezelStyle, arginfo_appkit_ns_nssecuretextfieldcell_nssecuretextfieldcell_getbezelstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
