
extern zend_class_entry *appkit_ns_nspagecontroller_nspagecontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSPageController_NSPageController);

PHP_METHOD(AppKit_NS_NSPageController_NSPageController, create);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, wrap);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, destroy);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, nsPageController);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, setTransitionStyle);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, getTransitionStyle);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, setSelectedIndex);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, getSelectedIndex);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, arrangedObjectCount);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, navigateForwardToObject);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, navigateBack);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, navigateForward);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, completeTransition);
PHP_METHOD(AppKit_NS_NSPageController_NSPageController, selectedViewController);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsPageControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_nspagecontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_settransitionstyle, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, style, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_gettransitionstyle, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_setselectedindex, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_getselectedindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_arrangedobjectcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_navigateforwardtoobject, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, objectId, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_navigateback, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_navigateforward, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_completetransition, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspagecontroller_nspagecontroller_selectedviewcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nspagecontroller_nspagecontroller_method_entry) {
	PHP_ME(AppKit_NS_NSPageController_NSPageController, create, arginfo_appkit_ns_nspagecontroller_nspagecontroller_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, wrap, arginfo_appkit_ns_nspagecontroller_nspagecontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, destroy, arginfo_appkit_ns_nspagecontroller_nspagecontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, nsPageController, arginfo_appkit_ns_nspagecontroller_nspagecontroller_nspagecontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, setTransitionStyle, arginfo_appkit_ns_nspagecontroller_nspagecontroller_settransitionstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, getTransitionStyle, arginfo_appkit_ns_nspagecontroller_nspagecontroller_gettransitionstyle, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, setSelectedIndex, arginfo_appkit_ns_nspagecontroller_nspagecontroller_setselectedindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, getSelectedIndex, arginfo_appkit_ns_nspagecontroller_nspagecontroller_getselectedindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, arrangedObjectCount, arginfo_appkit_ns_nspagecontroller_nspagecontroller_arrangedobjectcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, navigateForwardToObject, arginfo_appkit_ns_nspagecontroller_nspagecontroller_navigateforwardtoobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, navigateBack, arginfo_appkit_ns_nspagecontroller_nspagecontroller_navigateback, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, navigateForward, arginfo_appkit_ns_nspagecontroller_nspagecontroller_navigateforward, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, completeTransition, arginfo_appkit_ns_nspagecontroller_nspagecontroller_completetransition, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPageController_NSPageController, selectedViewController, arginfo_appkit_ns_nspagecontroller_nspagecontroller_selectedviewcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
