
extern zend_class_entry *appkit_ns_nsgesturerecognizer_nsgesturerecognizer_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer);

PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, create);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, wrap);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, destroy);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, setEnabled);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, isEnabled);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, state);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, addToView);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, removeFromView);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, locationInView);
PHP_METHOD(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, nsGestureRecognizer);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsGestureRecognizerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_setenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, enabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_isenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_state, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_addtoview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_removefromview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_locationinview, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_nsgesturerecognizer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsgesturerecognizer_nsgesturerecognizer_method_entry) {
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, create, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, wrap, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, destroy, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, setEnabled, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_setenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, isEnabled, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_isenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, state, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_state, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, addToView, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_addtoview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, removeFromView, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_removefromview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, locationInView, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_locationinview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGestureRecognizer_NSGestureRecognizer, nsGestureRecognizer, arginfo_appkit_ns_nsgesturerecognizer_nsgesturerecognizer_nsgesturerecognizer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
