// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSecureTextField;

class NSSecureTextField
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nssecuretextfield_init_with_frame(x, y, width, height);
    }
}
