// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSTextContainer;

class NSTextContainer
{
    public static function initWithSize(double width, double height) -> int
    {
        return nstextcontainer_init_with_size(width, height);
    }

    public static function textLayoutManager(int handle) -> int
    {
        return nstextcontainer_text_layout_manager(handle);
    }

    public static function size(int handle) -> array
    {
        var result;

        let result = nstextcontainer_size(handle);

        return result;
    }

    public static function setSize(int handle, double width, double height) -> void
    {
        nstextcontainer_set_size(handle, width, height);
    }

    public static function lineBreakMode(int handle) -> int
    {
        return nstextcontainer_line_break_mode(handle);
    }

    public static function setLineBreakMode(int handle, int lineBreakMode) -> void
    {
        nstextcontainer_set_line_break_mode(handle, lineBreakMode);
    }

    public static function lineFragmentPadding(int handle) -> double
    {
        return nstextcontainer_line_fragment_padding(handle);
    }

    public static function setLineFragmentPadding(int handle, double lineFragmentPadding) -> void
    {
        nstextcontainer_set_line_fragment_padding(handle, lineFragmentPadding);
    }

    public static function maximumNumberOfLines(int handle) -> int
    {
        return nstextcontainer_maximum_number_of_lines(handle);
    }

    public static function setMaximumNumberOfLines(int handle, int maximumNumberOfLines) -> void
    {
        nstextcontainer_set_maximum_number_of_lines(handle, maximumNumberOfLines);
    }

    public static function lineFragmentRectForProposedRectAtIndexWritingDirectionRemainingRect(int handle, double x, double y, double width, double height, int characterIndex, int baseWritingDirection) -> array
    {
        var result;

        let result = nstextcontainer_line_fragment_rect_for_proposed_rect_at_index_writing_direction_remaining_rect(handle, x, y, width, height, characterIndex, baseWritingDirection);

        return result;
    }

    public static function isSimpleRectangularTextContainer(int handle) -> bool
    {
        int r;

        let r = nstextcontainer_is_simple_rectangular_text_container(handle);

        return r == 1;
    }

    public static function widthTracksTextView(int handle) -> bool
    {
        int r;

        let r = nstextcontainer_width_tracks_text_view(handle);

        return r == 1;
    }

    public static function setWidthTracksTextView(int handle, bool widthTracksTextView) -> void
    {
        nstextcontainer_set_width_tracks_text_view(handle, widthTracksTextView);
    }

    public static function heightTracksTextView(int handle) -> bool
    {
        int r;

        let r = nstextcontainer_height_tracks_text_view(handle);

        return r == 1;
    }

    public static function setHeightTracksTextView(int handle, bool heightTracksTextView) -> void
    {
        nstextcontainer_set_height_tracks_text_view(handle, heightTracksTextView);
    }

    public static function layoutManager(int handle) -> int
    {
        return nstextcontainer_layout_manager(handle);
    }

    public static function setLayoutManager(int handle, int layoutManager) -> void
    {
        nstextcontainer_set_layout_manager(handle, layoutManager);
    }

    public static function replaceLayoutManager(int handle, int newLayoutManager) -> void
    {
        nstextcontainer_replace_layout_manager(handle, newLayoutManager);
    }

    public static function exclusionPaths(int handle) -> array
    {
        var result;

        let result = nstextcontainer_exclusion_paths(handle);

        return result;
    }

    public static function setExclusionPaths(int handle, array exclusionPaths) -> void
    {
        nstextcontainer_set_exclusion_paths(handle, exclusionPaths);
    }

    public static function textView(int handle) -> int
    {
        return nstextcontainer_text_view(handle);
    }

    public static function setTextView(int handle, int textView) -> void
    {
        nstextcontainer_set_text_view(handle, textView);
    }

    public static function initWithContainerSize(double width, double height) -> int
    {
        return nstextcontainer_init_with_container_size(width, height);
    }

    public static function containerSize(int handle) -> array
    {
        var result;

        let result = nstextcontainer_container_size(handle);

        return result;
    }

    public static function setContainerSize(int handle, double width, double height) -> void
    {
        nstextcontainer_set_container_size(handle, width, height);
    }

    public static function lineFragmentRectForProposedRectSweepDirectionMovementDirectionRemainingRect(int handle, double x, double y, double width, double height, int sweepDirection, int movementDirection) -> array
    {
        var result;

        let result = nstextcontainer_line_fragment_rect_for_proposed_rect_sweep_direction_movement_direction_remaining_rect(handle, x, y, width, height, sweepDirection, movementDirection);

        return result;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
    // @reserved @property (nullable, strong) NSTextView *textView — pre-10.12 duplicate getter
    // @reserved @property (nullable, strong) NSTextView *textView — pre-10.12 duplicate setter
    // @reserved - (BOOL)containsPoint:(NSPoint)point API_DEPRECATED("", macos(10.0,10.11));

}
