// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSavePanel;

class NSSavePanel
{
    public static function savePanel() -> int
    {
        return nssavepanel_save_panel();
    }

    public static function Url(int handle) -> int
    {
        return nssavepanel_url(handle);
    }

    public static function identifier(int handle) -> var
    {
        var result;

        let result = nssavepanel_identifier(handle);

        return result;
    }

    public static function setIdentifier(int handle, var identifier) -> void
    {
        nssavepanel_set_identifier(handle, identifier);
    }

    public static function directoryURL(int handle) -> int
    {
        return nssavepanel_directory_url(handle);
    }

    public static function setDirectoryURL(int handle, int directoryURL) -> void
    {
        nssavepanel_set_directory_url(handle, directoryURL);
    }

    public static function allowedContentTypes(int handle) -> array
    {
        var result;

        let result = nssavepanel_allowed_content_types(handle);

        return result;
    }

    public static function setAllowedContentTypes(int handle, array allowedContentTypes) -> void
    {
        nssavepanel_set_allowed_content_types(handle, allowedContentTypes);
    }

    public static function allowsOtherFileTypes(int handle) -> bool
    {
        int r;

        let r = nssavepanel_allows_other_file_types(handle);

        return r == 1;
    }

    public static function setAllowsOtherFileTypes(int handle, bool allowsOtherFileTypes) -> void
    {
        nssavepanel_set_allows_other_file_types(handle, allowsOtherFileTypes);
    }

    public static function currentContentType(int handle) -> int
    {
        return nssavepanel_current_content_type(handle);
    }

    public static function setCurrentContentType(int handle, int currentContentType) -> void
    {
        nssavepanel_set_current_content_type(handle, currentContentType);
    }

    public static function accessoryView(int handle) -> int
    {
        return nssavepanel_accessory_view(handle);
    }

    public static function setAccessoryView(int handle, int accessoryView) -> void
    {
        nssavepanel_set_accessory_view(handle, accessoryView);
    }

    public static function delegate(int handle) -> int
    {
        return nssavepanel_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nssavepanel_set_delegate(handle, delegate);
    }

    public static function isExpanded(int handle) -> bool
    {
        int r;

        let r = nssavepanel_is_expanded(handle);

        return r == 1;
    }

    public static function canCreateDirectories(int handle) -> bool
    {
        int r;

        let r = nssavepanel_can_create_directories(handle);

        return r == 1;
    }

    public static function setCanCreateDirectories(int handle, bool canCreateDirectories) -> void
    {
        nssavepanel_set_can_create_directories(handle, canCreateDirectories);
    }

    public static function canSelectHiddenExtension(int handle) -> bool
    {
        int r;

        let r = nssavepanel_can_select_hidden_extension(handle);

        return r == 1;
    }

    public static function setCanSelectHiddenExtension(int handle, bool canSelectHiddenExtension) -> void
    {
        nssavepanel_set_can_select_hidden_extension(handle, canSelectHiddenExtension);
    }

    public static function isExtensionHidden(int handle) -> bool
    {
        int r;

        let r = nssavepanel_is_extension_hidden(handle);

        return r == 1;
    }

    public static function setExtensionHidden(int handle, bool extensionHidden) -> void
    {
        nssavepanel_set_extension_hidden(handle, extensionHidden);
    }

    public static function treatsFilePackagesAsDirectories(int handle) -> bool
    {
        int r;

        let r = nssavepanel_treats_file_packages_as_directories(handle);

        return r == 1;
    }

    public static function setTreatsFilePackagesAsDirectories(int handle, bool treatsFilePackagesAsDirectories) -> void
    {
        nssavepanel_set_treats_file_packages_as_directories(handle, treatsFilePackagesAsDirectories);
    }

    public static function prompt(int handle) -> string
    {
        var result;

        let result = nssavepanel_prompt(handle);

        return result;
    }

    public static function setPrompt(int handle, string prompt) -> void
    {
        nssavepanel_set_prompt(handle, prompt);
    }

    public static function title(int handle) -> string
    {
        var result;

        let result = nssavepanel_title(handle);

        return result;
    }

    public static function setTitle(int handle, string title) -> void
    {
        nssavepanel_set_title(handle, title);
    }

    public static function nameFieldLabel(int handle) -> string
    {
        var result;

        let result = nssavepanel_name_field_label(handle);

        return result;
    }

    public static function setNameFieldLabel(int handle, string nameFieldLabel) -> void
    {
        nssavepanel_set_name_field_label(handle, nameFieldLabel);
    }

    public static function nameFieldStringValue(int handle) -> string
    {
        var result;

        let result = nssavepanel_name_field_string_value(handle);

        return result;
    }

    public static function setNameFieldStringValue(int handle, string nameFieldStringValue) -> void
    {
        nssavepanel_set_name_field_string_value(handle, nameFieldStringValue);
    }

    public static function message(int handle) -> string
    {
        var result;

        let result = nssavepanel_message(handle);

        return result;
    }

    public static function setMessage(int handle, string message) -> void
    {
        nssavepanel_set_message(handle, message);
    }

    public static function showsHiddenFiles(int handle) -> bool
    {
        int r;

        let r = nssavepanel_shows_hidden_files(handle);

        return r == 1;
    }

    public static function setShowsHiddenFiles(int handle, bool showsHiddenFiles) -> void
    {
        nssavepanel_set_shows_hidden_files(handle, showsHiddenFiles);
    }

    public static function showsTagField(int handle) -> bool
    {
        int r;

        let r = nssavepanel_shows_tag_field(handle);

        return r == 1;
    }

    public static function setShowsTagField(int handle, bool showsTagField) -> void
    {
        nssavepanel_set_shows_tag_field(handle, showsTagField);
    }

    public static function tagNames(int handle) -> array
    {
        var result;

        let result = nssavepanel_tag_names(handle);

        return result;
    }

    public static function setTagNames(int handle, array tagNames) -> void
    {
        nssavepanel_set_tag_names(handle, tagNames);
    }

    public static function showsContentTypes(int handle) -> bool
    {
        int r;

        let r = nssavepanel_shows_content_types(handle);

        return r == 1;
    }

    public static function setShowsContentTypes(int handle, bool showsContentTypes) -> void
    {
        nssavepanel_set_shows_content_types(handle, showsContentTypes);
    }

    public static function validateVisibleColumns(int handle) -> void
    {
        nssavepanel_validate_visible_columns(handle);
    }

    public static function ok(int handle, int sender) -> void
    {
        nssavepanel_ok(handle, sender);
    }

    public static function cancel(int handle, int sender) -> void
    {
        nssavepanel_cancel(handle, sender);
    }

    public static function runModal(int handle) -> int
    {
        return nssavepanel_run_modal(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (void)beginSheetModalForWindow:(NSWindow *)window completionHandler:(void (^)(NSModalResponse result))handler — block
    // @reserved - (void)beginWithCompletionHandler:(void (^)(NSModalResponse result))handler — block
    // @reserved - (NSString *)filename API_DEPRECATED
    // @reserved - (NSString *)directory API_DEPRECATED
    // @reserved - (void)setDirectory:(nullable NSString *)path API_DEPRECATED
    // @reserved - (nullable NSString *)requiredFileType API_DEPRECATED
    // @reserved - (void)setRequiredFileType:(nullable NSString *)type API_DEPRECATED
    // @reserved - (void)beginSheetForDirectory:file:modalForWindow:modalDelegate:didEndSelector:contextInfo: API_DEPRECATED
    // @reserved - (NSInteger)runModalForDirectory:(nullable NSString *)path file:(nullable NSString *)name API_DEPRECATED
    // @reserved - (IBAction)selectText:(nullable id)sender API_DEPRECATED
    // @reserved @property (nullable, copy) NSArray<NSString *> *allowedFileTypes API_DEPRECATED — getter
    // @reserved @property (nullable, copy) NSArray<NSString *> *allowedFileTypes API_DEPRECATED — setter

}
