
extern zend_class_entry *appkit_ns_nstextlayoutfragment_nstextlayoutfragment_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment);

PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, wrap);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, destroy);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, state);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, layoutFragmentFrame);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, renderingSurfaceBounds);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, textLineFragmentsCount);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, invalidateLayout);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, leadingPadding);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, trailingPadding);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, topMargin);
PHP_METHOD(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, bottomMargin);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTextLayoutFragmentPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_state, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_layoutfragmentframe, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_renderingsurfacebounds, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_textlinefragmentscount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_invalidatelayout, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_leadingpadding, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_trailingpadding, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_topmargin, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_bottommargin, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, fragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstextlayoutfragment_nstextlayoutfragment_method_entry) {
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, wrap, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, destroy, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, state, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_state, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, layoutFragmentFrame, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_layoutfragmentframe, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, renderingSurfaceBounds, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_renderingsurfacebounds, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, textLineFragmentsCount, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_textlinefragmentscount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, invalidateLayout, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_invalidatelayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, leadingPadding, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_leadingpadding, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, trailingPadding, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_trailingpadding, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, topMargin, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_topmargin, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextLayoutFragment_NSTextLayoutFragment, bottomMargin, arginfo_appkit_ns_nstextlayoutfragment_nstextlayoutfragment_bottommargin, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
