// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSplitView;

class NSSplitView
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nssplitview_init_with_frame(x, y, width, height);
    }

    public static function isVertical(int handle) -> bool
    {
        int r;

        let r = nssplitview_is_vertical(handle);

        return r == 1;
    }

    public static function setVertical(int handle, bool vertical) -> void
    {
        nssplitview_set_vertical(handle, vertical);
    }

    public static function dividerStyle(int handle) -> int
    {
        return nssplitview_divider_style(handle);
    }

    public static function setDividerStyle(int handle, int dividerStyle) -> void
    {
        nssplitview_set_divider_style(handle, dividerStyle);
    }

    public static function autosaveName(int handle) -> var
    {
        var result;

        let result = nssplitview_autosave_name(handle);

        return result;
    }

    public static function setAutosaveName(int handle, var autosaveName) -> void
    {
        nssplitview_set_autosave_name(handle, autosaveName);
    }

    public static function delegate(int handle) -> int
    {
        return nssplitview_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nssplitview_set_delegate(handle, delegate);
    }

    public static function drawDividerInRect(int handle, double x, double y, double width, double height) -> void
    {
        nssplitview_draw_divider_in_rect(handle, x, y, width, height);
    }

    public static function dividerColor(int handle) -> int
    {
        return nssplitview_divider_color(handle);
    }

    public static function dividerThickness(int handle) -> double
    {
        return nssplitview_divider_thickness(handle);
    }

    public static function adjustSubviews(int handle) -> void
    {
        nssplitview_adjust_subviews(handle);
    }

    public static function isSubviewCollapsed(int handle, int subview) -> bool
    {
        int r;

        let r = nssplitview_is_subview_collapsed(handle, subview);

        return r == 1;
    }

    public static function minPossiblePositionOfDividerAtIndex(int handle, int dividerIndex) -> double
    {
        return nssplitview_min_possible_position_of_divider_at_index(handle, dividerIndex);
    }

    public static function maxPossiblePositionOfDividerAtIndex(int handle, int dividerIndex) -> double
    {
        return nssplitview_max_possible_position_of_divider_at_index(handle, dividerIndex);
    }

    public static function setPositionOfDividerAtIndex(int handle, double position, int dividerIndex) -> void
    {
        nssplitview_set_position_of_divider_at_index(handle, position, dividerIndex);
    }

    public static function holdingPriorityForSubviewAtIndex(int handle, int subviewIndex) -> double
    {
        return nssplitview_holding_priority_for_subview_at_index(handle, subviewIndex);
    }

    public static function setHoldingPriorityForSubviewAtIndex(int handle, double priority, int subviewIndex) -> void
    {
        nssplitview_set_holding_priority_for_subview_at_index(handle, priority, subviewIndex);
    }

    public static function arrangesAllSubviews(int handle) -> bool
    {
        int r;

        let r = nssplitview_arranges_all_subviews(handle);

        return r == 1;
    }

    public static function setArrangesAllSubviews(int handle, bool arrangesAllSubviews) -> void
    {
        nssplitview_set_arranges_all_subviews(handle, arrangesAllSubviews);
    }

    public static function arrangedSubviews(int handle) -> array
    {
        var result;

        let result = nssplitview_arranged_subviews(handle);

        return result;
    }

    public static function addArrangedSubview(int handle, int view) -> void
    {
        nssplitview_add_arranged_subview(handle, view);
    }

    public static function insertArrangedSubviewAtIndex(int handle, int view, int index) -> void
    {
        nssplitview_insert_arranged_subview_at_index(handle, view, index);
    }

    public static function removeArrangedSubview(int handle, int view) -> void
    {
        nssplitview_remove_arranged_subview(handle, view);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (void)setIsPaneSplitter:(BOOL)flag API_DEPRECATED
    // @reserved - (BOOL)isPaneSplitter API_DEPRECATED

}
