
extern zend_class_entry *appkit_ns_nssharingservicepicker_nssharingservicepicker_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker);

PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, create);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, wrap);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, destroy);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, nsSharingServicePicker);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, showRelativeToRect);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, close);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, pollChosenService);
PHP_METHOD(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, standardShareMenuItem);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, strings, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsSharingServicePickerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, picker, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_nssharingservicepicker, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, picker, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_showrelativetorect, 0, 7, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, picker, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, preferredEdge, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_close, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, picker, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_pollchosenservice, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, picker, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_standardsharemenuitem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, picker, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssharingservicepicker_nssharingservicepicker_method_entry) {
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, create, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, wrap, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, destroy, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, nsSharingServicePicker, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_nssharingservicepicker, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, showRelativeToRect, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_showrelativetorect, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, close, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_close, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, pollChosenService, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_pollchosenservice, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePicker_NSSharingServicePicker, standardShareMenuItem, arginfo_appkit_ns_nssharingservicepicker_nssharingservicepicker_standardsharemenuitem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
