
extern zend_class_entry *appkit_ns_nscollectionviewlayout_nscollectionviewlayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout);

PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, init);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, collectionView);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidateLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidateLayoutWithContext);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, registerNibForDecorationViewOfKind);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForElementsInRect);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForItemAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForSupplementaryViewOfKindAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForDecorationViewOfKindAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForDropTargetAtPoint);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForInterItemGapBeforeIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, shouldInvalidateLayoutForBoundsChange);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidationContextForBoundsChange);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, shouldInvalidateLayoutForPreferredLayoutAttributesWithOriginalAttributes);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidationContextForPreferredLayoutAttributesWithOriginalAttributes);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, targetContentOffsetForProposedContentOffsetWithScrollingVelocity);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, targetContentOffsetForProposedContentOffset);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, collectionViewContentSize);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForCollectionViewUpdates);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalizeCollectionViewUpdates);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForAnimatedBoundsChange);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalizeAnimatedBoundsChange);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForTransitionToLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForTransitionFromLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalizeLayoutTransition);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, initialLayoutAttributesForAppearingItemAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalLayoutAttributesForDisappearingItemAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, initialLayoutAttributesForAppearingSupplementaryElementOfKindAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalLayoutAttributesForDisappearingSupplementaryElementOfKindAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, initialLayoutAttributesForAppearingDecorationElementOfKindAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalLayoutAttributesForDisappearingDecorationElementOfKindAtIndexPath);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToDeleteForSupplementaryViewOfKind);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToDeleteForDecorationViewOfKind);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToInsertForSupplementaryViewOfKind);
PHP_METHOD(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToInsertForDecorationViewOfKind);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_init, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_collectionview, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidatelayout, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidatelayoutwithcontext, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, context, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_registernibfordecorationviewofkind, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nib, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_preparelayout, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforelementsinrect, 0, 5, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforitematindexpath, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforsupplementaryviewofkindatindexpath, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesfordecorationviewofkindatindexpath, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesfordroptargetatpoint, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforinteritemgapbeforeindexpath, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, indexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_shouldinvalidatelayoutforboundschange, 0, 5, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidationcontextforboundschange, 0, 5, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_shouldinvalidatelayoutforpreferredlayoutattributeswithoriginalattributes, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, preferredAttributes, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, originalAttributes, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidationcontextforpreferredlayoutattributeswithoriginalattributes, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, preferredAttributes, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, originalAttributes, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_targetcontentoffsetforproposedcontentoffsetwithscrollingvelocity, 0, 5, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, velocityX, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, velocityY, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_targetcontentoffsetforproposedcontentoffset, 0, 3, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_collectionviewcontentsize, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_prepareforcollectionviewupdates, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, updateItems, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finalizecollectionviewupdates, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_prepareforanimatedboundschange, 0, 5, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, x, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, y, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, width, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, height, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finalizeanimatedboundschange, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_preparefortransitiontolayout, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, newLayout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_preparefortransitionfromlayout, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, oldLayout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finalizelayouttransition, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_initiallayoutattributesforappearingitematindexpath, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, itemIndexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finallayoutattributesfordisappearingitematindexpath, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, itemIndexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_initiallayoutattributesforappearingsupplementaryelementofkindatindexpath, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, elementIndexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finallayoutattributesfordisappearingsupplementaryelementofkindatindexpath, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, elementIndexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_initiallayoutattributesforappearingdecorationelementofkindatindexpath, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, decorationIndexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finallayoutattributesfordisappearingdecorationelementofkindatindexpath, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, decorationIndexPath, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstodeleteforsupplementaryviewofkind, 0, 2, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstodeletefordecorationviewofkind, 0, 2, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstoinsertforsupplementaryviewofkind, 0, 2, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstoinsertfordecorationviewofkind, 0, 2, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, elementKind, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewlayout_nscollectionviewlayout_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, init, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_init, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, collectionView, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_collectionview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidateLayout, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidatelayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidateLayoutWithContext, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidatelayoutwithcontext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, registerNibForDecorationViewOfKind, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_registernibfordecorationviewofkind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareLayout, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_preparelayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForElementsInRect, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforelementsinrect, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForItemAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforitematindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForSupplementaryViewOfKindAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforsupplementaryviewofkindatindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForDecorationViewOfKindAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesfordecorationviewofkindatindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForDropTargetAtPoint, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesfordroptargetatpoint, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, layoutAttributesForInterItemGapBeforeIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_layoutattributesforinteritemgapbeforeindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, shouldInvalidateLayoutForBoundsChange, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_shouldinvalidatelayoutforboundschange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidationContextForBoundsChange, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidationcontextforboundschange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, shouldInvalidateLayoutForPreferredLayoutAttributesWithOriginalAttributes, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_shouldinvalidatelayoutforpreferredlayoutattributeswithoriginalattributes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, invalidationContextForPreferredLayoutAttributesWithOriginalAttributes, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_invalidationcontextforpreferredlayoutattributeswithoriginalattributes, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, targetContentOffsetForProposedContentOffsetWithScrollingVelocity, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_targetcontentoffsetforproposedcontentoffsetwithscrollingvelocity, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, targetContentOffsetForProposedContentOffset, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_targetcontentoffsetforproposedcontentoffset, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, collectionViewContentSize, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_collectionviewcontentsize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForCollectionViewUpdates, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_prepareforcollectionviewupdates, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalizeCollectionViewUpdates, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finalizecollectionviewupdates, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForAnimatedBoundsChange, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_prepareforanimatedboundschange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalizeAnimatedBoundsChange, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finalizeanimatedboundschange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForTransitionToLayout, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_preparefortransitiontolayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, prepareForTransitionFromLayout, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_preparefortransitionfromlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalizeLayoutTransition, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finalizelayouttransition, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, initialLayoutAttributesForAppearingItemAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_initiallayoutattributesforappearingitematindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalLayoutAttributesForDisappearingItemAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finallayoutattributesfordisappearingitematindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, initialLayoutAttributesForAppearingSupplementaryElementOfKindAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_initiallayoutattributesforappearingsupplementaryelementofkindatindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalLayoutAttributesForDisappearingSupplementaryElementOfKindAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finallayoutattributesfordisappearingsupplementaryelementofkindatindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, initialLayoutAttributesForAppearingDecorationElementOfKindAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_initiallayoutattributesforappearingdecorationelementofkindatindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, finalLayoutAttributesForDisappearingDecorationElementOfKindAtIndexPath, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_finallayoutattributesfordisappearingdecorationelementofkindatindexpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToDeleteForSupplementaryViewOfKind, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstodeleteforsupplementaryviewofkind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToDeleteForDecorationViewOfKind, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstodeletefordecorationviewofkind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToInsertForSupplementaryViewOfKind, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstoinsertforsupplementaryviewofkind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewLayout_NSCollectionViewLayout, indexPathsToInsertForDecorationViewOfKind, arginfo_appkit_ns_nscollectionviewlayout_nscollectionviewlayout_indexpathstoinsertfordecorationviewofkind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
