// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSOutlineView;

class NSOutlineView
{
    public static function initWithFrame(double x, double y, double width, double height) -> int
    {
        return nsoutlineview_init_with_frame(x, y, width, height);
    }

    public static function delegate(int handle) -> int
    {
        return nsoutlineview_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nsoutlineview_set_delegate(handle, delegate);
    }

    public static function dataSource(int handle) -> int
    {
        return nsoutlineview_data_source(handle);
    }

    public static function setDataSource(int handle, int dataSource) -> void
    {
        nsoutlineview_set_data_source(handle, dataSource);
    }

    public static function outlineTableColumn(int handle) -> int
    {
        return nsoutlineview_outline_table_column(handle);
    }

    public static function setOutlineTableColumn(int handle, int outlineTableColumn) -> void
    {
        nsoutlineview_set_outline_table_column(handle, outlineTableColumn);
    }

    public static function isExpandable(int handle, int item) -> bool
    {
        int r;

        let r = nsoutlineview_is_expandable(handle, item);

        return r == 1;
    }

    public static function numberOfChildrenOfItem(int handle, int item) -> int
    {
        return nsoutlineview_number_of_children_of_item(handle, item);
    }

    public static function childOfItem(int handle, int index, int item) -> int
    {
        return nsoutlineview_child_of_item(handle, index, item);
    }

    public static function expandItemExpandChildren(int handle, int item, bool expandChildren) -> void
    {
        nsoutlineview_expand_item_expand_children(handle, item, expandChildren);
    }

    public static function expandItem(int handle, int item) -> void
    {
        nsoutlineview_expand_item(handle, item);
    }

    public static function collapseItemCollapseChildren(int handle, int item, bool collapseChildren) -> void
    {
        nsoutlineview_collapse_item_collapse_children(handle, item, collapseChildren);
    }

    public static function collapseItem(int handle, int item) -> void
    {
        nsoutlineview_collapse_item(handle, item);
    }

    public static function reloadItemReloadChildren(int handle, int item, bool reloadChildren) -> void
    {
        nsoutlineview_reload_item_reload_children(handle, item, reloadChildren);
    }

    public static function reloadItem(int handle, int item) -> void
    {
        nsoutlineview_reload_item(handle, item);
    }

    public static function parentForItem(int handle, int item) -> int
    {
        return nsoutlineview_parent_for_item(handle, item);
    }

    public static function childIndexForItem(int handle, int item) -> int
    {
        return nsoutlineview_child_index_for_item(handle, item);
    }

    public static function itemAtRow(int handle, int row) -> int
    {
        return nsoutlineview_item_at_row(handle, row);
    }

    public static function rowForItem(int handle, int item) -> int
    {
        return nsoutlineview_row_for_item(handle, item);
    }

    public static function levelForItem(int handle, int item) -> int
    {
        return nsoutlineview_level_for_item(handle, item);
    }

    public static function levelForRow(int handle, int row) -> int
    {
        return nsoutlineview_level_for_row(handle, row);
    }

    public static function isItemExpanded(int handle, int item) -> bool
    {
        int r;

        let r = nsoutlineview_is_item_expanded(handle, item);

        return r == 1;
    }

    public static function indentationPerLevel(int handle) -> double
    {
        return nsoutlineview_indentation_per_level(handle);
    }

    public static function setIndentationPerLevel(int handle, double indentationPerLevel) -> void
    {
        nsoutlineview_set_indentation_per_level(handle, indentationPerLevel);
    }

    public static function indentationMarkerFollowsCell(int handle) -> bool
    {
        int r;

        let r = nsoutlineview_indentation_marker_follows_cell(handle);

        return r == 1;
    }

    public static function setIndentationMarkerFollowsCell(int handle, bool indentationMarkerFollowsCell) -> void
    {
        nsoutlineview_set_indentation_marker_follows_cell(handle, indentationMarkerFollowsCell);
    }

    public static function autoresizesOutlineColumn(int handle) -> bool
    {
        int r;

        let r = nsoutlineview_autoresizes_outline_column(handle);

        return r == 1;
    }

    public static function setAutoresizesOutlineColumn(int handle, bool autoresizesOutlineColumn) -> void
    {
        nsoutlineview_set_autoresizes_outline_column(handle, autoresizesOutlineColumn);
    }

    public static function frameOfOutlineCellAtRow(int handle, int row) -> array
    {
        var result;

        let result = nsoutlineview_frame_of_outline_cell_at_row(handle, row);

        return result;
    }

    public static function setDropItemDropChildIndex(int handle, int item, int index) -> void
    {
        nsoutlineview_set_drop_item_drop_child_index(handle, item, index);
    }

    public static function shouldCollapseAutoExpandedItemsForDeposited(int handle, bool deposited) -> bool
    {
        int r;

        let r = nsoutlineview_should_collapse_auto_expanded_items_for_deposited(handle, deposited);

        return r == 1;
    }

    public static function autosaveExpandedItems(int handle) -> bool
    {
        int r;

        let r = nsoutlineview_autosave_expanded_items(handle);

        return r == 1;
    }

    public static function setAutosaveExpandedItems(int handle, bool autosaveExpandedItems) -> void
    {
        nsoutlineview_set_autosave_expanded_items(handle, autosaveExpandedItems);
    }

    public static function insertItemsAtIndexesInParentWithAnimation(int handle, int indexes, int parent, int animationOptions) -> void
    {
        nsoutlineview_insert_items_at_indexes_in_parent_with_animation(handle, indexes, parent, animationOptions);
    }

    public static function removeItemsAtIndexesInParentWithAnimation(int handle, int indexes, int parent, int animationOptions) -> void
    {
        nsoutlineview_remove_items_at_indexes_in_parent_with_animation(handle, indexes, parent, animationOptions);
    }

    public static function moveItemAtIndexInParentToIndexInParent(int handle, int fromIndex, int oldParent, int toIndex, int newParent) -> void
    {
        nsoutlineview_move_item_at_index_in_parent_to_index_in_parent(handle, fromIndex, oldParent, toIndex, newParent);
    }

    public static function userInterfaceLayoutDirection(int handle) -> int
    {
        return nsoutlineview_user_interface_layout_direction(handle);
    }

    public static function setUserInterfaceLayoutDirection(int handle, int userInterfaceLayoutDirection) -> void
    {
        nsoutlineview_set_user_interface_layout_direction(handle, userInterfaceLayoutDirection);
    }

    public static function stronglyReferencesItems(int handle) -> bool
    {
        int r;

        let r = nsoutlineview_strongly_references_items(handle);

        return r == 1;
    }

    public static function setStronglyReferencesItems(int handle, bool stronglyReferencesItems) -> void
    {
        nsoutlineview_set_strongly_references_items(handle, stronglyReferencesItems);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (void)insertRowsAtIndexes:(NSIndexSet *)indexes withAnimation:(NSTableViewAnimationOptions)animationOptions UNAVAILABLE_ATTRIBUTE;
    // @reserved - (void)removeRowsAtIndexes:(NSIndexSet *)indexes withAnimation:(NSTableViewAnimationOptions)animationOptions UNAVAILABLE_ATTRIBUTE;
    // @reserved - (void)moveRowAtIndex:(NSInteger)oldIndex toIndex:(NSInteger)newIndex UNAVAILABLE_ATTRIBUTE;

}
