
extern zend_class_entry *appkit_ns_nsatstypesetter_nsatstypesetter_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSATSTypesetter_NSATSTypesetter);

PHP_METHOD(AppKit_NS_NSATSTypesetter_NSATSTypesetter, sharedTypesetter);
PHP_METHOD(AppKit_NS_NSATSTypesetter_NSATSTypesetter, wrap);
PHP_METHOD(AppKit_NS_NSATSTypesetter_NSATSTypesetter, destroy);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsatstypesetter_nsatstypesetter_sharedtypesetter, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsatstypesetter_nsatstypesetter_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsATSTypesetterPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsatstypesetter_nsatstypesetter_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, typesetter, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsatstypesetter_nsatstypesetter_method_entry) {
	PHP_ME(AppKit_NS_NSATSTypesetter_NSATSTypesetter, sharedTypesetter, arginfo_appkit_ns_nsatstypesetter_nsatstypesetter_sharedtypesetter, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSATSTypesetter_NSATSTypesetter, wrap, arginfo_appkit_ns_nsatstypesetter_nsatstypesetter_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSATSTypesetter_NSATSTypesetter, destroy, arginfo_appkit_ns_nsatstypesetter_nsatstypesetter_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
