// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSTextField;

class NSTextField
{
    public static function placeholderString(int handle) -> var
    {
        var result;

        let result = nstextfield_placeholder_string(handle);

        return result;
    }

    public static function setPlaceholderString(int handle, var placeholderString) -> void
    {
        nstextfield_set_placeholder_string(handle, placeholderString);
    }

    public static function backgroundColor(int handle) -> int
    {
        return nstextfield_background_color(handle);
    }

    public static function setBackgroundColor(int handle, int backgroundColor) -> void
    {
        nstextfield_set_background_color(handle, backgroundColor);
    }

    public static function drawsBackground(int handle) -> bool
    {
        int r;

        let r = nstextfield_draws_background(handle);

        return r == 1;
    }

    public static function setDrawsBackground(int handle, bool drawsBackground) -> void
    {
        nstextfield_set_draws_background(handle, drawsBackground);
    }

    public static function textColor(int handle) -> int
    {
        return nstextfield_text_color(handle);
    }

    public static function setTextColor(int handle, int textColor) -> void
    {
        nstextfield_set_text_color(handle, textColor);
    }

    public static function isBordered(int handle) -> bool
    {
        int r;

        let r = nstextfield_is_bordered(handle);

        return r == 1;
    }

    public static function setBordered(int handle, bool bordered) -> void
    {
        nstextfield_set_bordered(handle, bordered);
    }

    public static function isBezeled(int handle) -> bool
    {
        int r;

        let r = nstextfield_is_bezeled(handle);

        return r == 1;
    }

    public static function setBezeled(int handle, bool bezeled) -> void
    {
        nstextfield_set_bezeled(handle, bezeled);
    }

    public static function isEditable(int handle) -> bool
    {
        int r;

        let r = nstextfield_is_editable(handle);

        return r == 1;
    }

    public static function setEditable(int handle, bool editable) -> void
    {
        nstextfield_set_editable(handle, editable);
    }

    public static function isSelectable(int handle) -> bool
    {
        int r;

        let r = nstextfield_is_selectable(handle);

        return r == 1;
    }

    public static function setSelectable(int handle, bool selectable) -> void
    {
        nstextfield_set_selectable(handle, selectable);
    }

    public static function selectText(int handle, int sender) -> void
    {
        nstextfield_select_text(handle, sender);
    }

    public static function delegate(int handle) -> int
    {
        return nstextfield_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nstextfield_set_delegate(handle, delegate);
    }

    public static function textShouldBeginEditing(int handle, int textObject) -> bool
    {
        int r;

        let r = nstextfield_text_should_begin_editing(handle, textObject);

        return r == 1;
    }

    public static function textShouldEndEditing(int handle, int textObject) -> bool
    {
        int r;

        let r = nstextfield_text_should_end_editing(handle, textObject);

        return r == 1;
    }

    public static function textDidBeginEditing(int handle, int notification) -> void
    {
        nstextfield_text_did_begin_editing(handle, notification);
    }

    public static function textDidEndEditing(int handle, int notification) -> void
    {
        nstextfield_text_did_end_editing(handle, notification);
    }

    public static function textDidChange(int handle, int notification) -> void
    {
        nstextfield_text_did_change(handle, notification);
    }

    public static function acceptsFirstResponder(int handle) -> bool
    {
        int r;

        let r = nstextfield_accepts_first_responder(handle);

        return r == 1;
    }

    public static function bezelStyle(int handle) -> int
    {
        return nstextfield_bezel_style(handle);
    }

    public static function setBezelStyle(int handle, int bezelStyle) -> void
    {
        nstextfield_set_bezel_style(handle, bezelStyle);
    }

    public static function preferredMaxLayoutWidth(int handle) -> double
    {
        return nstextfield_preferred_max_layout_width(handle);
    }

    public static function setPreferredMaxLayoutWidth(int handle, double preferredMaxLayoutWidth) -> void
    {
        nstextfield_set_preferred_max_layout_width(handle, preferredMaxLayoutWidth);
    }

    public static function maximumNumberOfLines(int handle) -> int
    {
        return nstextfield_maximum_number_of_lines(handle);
    }

    public static function setMaximumNumberOfLines(int handle, int maximumNumberOfLines) -> void
    {
        nstextfield_set_maximum_number_of_lines(handle, maximumNumberOfLines);
    }

    public static function allowsDefaultTighteningForTruncation(int handle) -> bool
    {
        int r;

        let r = nstextfield_allows_default_tightening_for_truncation(handle);

        return r == 1;
    }

    public static function setAllowsDefaultTighteningForTruncation(int handle, bool allowsDefaultTighteningForTruncation) -> void
    {
        nstextfield_set_allows_default_tightening_for_truncation(handle, allowsDefaultTighteningForTruncation);
    }

    public static function lineBreakStrategy(int handle) -> int
    {
        return nstextfield_line_break_strategy(handle);
    }

    public static function setLineBreakStrategy(int handle, int lineBreakStrategy) -> void
    {
        nstextfield_set_line_break_strategy(handle, lineBreakStrategy);
    }

    public static function allowsWritingTools(int handle) -> bool
    {
        int r;

        let r = nstextfield_allows_writing_tools(handle);

        return r == 1;
    }

    public static function setAllowsWritingTools(int handle, bool allowsWritingTools) -> void
    {
        nstextfield_set_allows_writing_tools(handle, allowsWritingTools);
    }

    public static function allowsWritingToolsAffordance(int handle) -> bool
    {
        int r;

        let r = nstextfield_allows_writing_tools_affordance(handle);

        return r == 1;
    }

    public static function setAllowsWritingToolsAffordance(int handle, bool allowsWritingToolsAffordance) -> void
    {
        nstextfield_set_allows_writing_tools_affordance(handle, allowsWritingToolsAffordance);
    }

    public static function isAutomaticTextCompletionEnabled(int handle) -> bool
    {
        int r;

        let r = nstextfield_is_automatic_text_completion_enabled(handle);

        return r == 1;
    }

    public static function setAutomaticTextCompletionEnabled(int handle, bool automaticTextCompletionEnabled) -> void
    {
        nstextfield_set_automatic_text_completion_enabled(handle, automaticTextCompletionEnabled);
    }

    public static function allowsCharacterPickerTouchBarItem(int handle) -> bool
    {
        int r;

        let r = nstextfield_allows_character_picker_touch_bar_item(handle);

        return r == 1;
    }

    public static function setAllowsCharacterPickerTouchBarItem(int handle, bool allowsCharacterPickerTouchBarItem) -> void
    {
        nstextfield_set_allows_character_picker_touch_bar_item(handle, allowsCharacterPickerTouchBarItem);
    }

    public static function labelWithString(string stringValue) -> int
    {
        return nstextfield_label_with_string(stringValue);
    }

    public static function wrappingLabelWithString(string stringValue) -> int
    {
        return nstextfield_wrapping_label_with_string(stringValue);
    }

    public static function textFieldWithString(string stringValue) -> int
    {
        return nstextfield_text_field_with_string(stringValue);
    }

    public static function allowsEditingTextAttributes(int handle) -> bool
    {
        int r;

        let r = nstextfield_allows_editing_text_attributes(handle);

        return r == 1;
    }

    public static function setAllowsEditingTextAttributes(int handle, bool allowsEditingTextAttributes) -> void
    {
        nstextfield_set_allows_editing_text_attributes(handle, allowsEditingTextAttributes);
    }

    public static function importsGraphics(int handle) -> bool
    {
        int r;

        let r = nstextfield_imports_graphics(handle);

        return r == 1;
    }

    public static function setImportsGraphics(int handle, bool importsGraphics) -> void
    {
        nstextfield_set_imports_graphics(handle, importsGraphics);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (nullable, copy) NSAttributedString *placeholderAttributedString — getter
    // @reserved @property (nullable, copy) NSAttributedString *placeholderAttributedString — setter
    // @reserved + (instancetype)labelWithAttributedString:(NSAttributedString *)attributedStringValue
    // @reserved - (void)setTitleWithMnemonic:(null_unspecified NSString *)stringWithAmpersand API_DEPRECATED

}
