// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSButton;

class NSButton
{
    public static function buttonWithTitleImageTargetAction(string title, int image, int target, string action) -> int
    {
        return nsbutton_button_with_title_image_target_action(title, image, target, action);
    }

    public static function buttonWithTitleTargetAction(string title, int target, string action) -> int
    {
        return nsbutton_button_with_title_target_action(title, target, action);
    }

    public static function buttonWithImageTargetAction(int image, int target, string action) -> int
    {
        return nsbutton_button_with_image_target_action(image, target, action);
    }

    public static function checkboxWithTitleTargetAction(string title, int target, string action) -> int
    {
        return nsbutton_checkbox_with_title_target_action(title, target, action);
    }

    public static function radioButtonWithTitleTargetAction(string title, int target, string action) -> int
    {
        return nsbutton_radio_button_with_title_target_action(title, target, action);
    }

    public static function setButtonType(int handle, int type) -> void
    {
        nsbutton_set_button_type(handle, type);
    }

    public static function attributedTitle(int handle) -> int
    {
        return nsbutton_attributed_title(handle);
    }

    public static function setAttributedTitle(int handle, int attributedTitle) -> void
    {
        nsbutton_set_attributed_title(handle, attributedTitle);
    }

    public static function title(int handle) -> string
    {
        var result;

        let result = nsbutton_title(handle);

        return result;
    }

    public static function setTitle(int handle, string title) -> void
    {
        nsbutton_set_title(handle, title);
    }

    public static function alternateTitle(int handle) -> string
    {
        var result;

        let result = nsbutton_alternate_title(handle);

        return result;
    }

    public static function setAlternateTitle(int handle, string title) -> void
    {
        nsbutton_set_alternate_title(handle, title);
    }

    public static function hasDestructiveAction(int handle) -> bool
    {
        int r;

        let r = nsbutton_has_destructive_action(handle);

        return r == 1;
    }

    public static function setHasDestructiveAction(int handle, bool flag) -> void
    {
        nsbutton_set_has_destructive_action(handle, flag);
    }

    public static function sound(int handle) -> int
    {
        return nsbutton_sound(handle);
    }

    public static function setSound(int handle, int sound) -> void
    {
        nsbutton_set_sound(handle, sound);
    }

    public static function isSpringLoaded(int handle) -> bool
    {
        int r;

        let r = nsbutton_is_spring_loaded(handle);

        return r == 1;
    }

    public static function setSpringLoaded(int handle, bool flag) -> void
    {
        nsbutton_set_spring_loaded(handle, flag);
    }

    public static function maxAcceleratorLevel(int handle) -> int
    {
        return nsbutton_max_accelerator_level(handle);
    }

    public static function setMaxAcceleratorLevel(int handle, int level) -> void
    {
        nsbutton_set_max_accelerator_level(handle, level);
    }

    public static function setPeriodicDelayInterval(int handle, double delay, double interval) -> void
    {
        nsbutton_set_periodic_delay_interval(handle, delay, interval);
    }

    public static function getPeriodicDelayInterval(int handle) -> array
    {
        var result;

        let result = nsbutton_get_periodic_delay_interval(handle);

        return result;
    }

    public static function bezelStyle(int handle) -> int
    {
        return nsbutton_bezel_style(handle);
    }

    public static function setBezelStyle(int handle, int style) -> void
    {
        nsbutton_set_bezel_style(handle, style);
    }

    public static function isBordered(int handle) -> bool
    {
        int r;

        let r = nsbutton_is_bordered(handle);

        return r == 1;
    }

    public static function setBordered(int handle, bool flag) -> void
    {
        nsbutton_set_bordered(handle, flag);
    }

    public static function isTransparent(int handle) -> bool
    {
        int r;

        let r = nsbutton_is_transparent(handle);

        return r == 1;
    }

    public static function setTransparent(int handle, bool flag) -> void
    {
        nsbutton_set_transparent(handle, flag);
    }

    public static function showsBorderOnlyWhileMouseInside(int handle) -> bool
    {
        int r;

        let r = nsbutton_shows_border_only_while_mouse_inside(handle);

        return r == 1;
    }

    public static function setShowsBorderOnlyWhileMouseInside(int handle, bool flag) -> void
    {
        nsbutton_set_shows_border_only_while_mouse_inside(handle, flag);
    }

    public static function bezelColor(int handle) -> int
    {
        return nsbutton_bezel_color(handle);
    }

    public static function setBezelColor(int handle, int color) -> void
    {
        nsbutton_set_bezel_color(handle, color);
    }

    public static function contentTintColor(int handle) -> int
    {
        return nsbutton_content_tint_color(handle);
    }

    public static function setContentTintColor(int handle, int color) -> void
    {
        nsbutton_set_content_tint_color(handle, color);
    }

    public static function image(int handle) -> int
    {
        return nsbutton_image(handle);
    }

    public static function setImage(int handle, int image) -> void
    {
        nsbutton_set_image(handle, image);
    }

    public static function alternateImage(int handle) -> int
    {
        return nsbutton_alternate_image(handle);
    }

    public static function setAlternateImage(int handle, int image) -> void
    {
        nsbutton_set_alternate_image(handle, image);
    }

    public static function imagePosition(int handle) -> int
    {
        return nsbutton_image_position(handle);
    }

    public static function setImagePosition(int handle, int position) -> void
    {
        nsbutton_set_image_position(handle, position);
    }

    public static function imageScaling(int handle) -> int
    {
        return nsbutton_image_scaling(handle);
    }

    public static function setImageScaling(int handle, int scaling) -> void
    {
        nsbutton_set_image_scaling(handle, scaling);
    }

    public static function imageHugsTitle(int handle) -> bool
    {
        int r;

        let r = nsbutton_image_hugs_title(handle);

        return r == 1;
    }

    public static function setImageHugsTitle(int handle, bool flag) -> void
    {
        nsbutton_set_image_hugs_title(handle, flag);
    }

    public static function symbolConfiguration(int handle) -> int
    {
        return nsbutton_symbol_configuration(handle);
    }

    public static function setSymbolConfiguration(int handle, int configuration) -> void
    {
        nsbutton_set_symbol_configuration(handle, configuration);
    }

    public static function state(int handle) -> int
    {
        return nsbutton_state(handle);
    }

    public static function setState(int handle, int state) -> void
    {
        nsbutton_set_state(handle, state);
    }

    public static function allowsMixedState(int handle) -> bool
    {
        int r;

        let r = nsbutton_allows_mixed_state(handle);

        return r == 1;
    }

    public static function setAllowsMixedState(int handle, bool flag) -> void
    {
        nsbutton_set_allows_mixed_state(handle, flag);
    }

    public static function setNextState(int handle) -> void
    {
        nsbutton_set_next_state(handle);
    }

    public static function highlight(int handle, bool flag) -> void
    {
        nsbutton_highlight(handle, flag);
    }

    public static function keyEquivalent(int handle) -> string
    {
        var result;

        let result = nsbutton_key_equivalent(handle);

        return result;
    }

    public static function setKeyEquivalent(int handle, string keyEquivalent) -> void
    {
        nsbutton_set_key_equivalent(handle, keyEquivalent);
    }

    public static function keyEquivalentModifierMask(int handle) -> int
    {
        return nsbutton_key_equivalent_modifier_mask(handle);
    }

    public static function setKeyEquivalentModifierMask(int handle, int mask) -> void
    {
        nsbutton_set_key_equivalent_modifier_mask(handle, mask);
    }

    public static function performKeyEquivalent(int handle, int key) -> bool
    {
        int r;

        let r = nsbutton_perform_key_equivalent(handle, key);

        return r == 1;
    }

    public static function compressWithPrioritizedCompressionOptions(int handle, array prioritizedOptions) -> void
    {
        nsbutton_compress_with_prioritized_compression_options(handle, prioritizedOptions);
    }

    public static function minimumSizeWithPrioritizedCompressionOptions(int handle, array prioritizedOptions) -> array
    {
        var result;

        let result = nsbutton_minimum_size_with_prioritized_compression_options(handle, prioritizedOptions);

        return result;
    }

    public static function activeCompressionOptions(int handle) -> int
    {
        return nsbutton_active_compression_options(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved @property (copy) NSAttributedString *attributedTitle — getter
    // @reserved @property (copy) NSAttributedString *attributedTitle — setter
    // @reserved @property (copy) NSAttributedString *attributedAlternateTitle — getter
    // @reserved @property (copy) NSAttributedString *attributedAlternateTitle — setter
    // @reserved - (void)setTitleWithMnemonic:(null_unspecified NSString *)stringWithAmpersand API_DEPRECATED

}
