
extern zend_class_entry *appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer);

PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, create);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, destroy);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setEnabled);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, isEnabled);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, state);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, addToView);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, removeFromView);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, locationInView);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setButtonMask);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, buttonMask);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setMinimumPressDuration);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, minimumPressDuration);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setAllowableMovement);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, allowableMovement);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setNumberOfTouchesRequired);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, numberOfTouchesRequired);
PHP_METHOD(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, nsPressGestureRecognizer);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, enabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_isenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_state, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_addtoview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_removefromview, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_locationinview, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, view, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setbuttonmask, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, mask, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_buttonmask, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setminimumpressduration, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seconds, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_minimumpressduration, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setallowablemovement, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, points, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_allowablemovement, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setnumberoftouchesrequired, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_numberoftouchesrequired, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_nspressgesturerecognizer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, recognizer, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_method_entry) {
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, create, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, destroy, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setEnabled, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, isEnabled, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_isenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, state, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_state, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, addToView, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_addtoview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, removeFromView, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_removefromview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, locationInView, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_locationinview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setButtonMask, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setbuttonmask, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, buttonMask, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_buttonmask, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setMinimumPressDuration, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setminimumpressduration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, minimumPressDuration, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_minimumpressduration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setAllowableMovement, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setallowablemovement, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, allowableMovement, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_allowablemovement, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, setNumberOfTouchesRequired, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_setnumberoftouchesrequired, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, numberOfTouchesRequired, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_numberoftouchesrequired, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSPressGestureRecognizer_NSPressGestureRecognizer, nsPressGestureRecognizer, arginfo_appkit_ns_nspressgesturerecognizer_nspressgesturerecognizer_nspressgesturerecognizer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
