// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSImageRep;

class NSImageRep
{
    public static function init() -> int
    {
        return nsimagerep_init();
    }

    public static function draw(int handle) -> bool
    {
        int r;

        let r = nsimagerep_draw(handle);

        return r == 1;
    }

    public static function drawAtPoint(int handle, double x, double y) -> bool
    {
        int r;

        let r = nsimagerep_draw_at_point(handle, x, y);

        return r == 1;
    }

    public static function drawInRect(int handle, double x, double y, double width, double height) -> bool
    {
        int r;

        let r = nsimagerep_draw_in_rect(handle, x, y, width, height);

        return r == 1;
    }

    public static function drawInRectFromRectOperationFractionRespectFlippedHints(int handle, double x, double y, double width, double height, double fromX, double fromY, double fromWidth, double fromHeight, int op, double requestedAlpha, bool respectFlipped, int hints) -> bool
    {
        int r;

        let r = nsimagerep_draw_in_rect_from_rect_operation_fraction_respect_flipped_hints(handle, x, y, width, height, fromX, fromY, fromWidth, fromHeight, op, requestedAlpha, respectFlipped, hints);

        return r == 1;
    }

    public static function size(int handle) -> array
    {
        var result;

        let result = nsimagerep_size(handle);

        return result;
    }

    public static function setSize(int handle, double width, double height) -> void
    {
        nsimagerep_set_size(handle, width, height);
    }

    public static function hasAlpha(int handle) -> bool
    {
        int r;

        let r = nsimagerep_has_alpha(handle);

        return r == 1;
    }

    public static function setAlpha(int handle, bool flag) -> void
    {
        nsimagerep_set_alpha(handle, flag);
    }

    public static function isOpaque(int handle) -> bool
    {
        int r;

        let r = nsimagerep_is_opaque(handle);

        return r == 1;
    }

    public static function setOpaque(int handle, bool flag) -> void
    {
        nsimagerep_set_opaque(handle, flag);
    }

    public static function colorSpaceName(int handle) -> string
    {
        var result;

        let result = nsimagerep_color_space_name(handle);

        return result;
    }

    public static function setColorSpaceName(int handle, string colorSpaceName) -> void
    {
        nsimagerep_set_color_space_name(handle, colorSpaceName);
    }

    public static function bitsPerSample(int handle) -> int
    {
        return nsimagerep_bits_per_sample(handle);
    }

    public static function setBitsPerSample(int handle, int bitsPerSample) -> void
    {
        nsimagerep_set_bits_per_sample(handle, bitsPerSample);
    }

    public static function pixelsWide(int handle) -> int
    {
        return nsimagerep_pixels_wide(handle);
    }

    public static function setPixelsWide(int handle, int pixelsWide) -> void
    {
        nsimagerep_set_pixels_wide(handle, pixelsWide);
    }

    public static function pixelsHigh(int handle) -> int
    {
        return nsimagerep_pixels_high(handle);
    }

    public static function setPixelsHigh(int handle, int pixelsHigh) -> void
    {
        nsimagerep_set_pixels_high(handle, pixelsHigh);
    }

    public static function layoutDirection(int handle) -> int
    {
        return nsimagerep_layout_direction(handle);
    }

    public static function setLayoutDirection(int handle, int layoutDirection) -> void
    {
        nsimagerep_set_layout_direction(handle, layoutDirection);
    }

    public static function imageUnfilteredTypes() -> array
    {
        var result;

        let result = nsimagerep_image_unfiltered_types();

        return result;
    }

    public static function imageTypes() -> array
    {
        var result;

        let result = nsimagerep_image_types();

        return result;
    }

    public static function canInitWithPasteboard(int pasteboard) -> bool
    {
        int r;

        let r = nsimagerep_can_init_with_pasteboard(pasteboard);

        return r == 1;
    }

    public static function imageRepsWithContentsOfFile(string fileName) -> array
    {
        var result;

        let result = nsimagerep_image_reps_with_contents_of_file(fileName);

        return result;
    }

    public static function imageRepWithContentsOfFile(string fileName) -> int
    {
        return nsimagerep_image_rep_with_contents_of_file(fileName);
    }

    public static function imageRepsWithContentsOfURL(int url) -> array
    {
        var result;

        let result = nsimagerep_image_reps_with_contents_of_url(url);

        return result;
    }

    public static function imageRepWithContentsOfURL(int url) -> int
    {
        return nsimagerep_image_rep_with_contents_of_url(url);
    }

    public static function imageRepsWithPasteboard(int pasteboard) -> array
    {
        var result;

        let result = nsimagerep_image_reps_with_pasteboard(pasteboard);

        return result;
    }

    public static function imageRepWithPasteboard(int pasteboard) -> int
    {
        return nsimagerep_image_rep_with_pasteboard(pasteboard);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
    // @reserved + (void)registerImageRepClass:(Class)imageRepClass;
    // @reserved + (void)unregisterImageRepClass:(Class)imageRepClass;
    // @reserved @property (class, readonly, copy) NSArray<Class> *registeredImageRepClasses — Class
    // @reserved + (nullable Class)imageRepClassForFileType:(NSString *)type API_DEPRECATED
    // @reserved + (nullable Class)imageRepClassForPasteboardType:(NSPasteboardType)type API_DEPRECATED
    // @reserved + (nullable Class)imageRepClassForType:(NSString *)type;
    // @reserved + (nullable Class)imageRepClassForData:(NSData *)data;
    // @reserved + (BOOL)canInitWithData:(NSData *)data;
    // @reserved + (NSArray<NSString *> *)imageUnfilteredFileTypes API_DEPRECATED
    // @reserved + (NSArray<NSPasteboardType> *)imageUnfilteredPasteboardTypes API_DEPRECATED
    // @reserved + (NSArray<NSString *> *)imageFileTypes API_DEPRECATED
    // @reserved + (NSArray<NSPasteboardType> *)imagePasteboardTypes API_DEPRECATED
    // @reserved - (nullable CGImageRef)CGImageForProposedRect:(nullable NSRect *)proposedDestRect context:(nullable NSGraphicsContext *)context hints:(nullable NSDictionary<NSImageHintKey, id> *)hints — CGImageRef plus NSRect * inout

}
