// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSCollectionViewLayoutAttributes;

class NSCollectionViewLayoutAttributes
{
    public static function frame(int handle) -> array
    {
        var result;

        let result = nscollectionviewlayoutattributes_frame(handle);

        return result;
    }

    public static function setFrame(int handle, double x, double y, double width, double height) -> void
    {
        nscollectionviewlayoutattributes_set_frame(handle, x, y, width, height);
    }

    public static function size(int handle) -> array
    {
        var result;

        let result = nscollectionviewlayoutattributes_size(handle);

        return result;
    }

    public static function setSize(int handle, double width, double height) -> void
    {
        nscollectionviewlayoutattributes_set_size(handle, width, height);
    }

    public static function alpha(int handle) -> double
    {
        return nscollectionviewlayoutattributes_alpha(handle);
    }

    public static function setAlpha(int handle, double alpha) -> void
    {
        nscollectionviewlayoutattributes_set_alpha(handle, alpha);
    }

    public static function zIndex(int handle) -> int
    {
        return nscollectionviewlayoutattributes_z_index(handle);
    }

    public static function setZIndex(int handle, int zIndex) -> void
    {
        nscollectionviewlayoutattributes_set_z_index(handle, zIndex);
    }

    public static function isHidden(int handle) -> bool
    {
        int r;

        let r = nscollectionviewlayoutattributes_is_hidden(handle);

        return r == 1;
    }

    public static function setHidden(int handle, bool hidden) -> void
    {
        nscollectionviewlayoutattributes_set_hidden(handle, hidden);
    }

    public static function indexPath(int handle) -> int
    {
        return nscollectionviewlayoutattributes_index_path(handle);
    }

    public static function setIndexPath(int handle, int indexPath) -> void
    {
        nscollectionviewlayoutattributes_set_index_path(handle, indexPath);
    }

    public static function representedElementCategory(int handle) -> int
    {
        return nscollectionviewlayoutattributes_represented_element_category(handle);
    }

    public static function representedElementKind(int handle) -> var
    {
        var result;

        let result = nscollectionviewlayoutattributes_represented_element_kind(handle);

        return result;
    }

    public static function layoutAttributesForItemWithIndexPath(int indexPath) -> int
    {
        return nscollectionviewlayoutattributes_layout_attributes_for_item_with_index_path(indexPath);
    }

    public static function layoutAttributesForInterItemGapBeforeIndexPath(int indexPath) -> int
    {
        return nscollectionviewlayoutattributes_layout_attributes_for_inter_item_gap_before_index_path(indexPath);
    }

    public static function layoutAttributesForSupplementaryViewOfKindWithIndexPath(string elementKind, int indexPath) -> int
    {
        return nscollectionviewlayoutattributes_layout_attributes_for_supplementary_view_of_kind_with_index_path(elementKind, indexPath);
    }

    public static function layoutAttributesForDecorationViewOfKindWithIndexPath(string decorationViewKind, int indexPath) -> int
    {
        return nscollectionviewlayoutattributes_layout_attributes_for_decoration_view_of_kind_with_index_path(decorationViewKind, indexPath);
    }
}
