
extern zend_class_entry *appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem);

PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, create);
PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, nsSliderTouchBarItem);
PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, setDoubleValue);
PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, getDoubleValue);
PHP_METHOD(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, pollAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_nsslidertouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_setdoublevalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_getdoublevalue, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_pollaction, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, create, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, wrap, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, destroy, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, nsSliderTouchBarItem, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_nsslidertouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, setDoubleValue, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_setdoublevalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, getDoubleValue, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_getdoublevalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSliderTouchBarItem_NSSliderTouchBarItem, pollAction, arginfo_appkit_ns_nsslidertouchbaritem_nsslidertouchbaritem_pollaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
