
extern zend_class_entry *appkit_ns_nsscrubberlayout_nsscrubberlayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSScrubberLayout_NSScrubberLayout);

PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, create);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, wrap);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, destroy);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, nsScrubberLayout);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, invalidate);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, scrubber);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, visibleRect);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, contentWidth);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, contentHeight);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, shouldInvalidateForSelectionChange);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, shouldInvalidateForHighlightChange);
PHP_METHOD(AppKit_NS_NSScrubberLayout_NSScrubberLayout, automaticallyMirrorsInRightToLeftLayout);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_create, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsScrubberLayoutPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_nsscrubberlayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_invalidate, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_scrubber, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_visiblerect, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_contentwidth, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_contentheight, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_shouldinvalidateforselectionchange, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_shouldinvalidateforhighlightchange, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_automaticallymirrorsinrighttoleftlayout, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsscrubberlayout_nsscrubberlayout_method_entry) {
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, create, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, wrap, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, destroy, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, nsScrubberLayout, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_nsscrubberlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, invalidate, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_invalidate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, scrubber, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_scrubber, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, visibleRect, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_visiblerect, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, contentWidth, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_contentwidth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, contentHeight, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_contentheight, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, shouldInvalidateForSelectionChange, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_shouldinvalidateforselectionchange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, shouldInvalidateForHighlightChange, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_shouldinvalidateforhighlightchange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSScrubberLayout_NSScrubberLayout, automaticallyMirrorsInRightToLeftLayout, arginfo_appkit_ns_nsscrubberlayout_nsscrubberlayout_automaticallymirrorsinrighttoleftlayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
