
extern zend_class_entry *appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem);

PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, groupItem);
PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, alertStyleGroupItem);
PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, wrap);
PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, destroy);
PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, nsGroupTouchBarItem);
PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, setGroupTouchBar);
PHP_METHOD(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, getGroupTouchBar);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_groupitem, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
	ZEND_ARG_ARRAY_INFO(0, items, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_alertstylegroupitem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_nsgrouptouchbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_setgrouptouchbar, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, bar, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_getgrouptouchbar, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, groupItem, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_groupitem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, alertStyleGroupItem, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_alertstylegroupitem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, wrap, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, destroy, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, nsGroupTouchBarItem, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_nsgrouptouchbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, setGroupTouchBar, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_setgrouptouchbar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSGroupTouchBarItem_NSGroupTouchBarItem, getGroupTouchBar, arginfo_appkit_ns_nsgrouptouchbaritem_nsgrouptouchbaritem_getgrouptouchbar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
