// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSCollectionViewGridLayout;

class NSCollectionViewGridLayout
{
    public static function init() -> int
    {
        return nscollectionviewgridlayout_init();
    }

    public static function margins(int handle) -> array
    {
        var result;

        let result = nscollectionviewgridlayout_margins(handle);

        return result;
    }

    public static function setMargins(int handle, double top, double left, double bottom, double right) -> void
    {
        nscollectionviewgridlayout_set_margins(handle, top, left, bottom, right);
    }

    public static function minimumInteritemSpacing(int handle) -> double
    {
        return nscollectionviewgridlayout_minimum_interitem_spacing(handle);
    }

    public static function setMinimumInteritemSpacing(int handle, double minimumInteritemSpacing) -> void
    {
        nscollectionviewgridlayout_set_minimum_interitem_spacing(handle, minimumInteritemSpacing);
    }

    public static function minimumLineSpacing(int handle) -> double
    {
        return nscollectionviewgridlayout_minimum_line_spacing(handle);
    }

    public static function setMinimumLineSpacing(int handle, double minimumLineSpacing) -> void
    {
        nscollectionviewgridlayout_set_minimum_line_spacing(handle, minimumLineSpacing);
    }

    public static function maximumNumberOfRows(int handle) -> int
    {
        return nscollectionviewgridlayout_maximum_number_of_rows(handle);
    }

    public static function setMaximumNumberOfRows(int handle, int maximumNumberOfRows) -> void
    {
        nscollectionviewgridlayout_set_maximum_number_of_rows(handle, maximumNumberOfRows);
    }

    public static function maximumNumberOfColumns(int handle) -> int
    {
        return nscollectionviewgridlayout_maximum_number_of_columns(handle);
    }

    public static function setMaximumNumberOfColumns(int handle, int maximumNumberOfColumns) -> void
    {
        nscollectionviewgridlayout_set_maximum_number_of_columns(handle, maximumNumberOfColumns);
    }

    public static function minimumItemSize(int handle) -> array
    {
        var result;

        let result = nscollectionviewgridlayout_minimum_item_size(handle);

        return result;
    }

    public static function setMinimumItemSize(int handle, double width, double height) -> void
    {
        nscollectionviewgridlayout_set_minimum_item_size(handle, width, height);
    }

    public static function maximumItemSize(int handle) -> array
    {
        var result;

        let result = nscollectionviewgridlayout_maximum_item_size(handle);

        return result;
    }

    public static function setMaximumItemSize(int handle, double width, double height) -> void
    {
        nscollectionviewgridlayout_set_maximum_item_size(handle, width, height);
    }

    public static function backgroundColors(int handle) -> array
    {
        var result;

        let result = nscollectionviewgridlayout_background_colors(handle);

        return result;
    }

    public static function setBackgroundColors(int handle, var backgroundColors) -> void
    {
        nscollectionviewgridlayout_set_background_colors(handle, backgroundColors);
    }
}
