
extern zend_class_entry *appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem);

PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, createWithTargetElement);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, createWithToken);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, wrap);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, destroy);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, nsAccessibilityCustomRotorItem);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, customLabel);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, setCustomLabel);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, setTargetRange);
PHP_METHOD(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, targetRange);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_createwithtargetelement, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, element, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_createwithtoken, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, token, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, label, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, ptr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_customlabel, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_setcustomlabel, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, label, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_settargetrange, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_targetrange, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_method_entry) {
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, createWithTargetElement, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_createwithtargetelement, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, createWithToken, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_createwithtoken, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, wrap, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, destroy, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, nsAccessibilityCustomRotorItem, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, customLabel, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_customlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, setCustomLabel, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_setcustomlabel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, setTargetRange, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_settargetrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSAccessibilityCustomRotorItem_NSAccessibilityCustomRotorItem, targetRange, arginfo_appkit_ns_nsaccessibilitycustomrotoritem_nsaccessibilitycustomrotoritem_targetrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
