
extern zend_class_entry *appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout);

PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, createList);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, createGrid);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, wrap);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, destroy);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, nsCollectionViewCompositionalLayout);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, setScrollDirection);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, getScrollDirection);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, setInterSectionSpacing);
PHP_METHOD(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, getInterSectionSpacing);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_createlist, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, itemHeight, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_creategrid, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, columns, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, itemHeight, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsCollectionViewCompositionalLayoutPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_setscrolldirection, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, direction, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_getscrolldirection, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_setintersectionspacing, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, spacing, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_getintersectionspacing, 0, 1, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, layout, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_method_entry) {
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, createList, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_createlist, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, createGrid, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_creategrid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, wrap, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, destroy, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, nsCollectionViewCompositionalLayout, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, setScrollDirection, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_setscrolldirection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, getScrollDirection, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_getscrolldirection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, setInterSectionSpacing, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_setintersectionspacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSCollectionViewCompositionalLayout_NSCollectionViewCompositionalLayout, getInterSectionSpacing, arginfo_appkit_ns_nscollectionviewcompositionallayout_nscollectionviewcompositionallayout_getintersectionspacing, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
