
extern zend_class_entry *appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem);

PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, create);
PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, wrap);
PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, destroy);
PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, nsSharingServicePickerToolbarItem);
PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, setShareStrings);
PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, getShareStrings);
PHP_METHOD(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, pollShareRequest);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_create, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identifier, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsSharingServicePickerToolbarItemPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_setsharestrings, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, strings, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_getsharestrings, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_pollsharerequest, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, item, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_method_entry) {
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, create, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, wrap, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, destroy, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, nsSharingServicePickerToolbarItem, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, setShareStrings, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_setsharestrings, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, getShareStrings, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_getsharestrings, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSSharingServicePickerToolbarItem_NSSharingServicePickerToolbarItem, pollShareRequest, arginfo_appkit_ns_nssharingservicepickertoolbaritem_nssharingservicepickertoolbaritem_pollsharerequest, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
