// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSStatusBar;

class NSStatusBar
{
    public static function systemStatusBar() -> int
    {
        return nsstatusbar_system_status_bar();
    }

    public static function statusItemWithLength(int handle, double length) -> int
    {
        return nsstatusbar_status_item_with_length(handle, length);
    }

    public static function removeStatusItem(int handle, int item) -> void
    {
        nsstatusbar_remove_status_item(handle, item);
    }

    public static function isVertical(int handle) -> bool
    {
        int r;

        let r = nsstatusbar_is_vertical(handle);

        return r == 1;
    }

    public static function thickness(int handle) -> double
    {
        return nsstatusbar_thickness(handle);
    }
}
