
extern zend_class_entry *appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_ce;

ZEPHIR_INIT_CLASS(AppKit_NS_NSTextCheckingController_NSTextCheckingController);

PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, createWithClient);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, wrap);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, destroy);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, nsTextCheckingController);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, client);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, invalidate);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, didChangeTextInRange);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, insertedTextInRange);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, didChangeSelectedRange);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, considerTextCheckingForRange);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkTextInRange);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkTextInSelection);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkTextInDocument);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, orderFrontSubstitutionsPanel);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkSpelling);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, showGuessPanel);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, changeSpelling);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, ignoreSpelling);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, updateCandidates);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, getValidAnnotations);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, setSpellCheckerDocumentTag);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, getSpellCheckerDocumentTag);
PHP_METHOD(AppKit_NS_NSTextCheckingController_NSTextCheckingController, menuAtIndex);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_createwithclient, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, clientPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_wrap, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, nsTextCheckingControllerPtr, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_nstextcheckingcontroller, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_client, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_invalidate, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_didchangetextinrange, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_insertedtextinrange, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_didchangeselectedrange, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_considertextcheckingforrange, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checktextinrange, 0, 4, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, length, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, types, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checktextinselection, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checktextindocument, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_orderfrontsubstitutionspanel, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checkspelling, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_showguesspanel, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_changespelling, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_ignorespelling, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_updatecandidates, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_getvalidannotations, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_setspellcheckerdocumenttag, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, tag, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_getspellcheckerdocumenttag, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_menuatindex, 0, 3, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, controller, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, location, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, clickedOnSelection, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_method_entry) {
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, createWithClient, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_createwithclient, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, wrap, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_wrap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, destroy, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, nsTextCheckingController, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_nstextcheckingcontroller, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, client, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_client, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, invalidate, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_invalidate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, didChangeTextInRange, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_didchangetextinrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, insertedTextInRange, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_insertedtextinrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, didChangeSelectedRange, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_didchangeselectedrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, considerTextCheckingForRange, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_considertextcheckingforrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkTextInRange, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checktextinrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkTextInSelection, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checktextinselection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkTextInDocument, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checktextindocument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, orderFrontSubstitutionsPanel, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_orderfrontsubstitutionspanel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, checkSpelling, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_checkspelling, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, showGuessPanel, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_showguesspanel, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, changeSpelling, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_changespelling, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, ignoreSpelling, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_ignorespelling, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, updateCandidates, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_updatecandidates, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, getValidAnnotations, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_getvalidannotations, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, setSpellCheckerDocumentTag, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_setspellcheckerdocumenttag, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, getSpellCheckerDocumentTag, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_getspellcheckerdocumenttag, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(AppKit_NS_NSTextCheckingController_NSTextCheckingController, menuAtIndex, arginfo_appkit_ns_nstextcheckingcontroller_nstextcheckingcontroller_menuatindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
