// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSPopover;

class NSPopover
{
    public static function init() -> int
    {
        return nspopover_init();
    }

    public static function delegate(int handle) -> int
    {
        return nspopover_delegate(handle);
    }

    public static function setDelegate(int handle, int delegate) -> void
    {
        nspopover_set_delegate(handle, delegate);
    }

    public static function appearance(int handle) -> int
    {
        return nspopover_appearance(handle);
    }

    public static function setAppearance(int handle, int appearance) -> void
    {
        nspopover_set_appearance(handle, appearance);
    }

    public static function effectiveAppearance(int handle) -> int
    {
        return nspopover_effective_appearance(handle);
    }

    public static function behavior(int handle) -> int
    {
        return nspopover_behavior(handle);
    }

    public static function setBehavior(int handle, int behavior) -> void
    {
        nspopover_set_behavior(handle, behavior);
    }

    public static function animates(int handle) -> bool
    {
        int r;

        let r = nspopover_animates(handle);

        return r == 1;
    }

    public static function setAnimates(int handle, bool animates) -> void
    {
        nspopover_set_animates(handle, animates);
    }

    public static function contentViewController(int handle) -> int
    {
        return nspopover_content_view_controller(handle);
    }

    public static function setContentViewController(int handle, int contentViewController) -> void
    {
        nspopover_set_content_view_controller(handle, contentViewController);
    }

    public static function contentSize(int handle) -> array
    {
        var result;

        let result = nspopover_content_size(handle);

        return result;
    }

    public static function setContentSize(int handle, double width, double height) -> void
    {
        nspopover_set_content_size(handle, width, height);
    }

    public static function isShown(int handle) -> bool
    {
        int r;

        let r = nspopover_is_shown(handle);

        return r == 1;
    }

    public static function isDetached(int handle) -> bool
    {
        int r;

        let r = nspopover_is_detached(handle);

        return r == 1;
    }

    public static function positioningRect(int handle) -> array
    {
        var result;

        let result = nspopover_positioning_rect(handle);

        return result;
    }

    public static function setPositioningRect(int handle, double x, double y, double width, double height) -> void
    {
        nspopover_set_positioning_rect(handle, x, y, width, height);
    }

    public static function hasFullSizeContent(int handle) -> bool
    {
        int r;

        let r = nspopover_has_full_size_content(handle);

        return r == 1;
    }

    public static function setHasFullSizeContent(int handle, bool hasFullSizeContent) -> void
    {
        nspopover_set_has_full_size_content(handle, hasFullSizeContent);
    }

    public static function showRelativeToRectOfViewPreferredEdge(int handle, double x, double y, double width, double height, int positioningView, int preferredEdge) -> void
    {
        nspopover_show_relative_to_rect_of_view_preferred_edge(handle, x, y, width, height, positioningView, preferredEdge);
    }

    public static function showRelativeToToolbarItem(int handle, int toolbarItem) -> void
    {
        nspopover_show_relative_to_toolbar_item(handle, toolbarItem);
    }

    public static function performClose(int handle, int sender) -> void
    {
        nspopover_perform_close(handle, sender);
    }

    public static function close(int handle) -> void
    {
        nspopover_close(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
    // @reserved @property NSPopoverAppearance appearance API_DEPRECATED — pre-10.10 duplicate getter
    // @reserved @property NSPopoverAppearance appearance API_DEPRECATED — pre-10.10 duplicate setter

}
