// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace AppKit\NS\NSSearchFieldCell;

class NSSearchFieldCell
{
    public static function initTextCell(string string_) -> int
    {
        return nssearchfieldcell_init_text_cell(string_);
    }

    public static function searchButtonCell(int handle) -> int
    {
        return nssearchfieldcell_search_button_cell(handle);
    }

    public static function setSearchButtonCell(int handle, int searchButtonCell) -> void
    {
        nssearchfieldcell_set_search_button_cell(handle, searchButtonCell);
    }

    public static function cancelButtonCell(int handle) -> int
    {
        return nssearchfieldcell_cancel_button_cell(handle);
    }

    public static function setCancelButtonCell(int handle, int cancelButtonCell) -> void
    {
        nssearchfieldcell_set_cancel_button_cell(handle, cancelButtonCell);
    }

    public static function resetSearchButtonCell(int handle) -> void
    {
        nssearchfieldcell_reset_search_button_cell(handle);
    }

    public static function resetCancelButtonCell(int handle) -> void
    {
        nssearchfieldcell_reset_cancel_button_cell(handle);
    }

    public static function searchTextRectForBounds(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nssearchfieldcell_search_text_rect_for_bounds(handle, x, y, width, height);

        return result;
    }

    public static function searchButtonRectForBounds(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nssearchfieldcell_search_button_rect_for_bounds(handle, x, y, width, height);

        return result;
    }

    public static function cancelButtonRectForBounds(int handle, double x, double y, double width, double height) -> array
    {
        var result;

        let result = nssearchfieldcell_cancel_button_rect_for_bounds(handle, x, y, width, height);

        return result;
    }

    public static function searchMenuTemplate(int handle) -> int
    {
        return nssearchfieldcell_search_menu_template(handle);
    }

    public static function setSearchMenuTemplate(int handle, int searchMenuTemplate) -> void
    {
        nssearchfieldcell_set_search_menu_template(handle, searchMenuTemplate);
    }

    public static function sendsWholeSearchString(int handle) -> bool
    {
        int r;

        let r = nssearchfieldcell_sends_whole_search_string(handle);

        return r == 1;
    }

    public static function setSendsWholeSearchString(int handle, bool sendsWholeSearchString) -> void
    {
        nssearchfieldcell_set_sends_whole_search_string(handle, sendsWholeSearchString);
    }

    public static function maximumRecents(int handle) -> int
    {
        return nssearchfieldcell_maximum_recents(handle);
    }

    public static function setMaximumRecents(int handle, int maximumRecents) -> void
    {
        nssearchfieldcell_set_maximum_recents(handle, maximumRecents);
    }

    public static function recentSearches(int handle) -> array
    {
        var result;

        let result = nssearchfieldcell_recent_searches(handle);

        return result;
    }

    public static function setRecentSearches(int handle, var recentSearches) -> void
    {
        nssearchfieldcell_set_recent_searches(handle, recentSearches);
    }

    public static function recentsAutosaveName(int handle) -> var
    {
        var result;

        let result = nssearchfieldcell_recents_autosave_name(handle);

        return result;
    }

    public static function setRecentsAutosaveName(int handle, var recentsAutosaveName) -> void
    {
        nssearchfieldcell_set_recents_autosave_name(handle, recentsAutosaveName);
    }

    public static function sendsSearchStringImmediately(int handle) -> bool
    {
        int r;

        let r = nssearchfieldcell_sends_search_string_immediately(handle);

        return r == 1;
    }

    public static function setSendsSearchStringImmediately(int handle, bool sendsSearchStringImmediately) -> void
    {
        nssearchfieldcell_set_sends_search_string_immediately(handle, sendsSearchStringImmediately);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved - (instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;
    // @reserved - (instancetype)initImageCell:(nullable NSImage *)image NS_UNAVAILABLE;

}
